{
  "name": "SpaceParts",
  "compatibilityLevel": 1702,
  "model": {
    "name": "SpaceParts",
    "culture": "en-US",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Brands",
        "columns": [
          {
            "name": "Flagship",
            "dataType": "string",
            "sourceColumn": "Flagship",
            "displayFolder": "1. Brand Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "displayFolder": "1. Brand Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "2. Brand Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "displayFolder": "1. Brand Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sub Brand",
            "dataType": "string",
            "sourceColumn": "Sub Brand",
            "displayFolder": "1. Brand Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Brand VP",
            "dataType": "string",
            "sourceColumn": "Product Brand VP",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Brands",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Brands\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Brand Hierarchy",
            "displayFolder": "1. Brand Hierarchy",
            "levels": [
              {
                "name": "Class",
                "ordinal": 0,
                "column": "Class"
              },
              {
                "name": "Flagship",
                "ordinal": 1,
                "column": "Flagship"
              },
              {
                "name": "Brand",
                "ordinal": 2,
                "column": "Brand"
              },
              {
                "name": "Sub Brand",
                "ordinal": 3,
                "column": "Sub Brand"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Budget Rate",
        "isHidden": true,
        "columns": [
          {
            "name": "Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "1. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "From Currency",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "3. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "3. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Budget Rate",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Budget Rate\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Customers",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "4. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Sold-To Name",
            "dataType": "string",
            "sourceColumn": "Customer Sold-To Name",
            "displayFolder": "1. Customer Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Key Account Name",
            "dataType": "string",
            "sourceColumn": "Key Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "Transaction Type",
            "displayFolder": "2. Other Customer Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Type",
            "dataType": "string",
            "sourceColumn": "Account Type",
            "displayFolder": "1. Customer Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Station",
            "displayFolder": "4. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Manager",
            "dataType": "string",
            "sourceColumn": "Account Manager",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Key Account Manager",
            "dataType": "string",
            "sourceColumn": "Key Account Manager",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n\n  // Data Source\n  Source = Sql.Database(\n    #\"SqlEndpoint\", \n    #\"Database\"\n  ), \n\n  // Step\n  Data = Source\n    {\n      [\n        Schema = \"Dimview\", \n        Item   = \"Customers\"\n      ]\n    }\n    [Data]\n\n// Result\nin\n  Data"
            }
          }
        ],
        "measures": [
          {
            "name": "# Customers",
            "expression": "\nCOUNTROWS (\n    VALUES ( 'Customers'[Account Name] )\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures"
          },
          {
            "name": "# Key Accounts",
            "expression": "\nCOUNTROWS (\n    VALUES ( 'Customers'[Key Account Name] )\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "displayFolder": "1. Customer Hierarchy",
            "levels": [
              {
                "name": "Account Type",
                "ordinal": 0,
                "column": "Account Type"
              },
              {
                "name": "Key Account Name",
                "ordinal": 1,
                "column": "Key Account Name"
              },
              {
                "name": "Account Name",
                "ordinal": 2,
                "column": "Account Name"
              },
              {
                "name": "Customer Sold-To Name",
                "ordinal": 3,
                "column": "Customer Sold-To Name"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Employees",
        "isHidden": true,
        "columns": [
          {
            "name": "Role",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Role",
            "displayFolder": "Columns",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Name",
            "displayFolder": "Columns",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Email",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Email",
            "displayFolder": "Columns",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Data Security Rule",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Data Security Rule",
            "displayFolder": "Columns",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Employees\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Exchange Rate",
        "columns": [
          {
            "name": "Rate Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Rate Type",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "sourceColumn": "From Currency",
            "displayFolder": "1. Select a Currency",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Exchange Rate Composite Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Exchange Rate Composite Key",
            "displayFolder": "2. Other Currency Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Exchange Rate",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Exchange Rate\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Invoice Document Type",
        "columns": [
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "sourceColumn": "Billing Document Type Code",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "sortByColumn": "Group Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Invoice Document Type",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Invoice Document Type\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Products",
        "columns": [
          {
            "name": "Sub Brand Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sub Brand Name",
            "displayFolder": "5. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ship Class for Part",
            "dataType": "string",
            "sourceColumn": "Ship Class for Part",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "displayFolder": "1. Product Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Part Fit Grading",
            "dataType": "string",
            "sourceColumn": "Part Fit Grading",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "5. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Subtype",
            "dataType": "string",
            "sourceColumn": "Subtype",
            "displayFolder": "1. Product Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "1. Product Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MK",
            "dataType": "string",
            "sourceColumn": "MK",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Production Series",
            "dataType": "string",
            "sourceColumn": "Production Series",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nameplate",
            "dataType": "string",
            "sourceColumn": "Nameplate",
            "displayFolder": "2. Product Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Material",
            "dataType": "string",
            "sourceColumn": "Material",
            "displayFolder": "1. Product Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Maximum Temperature (K)",
            "dataType": "int64",
            "sourceColumn": "Maximum Temperature (K)",
            "displayFolder": "4. Product Facts",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Business Line Leader",
            "dataType": "string",
            "sourceColumn": "Product Business Line Leader",
            "displayFolder": "3. Product Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Tolerance (g)",
            "dataType": "int64",
            "sourceColumn": "Tolerance (g)",
            "displayFolder": "4. Product Facts",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Velocity Tolerance (Meters / Second)",
            "dataType": "int64",
            "sourceColumn": "Velocity Tolerance (Meters / Second)",
            "displayFolder": "4. Product Facts",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight (Tonnes)",
            "dataType": "double",
            "sourceColumn": "Weight (Tonnes)",
            "displayFolder": "4. Product Facts",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Products\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "measures": [
          {
            "name": "# Products",
            "expression": "\nCOUNTROWS ( \n    VALUES ( 'Products'[Product Name] )\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "displayFolder": "1. Product Hierarchy",
            "levels": [
              {
                "name": "Type",
                "ordinal": 0,
                "column": "Type"
              },
              {
                "name": "Subtype",
                "ordinal": 1,
                "column": "Subtype"
              },
              {
                "name": "Product Name",
                "ordinal": 2,
                "column": "Product Name"
              },
              {
                "name": "Material",
                "ordinal": 3,
                "column": "Material"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Regions",
        "columns": [
          {
            "name": "System",
            "dataType": "string",
            "sourceColumn": "System",
            "displayFolder": "1. Region Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Interplanetary Region",
            "dataType": "string",
            "sourceColumn": "Interplanetary Region",
            "displayFolder": "1. Region Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Territory",
            "dataType": "string",
            "sourceColumn": "Territory",
            "displayFolder": "1. Region Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station",
            "dataType": "string",
            "sourceColumn": "Station",
            "displayFolder": "1. Region Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station Type",
            "dataType": "string",
            "sourceColumn": "Station Type",
            "displayFolder": "2. Region Attributes",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Territory Directors",
            "dataType": "string",
            "sourceColumn": "Territory Directors",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "All",
            "dataType": "string",
            "sourceColumn": "All",
            "displayFolder": "1. Region Hierarchy",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station Sales Managers",
            "dataType": "string",
            "sourceColumn": "Station Sales Managers",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "System Regional Managers",
            "dataType": "string",
            "sourceColumn": "System Regional Managers",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "System Sales Directors",
            "dataType": "string",
            "sourceColumn": "System Sales Directors",
            "displayFolder": "3. Managers",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Tax Rate",
            "formatString": "#,##0.000",
            "displayFolder": "2. Region Attributes",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Regions",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Regions\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Regional Hierarchy",
            "displayFolder": "1. Region Hierarchy",
            "levels": [
              {
                "name": "Territory",
                "ordinal": 3,
                "column": "Territory"
              },
              {
                "name": "System",
                "ordinal": 1,
                "column": "System"
              },
              {
                "name": "Station",
                "ordinal": 4,
                "column": "Station"
              },
              {
                "name": "Interplanetary Region",
                "ordinal": 2,
                "column": "Interplanetary Region"
              },
              {
                "name": "All",
                "ordinal": 0,
                "column": "All"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Budget",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Month",
            "formatString": "Long Date",
            "displayFolder": "1. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Budget (EUR)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Budget (EUR)",
            "displayFolder": "2. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "1. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "1. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Budget",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Factview\",Item=\"Budget\"]}[Data],\n    #\"Select Columns\" = Table.SelectColumns ( Data, {\"Customer Key\", \"Month\", \"Product Key\", \"Total Budget\"} ),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Select Columns\",{{\"Total Budget\", \"Budget (EUR)\"}})\nin\n    #\"Renamed Columns\""
            }
          }
        ],
        "measures": [
          {
            "name": "2022 Budget Achievement %",
            "expression": "\nVAR _Sales =\n    CALCULATE (\n        [Gross Sales],\n        'Date'[Calendar Year Number (ie 2021)]\n            = 2022,\n        'Date'[IsDateInScope] = TRUE ( ),\n        DATESYTD ( 'Date'[Date] )\n    )\nVAR _Budget =\n    CALCULATE (\n        [Total Budget],\n        'Date'[Calendar Year Number (ie 2021)]\n            = 2022,\n        'Date'[IsDateInScope] = TRUE ( ),\n        DATESYTD ( 'Date'[Date] )\n    )\nVAR _Delta = _Sales - _Budget\nVAR _Perc = DIVIDE ( _Delta, _Budget )\nRETURN\n    _Perc",
            "formatString": "#,##0.0%",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Budget MTD",
            "expression": "\n-- Calculates the target for the current month/year selection\nVAR _CURRENT_MONTH_VALUE =\n    CALCULATE (\n        [Budget],\n        ALL ( 'Date' ),\n        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )\n    ) \n\n-- Computes rate at which Budget increases through the month\nVAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        1.035\n    )\n\nVAR _CURRENT_MONTH_PERC_WORKDAYS =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        1.035\n    )\n\nVAR _PERIOD =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\nVAR _HASONEMONTH =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        _HASONEMONTH\n            && _PERIOD = \"Full Period\",\n        _CURRENT_MONTH_PERC_WORKDAYS\n            * _CURRENT_MONTH_VALUE,\n\n        IF (\n            _HASONEMONTH,\n            _CURRENT_MONTH_PERC_WORKDAYS_MTD\n                * _CURRENT_MONTH_VALUE\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Budget MTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Budget MTD]\nVAR _DELTA  = [MTD Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Budget MTD vs. Gross Sales (Δ)",
            "expression": "\n[MTD Gross Sales] - [Budget MTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Budget QTD",
            "expression": "\nVAR _DATES_QTD =\n    CALCULATETABLE (\n        DATESQTD ('Date'[Date]),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _CURRENT_MONTH_Budget = [Budget MTD]\nVAR QTD_BUDGET_BEFORE_THIS_MONTH = CALCULATE ([Budget], _DATES_QTD)\nVAR _RESULT = _CURRENT_MONTH_Budget + QTD_BUDGET_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Budget QTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Budget QTD]\nVAR _DELTA  = [Gross Sales] - [Budget QTD]\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Budget QTD vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Budget QTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Budget YTD",
            "expression": "\nVAR _DATES_YTD =\n    CALCULATETABLE (\n        DATESYTD ( 'Date'[Date] ),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _CURRENT_MONTH_Budget = [Budget MTD]\nVAR QTD_Budget_BEFORE_THIS_MONTH =\n    CALCULATE ( [Budget], _DATES_YTD )\nVAR _RESULT =\n    _CURRENT_MONTH_Budget\n        + QTD_Budget_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Budget YTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Budget YTD]\nVAR _DELTA  = [Gross Sales] - [Budget YTD]\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Budget YTD vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Budget YTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Total Budget",
            "expression": "\n    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )\nRETURN\n    SUM ( 'Budget'[Budget (EUR)] ) * _SelectedRate",
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Budget",
            "expression": "\nIF.EAGER(\n    HASONEVALUE( '2) Selected Unit'[Select a Unit] )\n        && \n    HASONEVALUE( 'Exchange Rate'[From Currency] ),\n\n    VAR _SELECTED_CURRENCY = \n        SELECTEDVALUE( 'Exchange Rate'[From Currency] )\n\n    VAR _SELECTED_RATE_TYPE = \n        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )\n    \n    VAR _SELECTED_BUDGET_RATE =\n        MAX( 'Exchange Rate'[Rate] )\n        \n    VAR _SELECTED_MONTHLY_RATE =\n        ADDCOLUMNS(\n            SUMMARIZE(\n                'Exchange Rate',\n                'Date'[Calendar Month Year (ie Jan 21)]\n            ),\n            \"Curr\", \n            CALCULATE ( \n                MAX( 'Exchange Rate'[Rate] ) \n            )\n        )\n        \n    RETURN\n\n    IF(\n        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",\n        SUM ( 'Budget'[Budget (EUR)]) \n        * \n        _SELECTED_BUDGET_RATE,\n        \n        IF(\n            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",\n            SUMX(\n                _SELECTED_MONTHLY_RATE,\n                CALCULATE( \n                    SUM ( 'Budget'[Budget (EUR)])\n                )\n                * [Curr]\n            )\n        )\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Budget vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Budget]\nVAR _DELTA  = [Gross Sales] - [Budget]\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Budget vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Budget]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Invoices",
        "columns": [
          {
            "name": "Billing Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Number",
            "displayFolder": "Columns\\1. Degenerate Dimensions\\Document #s",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "formatString": "Long Date",
            "sourceProviderType": "date",
            "displayFolder": "Columns\\2. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Line Item Number",
            "displayFolder": "Columns\\1. Degenerate Dimensions\\Document #s",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "Long Date",
            "sourceProviderType": "date",
            "displayFolder": "Columns\\2. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "OTD Indicator",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Billing Document Type Code",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Delivery Cost",
            "dataType": "double",
            "description": "The cost of the delivery only",
            "isHidden": true,
            "sourceColumn": "Delivery Cost",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Invoice COGS",
            "dataType": "double",
            "description": "All costs associated with the sold product",
            "isHidden": true,
            "sourceColumn": "Net Invoice COGS",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Late Delivery Penalties",
            "dataType": "double",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "isHidden": true,
            "sourceColumn": "Late Delivery Penalties",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Overdue Payment Penalties",
            "dataType": "double",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "isHidden": true,
            "sourceColumn": "Overdue Payment Penalties",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Taxes & Commercial Fees",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes & Commercial Fees",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Freight",
            "dataType": "double",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "isHidden": true,
            "sourceColumn": "Freight",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Invoice Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Invoice Value",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Invoice Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Invoice Quantity",
            "displayFolder": "Columns\\0. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Invoices",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Factview\",Item=\"Invoices\"]}[Data],\n    #\"Select Columns\" = Table.RemoveColumns ( Data, {\"DWCreatedDate\", \"Net Invoice Cost\"} )\nin\n    #\"Select Columns\"\n\n\n//   ,#\"Incremental Refresh\" = Table.SelectRows( #\"Select Columns\" , each [Billing Date] >= Date.From ( #\"RangeStart\" ) and [Billing Date] < Date.From ( #\"RangeEnd\" ) )\n//in\n//    #\"Incremental Refresh\""
            }
          }
        ],
        "measures": [
          {
            "name": "Delivery Margin (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "\nVAR _TOTAL =\n    CALCULATE (\n        [Total Freight Surcharge],\n        'Invoice Document Type'[Billing Document Type Code] IN {\"invoice\", \"express\"}\n    )\nVAR _MARGIN = [Delivery Margin (Value)]\nRETURN\n    DIVIDE (_MARGIN, _TOTAL)",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%"
          },
          {
            "name": "Delivery Margin (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "CALCULATE (\n    SUMX (\n        'Invoices',\n        'Invoices'[Freight] - 'Invoices'[Delivery Cost]\n    ),\n    'Invoice Document Type'[Billing Document Type Code] IN { \"invoice\", \"express\" }\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$"
          },
          {
            "name": "Delivery Margin 1YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "CALCULATE (\n    [Delivery Margin (%)],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%"
          },
          {
            "name": "Delivery Margin 1YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "CALCULATE (\n    [Delivery Margin (Value)],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$"
          },
          {
            "name": "Delivery Margin 2YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "CALCULATE (\n    [Delivery Margin (%)],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%"
          },
          {
            "name": "Delivery Margin 2YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": "CALCULATE (\n    [Delivery Margin (Value)],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$"
          },
          {
            "name": "Gross Sales",
            "expression": "\n[Total Net Invoice Value]\n    + [Total Freight Surcharge]\n    + [Total Late Delivery Penalties]\n    + [Total Overdue Payment Penalties]\n    - [Total Taxes & Commercial Fees]",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total"
          },
          {
            "name": "Gross Sales (Quantity)",
            "expression": "\n[Total Net Invoice Quantity]",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals"
          },
          {
            "name": "Gross Sales (Selected Unit)",
            "expression": "\n-- Sideways recursion\nCALCULATE (\n    [Actuals],\n    ALL ( '1) Selected Metric'[Select a Measure] ),\n    '1) Selected Metric'[Select a Measure] = \"Gross Sales\"\n)",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total"
          },
          {
            "name": "Gross Sales 1YP",
            "expression": "\nCALCULATE (\n    [Gross Sales],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily"
          },
          {
            "name": "Gross Sales 1YP (Quantity)",
            "expression": "\nCALCULATE (\n    [Gross Sales (Quantity)],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals"
          },
          {
            "name": "MTD Gross Sales 1YP",
            "expression": "\n-- Calculates Target for the current month/year selection\nVAR _CurrentMonth =\n    CALCULATE (\n        [Gross Sales 1YP],\n        ALL ( 'Date' ),\n        VALUES (\n            'Date'[Calendar Month Year (ie Jan 21)]\n        )\n    )\n\n-- Computes rate at which Target increases through the month\nVAR _CurrentMonthWDMTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        0.93\n    )\nVAR _CurrentMonthWDTotal =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        0.93\n    )\nVAR _Period =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\nVAR _HasOneMonth =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        _HasOneMonth && _Period = \"Full Period\",\n        _CurrentMonthWDTotal\n            * _CurrentMonth,\n        IF (\n            _HasOneMonth,\n            _CurrentMonthWDMTD\n                * _CurrentMonth\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD"
          },
          {
            "name": "Gross Sales 2YP",
            "expression": "\nCALCULATE (\n    [Gross Sales],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily"
          },
          {
            "name": "MTD Gross Sales 2YP",
            "expression": "\n-- Calculates Target for the current month/year selection\nVAR _CurrentMonth =\n    CALCULATE (\n        [Gross Sales 2YP],\n        ALL ( 'Date' ),\n        VALUES (\n            'Date'[Calendar Month Year (ie Jan 21)]\n        )\n    )\n\n-- Computes rate at which Target increases through the month\nVAR _CurrentMonthWDMTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        0.93\n    )\nVAR _CurrentMonthWDTotal =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        0.93\n    )\nVAR _Period =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\nVAR _HasOneMonth =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        _HasOneMonth && _Period = \"Full Period\",\n        _CurrentMonthWDTotal\n            * _CurrentMonth,\n        IF (\n            _HasOneMonth,\n            _CurrentMonthWDMTD\n                * _CurrentMonth\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD"
          },
          {
            "name": "MTD Gross Sales",
            "expression": "\nCALCULATE (\n    [Gross Sales],\n    CALCULATETABLE (\n        DATESMTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total"
          },
          {
            "name": "Invoice Lines",
            "expression": "\nCOUNTROWS ( 'Invoices' )",
            "formatString": "#,##0",
            "displayFolder": "3. Lines"
          },
          {
            "name": "Net Sales",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n    CALCULATE (\n\n        -- Convert to common currency (WAT)\n        SUMX (\n            'Invoices',\n\n            -- Net sales\n            DIVIDE('Invoices'[Net Invoice Value]\n                + 'Invoices'[Freight]\n                - 'Invoices'[Taxes & Commercial Fees]\n                + 'Invoices'[Late Delivery Penalties]\n                + 'Invoices'[Overdue Payment Penalties],\n                RELATED ('Budget Rate'[Rate])\n            )\n        )\n\n            -- Convert to selected currency\n            * _RATE,\n\n        -- Limit to dates in scope\n        'Date'[IsDateInScope] = TRUE\n    )",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales"
          },
          {
            "name": "Net Sales 1YP",
            "expression": "\nCALCULATE (\n    [Net Sales],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales"
          },
          {
            "name": "Net Sales 2YP",
            "expression": "\nCALCULATE (\n    [Net Sales],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales"
          },
          {
            "name": "Selling Margin (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "VAR _TOTAL =\n    CALCULATE (\n        [Total Net Invoice Value],\n        'Invoice Document Type'[Billing Document Type Code] = \"invoice\"\n    )\nVAR _MARGIN = [Selling Margin (Value)]\nRETURN\n    DIVIDE (_MARGIN, _TOTAL)",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%"
          },
          {
            "name": "Selling Margin (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "\nCALCULATE (\n    SUMX (\n        'Invoices',\n        'Invoices'[Net Invoice Value] - 'Invoices'[Net Invoice COGS]\n    ),\n    'Invoice Document Type'[Billing Document Type Code] = \"invoice\"\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$"
          },
          {
            "name": "Selling Margin 1YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "CALCULATE (\n    [Selling Margin (%)],\n    DATEADD ('Date'[Date], -1, YEAR)\n) ",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%"
          },
          {
            "name": "Selling Margin 1YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "CALCULATE (\n    [Selling Margin (Value)],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$"
          },
          {
            "name": "Selling Margin 2YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "CALCULATE (\n    [Selling Margin (%)],\n    DATEADD ('Date'[Date], -2, YEAR)\n) ",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%"
          },
          {
            "name": "Selling Margin 2YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": "CALCULATE (\n    [Selling Margin (Value)],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$"
          },
          {
            "name": "Standard Margin (%)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "\nDIVIDE ( [Standard Margin (Value)], [Net Sales] ) ",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%"
          },
          {
            "name": "Standard Margin (Value)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n    CALCULATE (\n\n        -- Convert to common currency (WAT)\n        SUMX (\n            'Invoices',\n\n            -- Net Sales\n            VAR _NET = \n            ('Invoices'[Net Invoice Value]\n                + 'Invoices'[Freight]\n                - 'Invoices'[Taxes & Commercial Fees]\n                + 'Invoices'[Late Delivery Penalties]\n                + 'Invoices'[Overdue Payment Penalties] )\n\n            -- COGS\n            VAR _COST =\n            ('Invoices'[Net Invoice COGS] \n                + 'Invoices'[Delivery Cost] )\n\n            RETURN\n\n            ( _NET - _COST ) / RELATED ('Budget Rate'[Rate])\n        )\n\n            -- Convert to selected rate\n            * _RATE,\n\n        -- Limit to dates in scope\n        'Date'[IsDateInScope] = TRUE\n    )",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$"
          },
          {
            "name": "Standard Margin 1YP (%)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "CALCULATE (\n    [Standard Margin (%)],\n    DATEADD ('Date'[Date], -1, YEAR)\n) ",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%"
          },
          {
            "name": "Standard Margin 1YP (Value)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "CALCULATE (\n    [Standard Margin (Value)],\n    DATEADD ('Date'[Date], -1, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$"
          },
          {
            "name": "Standard Margin 2YP (%)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "CALCULATE (\n    [Standard Margin (%)],\n    DATEADD ('Date'[Date], -2, YEAR)\n) ",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%"
          },
          {
            "name": "Standard Margin 2YP (Value)",
            "description": "The standard margin is the selling margin + the delivery margin\nIt takes into account all revenues and costs.",
            "expression": "CALCULATE (\n    [Standard Margin (Value)],\n    DATEADD ('Date'[Date], -2, YEAR)\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$"
          },
          {
            "name": "Total Cost",
            "description": "The cost of the product sold and the shipment / delivery",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n    CALCULATE (\n\n        -- Convert to common currency (WAT)\n        SUMX (\n            'Invoices',\n\n            -- COGS\n            ('Invoices'[Net Invoice COGS] + 'Invoices'[Delivery Cost])\n                / RELATED ('Budget Rate'[Rate])\n        )\n\n            -- Convert to selected currency\n            * _RATE,\n\n        -- Limit to dates in scope\n        'Date'[IsDateInScope] = TRUE\n    )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost"
          },
          {
            "name": "Total Delivery Cost",
            "description": "The cost of the delivery only",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Delivery Cost]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost"
          },
          {
            "name": "Total Fees & Penalties",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n    CALCULATE (\n\n        -- Convert to common currency (WAT)\n        SUMX (\n            'Invoices',\n\n            -- Total fees & penalties\n            ('Invoices'[Late Delivery Penalties]\n                + 'Invoices'[Overdue Payment Penalties]\n                - 'Invoices'[Taxes & Commercial Fees])\n\n                / RELATED ('Budget Rate'[Rate])\n        )\n\n            -- Convert to selected currency\n            * _RATE,\n\n        -- Limit to dates in scope\n        'Date'[IsDateInScope] = TRUE\n    )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments"
          },
          {
            "name": "Total Freight Surcharge",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n    CALCULATE (\n\n        -- Convert to common currency (WAT)\n        SUMX (\n            'Invoices',\n            'Invoices'[Freight]\n                / RELATED ('Budget Rate'[Rate])\n        )\n\n            -- Convert to selected currency\n            * _RATE,\n\n        -- Limit to dates in scope\n        'Date'[IsDateInScope] = TRUE\n    )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\III. Freight"
          },
          {
            "name": "Total Late Delivery Penalties",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Late Delivery Penalties]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments"
          },
          {
            "name": "Total Net Invoice COGS",
            "description": "All costs associated with the sold product",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Net Invoice COGS]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost"
          },
          {
            "name": "Total Net Invoice Quantity",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Quantity]",
            "expression": "SUM ( 'Invoices'[Net Invoice Quantity] )",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals"
          },
          {
            "name": "Total Net Invoice Value",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Value]",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Net Invoice Value]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total"
          },
          {
            "name": "Total Overdue Payment Penalties",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Overdue Payment Penalties]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments"
          },
          {
            "name": "Total Taxes & Commercial Fees",
            "description": "This measure is theSumof column 'Invoices'[Taxes & Commercial Fees]",
            "expression": "SUMX (\n    'Invoices',\n    'Invoices'[Taxes & Commercial Fees]\n        / RELATED ( 'Budget Rate'[Rate] )\n)\n    * MAX ( 'Exchange Rate'[Rate] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments"
          },
          {
            "name": "MTD Gross Sales vs 1YP (%)",
            "expression": "\nVAR _TARGET = [MTD Gross Sales 1YP]\nVAR _DELTA  = [MTD Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD"
          },
          {
            "name": "MTD Gross Sales vs 1YP (Δ)",
            "expression": "\n[MTD Gross Sales] - [MTD Gross Sales 1YP]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD"
          },
          {
            "name": "Gross Sales vs 1YP (%)",
            "expression": "\nVAR _TARGET = [Gross Sales 1YP]\nVAR _DELTA  = [Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily"
          },
          {
            "name": "Gross Sales vs 1YP (Δ)",
            "expression": "\n[Gross Sales] - [Gross Sales 1YP]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily"
          },
          {
            "name": "MTD Gross Sales vs 2YP (%)",
            "expression": "\nVAR _TARGET = [MTD Gross Sales 1YP]\nVAR _DELTA  = [MTD Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD"
          },
          {
            "name": "MTD Gross Sales vs. 2YP (Δ)",
            "expression": "\n[MTD Gross Sales] - [MTD Gross Sales 1YP]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD"
          },
          {
            "name": "Gross Sales vs 2YP (%)",
            "expression": "\nVAR _TARGET = [Gross Sales 2YP]\nVAR _DELTA  = [Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily"
          },
          {
            "name": "Gross Sales vs 2YP (Δ)",
            "expression": "\n[Gross Sales] - [Gross Sales 2YP]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Date",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "displayFolder": "6. Calendar Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Number (ie 2021)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Number (ie 2021)]",
            "displayFolder": "1. Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year (ie 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year (ie 2021)]",
            "sortByColumn": "Calendar Year Number (ie 2021)",
            "displayFolder": "1. Year",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter Year (ie Q1 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter Year (ie Q1 2021)]",
            "sortByColumn": "Calendar Year Quarter (ie 202101)",
            "displayFolder": "2. Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Quarter (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Quarter (ie 202101)]",
            "displayFolder": "2. Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Year (ie Jan 21)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Year (ie Jan 21)]",
            "sortByColumn": "Calendar Year Month (ie 202101)",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Month (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Month (ie 202101)]",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month (ie Jan)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month (ie Jan)]",
            "sortByColumn": "Calendar Month # (ie 1)",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month # (ie 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month # (ie 1)]",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week EU (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week EU (ie WK25)]",
            "sortByColumn": "Calendar Week Number EU (ie 25)",
            "displayFolder": "4. Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number EU (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number EU (ie 25)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number EU (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number EU (ie 202125)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week US (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week US (ie WK25)]",
            "sortByColumn": "Calendar Week Number US (ie 25)",
            "displayFolder": "4. Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number US (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number US (ie 25)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number US (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number US (ie 202125)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week ISO (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week ISO (ie WK25)]",
            "sortByColumn": "Calendar Week Number ISO (ie 25)",
            "displayFolder": "4. Week",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number ISO (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number ISO (ie 25)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number ISO (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number ISO (ie 202125)]",
            "displayFolder": "4. Week",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Short (i.e. Mon)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Short (i.e. Mon)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Name (i.e. Monday)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Name (i.e. Monday)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Number EU (i.e. 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Number EU (i.e. 1)]",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. Jan 05)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. Jan 05)]",
            "sortByColumn": "Calendar Month Day (i.e. 0105)",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. 0105)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. 0105)]",
            "displayFolder": "3. Month",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YYYYMMDD",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YYYYMMDD]",
            "displayFolder": "6. Calendar Date",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsDateInScope",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsDateInScope]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsBeforeThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsBeforeThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsLastMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsLastMonth]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsYTD",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsYTD]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsActualToday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsActualToday]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsRefDate",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsRefDate]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsHoliday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsHoliday]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWeekday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWeekday]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisYear",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisYear]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisQuarter",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisQuarter]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisWeek",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisWeek]",
            "displayFolder": "7. Boolean Fields",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays MTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "VAR _Holidays =\n    CALCULATETABLE (\n        DISTINCT ('Date'[Date]),\n        'Date'[IsHoliday] <> TRUE\n    )\nVAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )\nVAR _WeekendDays = SWITCH (\n        _WeekdayName,\n        \"Sat\", 2,\n        \"Sun\", 3,\n        0\n    )\nVAR _WorkdaysMTD =\n    CALCULATE (\n        NETWORKDAYS (\n            CALCULATE (\n                MIN ('Date'[Date]),\n                ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])\n            ),\n            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),\n            1,\n            _Holidays\n        )\n    )\n        + 1\nRETURN\n    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays QTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "VAR _Holidays =\n    CALCULATETABLE (\n        DISTINCT ('Date'[Date]),\n        'Date'[IsHoliday] <> TRUE\n    )\nVAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )\nVAR _WeekendDays = SWITCH (\n        _WeekdayName,\n        \"Sat\", 2,\n        \"Sun\", 3,\n        0\n    )\nVAR _WorkdaysMTD =\n    CALCULATE (\n        NETWORKDAYS (\n            CALCULATE (\n                MIN ('Date'[Date]),\n                ALLEXCEPT ('Date', 'Date'[Calendar Quarter Year (ie Q1 2021)])\n            ),\n            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),\n            1,\n            _Holidays\n        )\n    )\n        + 1\nRETURN\n    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays YTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": "VAR _Holidays =\n    CALCULATETABLE (\n        DISTINCT ('Date'[Date]),\n        'Date'[IsHoliday] <> TRUE\n    )\nVAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )\nVAR _WeekendDays = SWITCH (\n        _WeekdayName,\n        \"Sat\", 2,\n        \"Sun\", 3,\n        0\n    )\nVAR _WorkdaysMTD =\n    CALCULATE (\n        NETWORKDAYS (\n            CALCULATE (\n                MIN ('Date'[Date]),\n                ALLEXCEPT ('Date', 'Date'[Calendar Year (ie 2021)])\n            ),\n            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),\n            1,\n            _Holidays\n        )\n    )\n        + 1\nRETURN\n    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays MTD %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": "DIVIDE (\n    'Date'[Workdays MTD],\n    /* Number of weekdays MTD for selected month */\n    CALCULATE (\n        [# Workdays in Selected Month],\n        ALLEXCEPT ( 'Date', 'Date'[Calendar Month Year (ie Jan 21)] )\n    ),\n    /* Total number of weekdays for selected month */\n    0\n)",
            "formatString": "0.00%",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter (ie Q1)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter (ie Q1)]",
            "displayFolder": "2. Quarter",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\n-- Reference date for the latest date in the report\n-- Until when the business wants to see data in reports\nVAR _Refdate_Measure = [RefDate]\nVAR _Today = TODAY ( )\n\n-- Replace with \"Today\" if [RefDate] evaluates blank\nVAR _Refdate = IF ( ISBLANK ( _Refdate_Measure ), _Today, _Refdate_Measure )\n    VAR _RefYear        = YEAR ( _Refdate )\n    VAR _RefQuarter     = _RefYear * 100 + QUARTER(_Refdate)\n    VAR _RefMonth       = _RefYear * 100 + MONTH(_Refdate)\n    VAR _RefWeek_EU     = _RefYear * 100 + WEEKNUM(_Refdate, 2)\n \n-- Earliest date in the model scope\nVAR _EarliestDate       = DATE ( YEAR ( MIN ( 'Orders'[Order Date] ) ) - 2, 1, 1 )\nVAR _EarliestDate_Safe  = MIN ( _EarliestDate, DATE ( YEAR ( _Today ) + 1, 1, 1 ) )\n\n-- Latest date in the model scope\nVAR _LatestDate_Safe    = DATE ( YEAR ( _Refdate ) + 2, 12, 1 )\n\n------------------------------------------\n-- Base calendar table\nVAR _Base_Calendar      = CALENDAR ( _EarliestDate_Safe, _LatestDate_Safe )\n------------------------------------------\n\n\n\n------------------------------------------\nVAR _IntermediateResult = \n    ADDCOLUMNS ( _Base_Calendar,\n\n            ------------------------------------------\n        \"Calendar Year Number (ie 2021)\",           --|\n            YEAR ([Date]),                          --|-- Year\n                                                    --|\n        \"Calendar Year (ie 2021)\",                  --|\n            FORMAT ([Date], \"YYYY\"),                --|\n            ------------------------------------------\n\n            ------------------------------------------\n        \"Calendar Quarter Year (ie Q1 2021)\",       --|\n            \"Q\" &                                   --|-- Quarter\n            CONVERT(QUARTER([Date]), STRING) &      --|\n            \" \" &                                   --|\n            CONVERT(YEAR([Date]), STRING),          --|\n                                                    --|\n        \"Calendar Year Quarter (ie 202101)\",        --|\n            YEAR([Date]) * 100 + QUARTER([Date]),   --|\n                                                    --| \n        \"Calendar Quarter (ie Q1)\",                 --|\n            \"Q\" &                                   --|\n            CONVERT(QUARTER([Date]), STRING),       --|  \n            ------------------------------------------\n\n            ------------------------------------------\n        \"Calendar Month Year (ie Jan 21)\",          --|\n            FORMAT ( [Date], \"MMM YY\" ),            --|-- Month\n                                                    --|\n        \"Calendar Year Month (ie 202101)\",          --|\n            YEAR([Date]) * 100 + MONTH([Date]),     --|\n                                                    --|\n        \"Calendar Month (ie Jan)\",                  --|\n            FORMAT ( [Date], \"MMM\" ),               --|\n                                                    --|\n        \"Calendar Month # (ie 1)\",                  --|\n            MONTH ( [Date] ),                       --|\n            ------------------------------------------\n            \n            ------------------------------------------\n        \"Calendar Week EU (ie WK25)\",               --|\n            \"WK\" & WEEKNUM( [Date], 2 ),            --|-- Week\n                                                    --|\n        \"Calendar Week Number EU (ie 25)\",          --|\n            WEEKNUM( [Date], 2 ),                   --|\n                                                    --|\n        \"Calendar Year Week Number EU (ie 202125)\", --|\n            YEAR ( [Date] ) * 100                   --|\n            +                                       --|\n            WEEKNUM( [Date], 2 ),                   --|\n                                                    --|\n        \"Calendar Week US (ie WK25)\",               --|\n            \"WK\" & WEEKNUM( [Date], 1 ),            --|\n                                                    --|\n        \"Calendar Week Number US (ie 25)\",          --|\n            WEEKNUM( [Date], 1 ),                   --|\n                                                    --|\n        \"Calendar Year Week Number US (ie 202125)\", --|\n            YEAR ( [Date] ) * 100                   --|\n            +                                       --|\n            WEEKNUM( [Date], 1 ),                   --|\n                                                    --|\n        \"Calendar Week ISO (ie WK25)\",              --|\n            \"WK\" & WEEKNUM( [Date], 21 ),           --|\n                                                    --|\n        \"Calendar Week Number ISO (ie 25)\",         --|\n            WEEKNUM( [Date], 21 ),                  --|\n                                                    --|\n        \"Calendar Year Week Number ISO (ie 202125)\",--|\n            YEAR ( [Date] ) * 100                   --|\n            +                                       --|\n            WEEKNUM( [Date], 21 ),                  --|\n            ------------------------------------------\n\n            ------------------------------------------\n        \"Weekday Short (i.e. Mon)\",                 --|\n            FORMAT ( [Date], \"DDD\" ),               --|-- Weekday\n                                                    --|\n        \"Weekday Name (i.e. Monday)\",               --|\n            FORMAT ( [Date], \"DDDD\" ),              --|\n                                                    --|\n        \"Weekday Number EU (i.e. 1)\",               --|\n            WEEKDAY ( [Date], 2 ),                  --|\n            ------------------------------------------\n            \n            ------------------------------------------\n        \"Calendar Month Day (i.e. Jan 05)\",         --|\n            FORMAT ( [Date], \"MMM DD\" ),            --|-- Day\n                                                    --|\n        \"Calendar Month Day (i.e. 0105)\",           --|\n            MONTH([Date]) * 100                     --|\n            +                                       --|\n            DAY([Date]),                            --|\n                                                    --|\n        \"YYYYMMDD\",                                 --|\n            YEAR ( [Date] ) * 10000                 --|\n            +                                       --|\n            MONTH ( [Date] ) * 100                  --|\n            +                                       --|\n            DAY ( [Date] ),                         --|\n            ------------------------------------------\n\n\n            ------------------------------------------\n        \"IsDateInScope\",                            --|\n            [Date] <= _Refdate                      --|-- Boolean\n            &&                                      --|\n            YEAR([Date]) > YEAR(_EarliestDate),     --|\n                                                    --|\n        \"IsBeforeThisMonth\",                        --|\n            [Date] <= EOMONTH ( _Refdate, -1 ),     --|\n                                                    --|\n        \"IsLastMonth\",                              --|\n            [Date] <= EOMONTH ( _Refdate, 0 )       --|\n            &&                                      --|\n            [Date] > EOMONTH ( _Refdate, -1 ),      --|\n                                                    --|\n        \"IsYTD\",                                    --|\n            MONTH([Date])                           --|\n            <=                                      --|\n            MONTH(EOMONTH ( _Refdate, 0 )),         --|\n                                                    --|\n        \"IsActualToday\",                            --|\n            [Date] = _Today,                        --|\n                                                    --|\n        \"IsRefDate\",                                --|\n            [Date] = _Refdate,                      --|\n                                                    --|\n        \"IsHoliday\",                                --|\n            MONTH([Date]) * 100                     --|\n            +                                       --|\n            DAY([Date])                             --|\n                IN {0101, 0501, 1111, 1225},        --|\n                                                    --|\n        \"IsWeekday\",                                --|\n            WEEKDAY([Date], 2)                      --|\n                IN {1, 2, 3, 4, 5})                 --|\n            ------------------------------------------\n\nVAR _Result = \n    \n            --------------------------------------------\n    ADDCOLUMNS (                                      --|\n        _IntermediateResult,                          --|-- Boolean #2\n        \"IsThisYear\",                                 --|\n            [Calendar Year Number (ie 2021)]          --|\n                = _RefYear,                           --|\n                                                      --|\n        \"IsThisMonth\",                                --|\n            [Calendar Year Month (ie 202101)]         --|\n                = _RefMonth,                          --|\n                                                      --|\n        \"IsThisQuarter\",                              --|\n            [Calendar Year Quarter (ie 202101)]       --|\n                = _RefQuarter,                        --|\n                                                      --|\n        \"IsThisWeek\",                                 --|\n            [Calendar Year Week Number EU (ie 202125)]--|\n                = _RefWeek_EU                         --|\n    )                                                 --|\n            --------------------------------------------\n            \nRETURN \n    _Result"
            }
          }
        ],
        "measures": [
          {
            "name": "# Workdays MTD",
            "expression": "CALCULATE(\n    MAX( 'Date'[Workdays MTD] ),\n    'Date'[IsDateInScope] = TRUE\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "# Workdays QTD",
            "expression": "CALCULATE(\n    MAX( 'Date'[Workdays QTD] ),\n    'Date'[IsDateInScope] = TRUE\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "# Workdays YTD",
            "expression": "CALCULATE(\n    MAX( 'Date'[Workdays YTD] ),\n    'Date'[IsDateInScope] = TRUE\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "# Workdays in Selected Month",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),\n    CALCULATE (\n        MAX ('Date'[Workdays MTD]),\n        VALUES ('Date'[Calendar Month Year (ie Jan 21)])\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "# Workdays in Selected Quarter",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),\n    CALCULATE (\n        MAX ('Date'[Workdays QTD]),\n        VALUES ('Date'[Calendar Quarter Year (ie Q1 2021)])\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "# Workdays in Selected Year",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),\n    CALCULATE (\n        MAX ('Date'[Workdays YTD]),\n        VALUES ('Date'[Calendar Year (ie 2021)])\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "% Workdays MTD",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),\n    MROUND (\n        DIVIDE ([# Workdays MTD], [# Workdays in Selected Month]),\n        0.01\n    )\n)",
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "% Workdays QTD",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),\n    MROUND (\n        DIVIDE ([# Workdays QTD], [# Workdays in Selected Quarter]),\n        0.01\n    )\n)",
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "% Workdays YTD",
            "expression": "IF (\n    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),\n    MROUND (\n        DIVIDE ([# Workdays YTD], [# Workdays in Selected Year]),\n        0.01\n    )\n)",
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays"
          },
          {
            "name": "RefDate",
            "expression": "CALCULATE ( MAX ( 'Invoices'[Billing Date] ), REMOVEFILTERS ( ) )",
            "isHidden": true,
            "displayFolder": "Measures"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "levels": [
              {
                "name": "Calendar Year (ie 2021)",
                "ordinal": 0,
                "column": "Calendar Year (ie 2021)"
              },
              {
                "name": "Calendar Month (ie Jan)",
                "ordinal": 2,
                "column": "Calendar Month (ie Jan)"
              },
              {
                "name": "Calendar Quarter (ie Q1)",
                "ordinal": 1,
                "column": "Calendar Quarter (ie Q1)"
              },
              {
                "name": "Calendar Week EU (ie WK25)",
                "ordinal": 3,
                "column": "Calendar Week EU (ie WK25)"
              },
              {
                "name": "Weekday Short (i.e. Mon)",
                "ordinal": 4,
                "column": "Weekday Short (i.e. Mon)"
              },
              {
                "name": "Date",
                "ordinal": 5,
                "column": "Date"
              }
            ]
          }
        ]
      },
      {
        "name": "On-Time Delivery",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Invoices[OTD Indicator]",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Status",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Status]",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\1. OTD",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Sort Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Sort Order]",
            "displayFolder": "Columns\\3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "On-Time Delivery",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nADDCOLUMNS (\n    FILTER (\n        DISTINCT ('Invoices'[OTD Indicator]),\n        NOT ISBLANK ('Invoices'[OTD Indicator])\n    ),\n    \"OTD Status\",\n        SWITCH (\n            TRUE (),\n            'Invoices'[OTD Indicator] = TRUE, \"On Time\",\n            \"Late\"\n        ),\n    \"OTD Sort Order\",\n        SWITCH (\n            TRUE (),\n            'Invoices'[OTD Indicator] = TRUE, 1,\n            2\n        )\n)"
            }
          }
        ],
        "measures": [
          {
            "name": "OTD % (Lines)",
            "expression": "\nVAR _OnTime = [OTD (Lines)]\nVAR _Total = CALCULATE (\n    [Invoice Lines],\n    'Invoice Document Type'[Group] = \"Invoice\"\n)\nRETURN\n\nDIVIDE ( _OnTime, _Total )",
            "formatString": "#,##0.0%",
            "displayFolder": "3. Lines"
          },
          {
            "name": "OTD % (Quantity)",
            "expression": "\nVAR _OnTime = [OTD (Quantity)]\nVAR _Total = \n    CALCULATE (\n        [Total Net Invoice Quantity],\n        'Invoice Document Type'[Group] = \"Invoice\"\n    )\nRETURN\n\nDIVIDE ( _OnTime, _Total )",
            "formatString": "#,##0.0%",
            "displayFolder": "2. Quantity"
          },
          {
            "name": "OTD % (Value)",
            "expression": "\nVAR _OnTime = [OTD (Value)]\nVAR _Total = \n    CALCULATE (\n        [Total Net Invoice Value],\n        'Invoice Document Type'[Group] = \"Invoice\"\n    )\nRETURN\n\nDIVIDE ( _OnTime, _Total )",
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value"
          },
          {
            "name": "OTD (Lines)",
            "expression": "\nCALCULATE (\n    [Invoice Lines],\n    'On-Time Delivery'[OTD Indicator] = TRUE,\n    'Invoice Document Type'[Group] = \"Invoice\"\n)",
            "formatString": "#,##0",
            "displayFolder": "3. Lines"
          },
          {
            "name": "OTD (Quantity)",
            "expression": "\nCALCULATE (\n    [Total Net Invoice Quantity],\n    'On-Time Delivery'[OTD Indicator] = TRUE,\n    'Invoice Document Type'[Group] = \"Invoice\"\n)",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity"
          },
          {
            "name": "OTD (Value)",
            "expression": "\nCALCULATE (\n    [Total Net Invoice Value],\n    'On-Time Delivery'[OTD Indicator] = TRUE,\n    'Invoice Document Type'[Group] = \"Invoice\"\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Value"
          }
        ]
      },
      {
        "name": "Orders",
        "columns": [
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "description": "There is a bug with the \"Order Date\" field where it is blank. This will take me a bit of time to resolve. - Kurt",
            "isHidden": true,
            "sourceColumn": "Order Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns\\3. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "Columns\\3. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Request Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Request Goods Receipt Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Confirm Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Confirm Goods Receipt Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "Columns\\3. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Order Document Line Item Status",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Line Item Status",
            "displayFolder": "Columns\\3. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns\\3. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Order Value",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "Net Order Value",
            "formatString": "\\$#,0.###############;(\\$#,0.###############);\\$#,0.###############",
            "displayFolder": "Columns\\1. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"en-US\"}"
              }
            ]
          },
          {
            "name": "Net Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Order Quantity",
            "displayFolder": "Columns\\1. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(\"te3-training-eu.database.windows.net\",\"SpacePartsCoDW\"),\n    Data = Source{[Schema=\"Factview\",Item=\"Orders\"]}[Data],\n    #\"Select Columns\" = Table.RemoveColumns ( Data, \"DWCreatedDate\" ),\n    #\"Filtered Rows1\" = Table.SelectRows(#\"Select Columns\", each ([Sales Order Document Line Item Status] <> \"Cancelled\" and Number.Mod([Product Key],100) = 0)),\n    #\"Added Custom\" = Table.AddColumn(#\"Filtered Rows1\", \"RandomDays\", each Number.RandomBetween(7, 90), Int64.Type),\n    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"RandomDays\", Int64.Type}, {\"Net Order Value\", Currency.Type}}),\n    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Fixed Order Date\", each if [Order Date] = null then if Date.AddDays([Request Goods Receipt Date], -[RandomDays]) > [Ship Date] then [Ship Date] else Date.AddDays([Request Goods Receipt Date], -[RandomDays]) else [Order Date]),\n    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Fixed Order Date\", type date}}),\n    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"Order Date\", \"RandomDays\"}),\n    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Fixed Order Date\", \"Order Date\"}}),\n    #\"Removed Columns1\" = Table.RemoveColumns(#\"Renamed Columns\",{\"Sales Order Document Number\", \"Sales Order Document Line Item Number\"}),\n    #\"Filtered Rows2\" = Table.SelectRows(#\"Removed Columns1\", each [Order Date] >= #date(2022, 1, 1) and [Order Date] <= #date(2022, 8, 19))\nin\n    #\"Filtered Rows2\""
            }
          }
        ],
        "measures": [
          {
            "name": "Net Orders",
            "description": "Net orders exclude cancellation document types",
            "expression": "\nCALCULATE (\n    [Total Net Order Value],\n    'Order Document Type'[Group]\n        <> \"Cancellation\"\n) ",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total"
          },
          {
            "name": "Net Orders (Quantity)",
            "description": "Net orders exclude cancellation document types",
            "expression": "\nCALCULATE (\n    [Total Net Order Quantity],\n    'Order Document Type'[Group]\n        <> \"Cancellation\"\n) ",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity"
          },
          {
            "name": "Net Orders 1YP",
            "description": "Net orders exclude cancellation document types",
            "expression": "\nCALCULATE ( [Net Orders], DATEADD('Date'[Date], -1, YEAR ))",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\ii. 1YP"
          },
          {
            "name": "Net Orders 2YP",
            "description": "Net orders exclude cancellation document types",
            "expression": "\nCALCULATE ( [Net Orders], DATEADD('Date'[Date], -2, YEAR ))",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\iii. 2YP"
          },
          {
            "name": "Total Net Order Value",
            "description": "The net order value is the sum of all order intake including cancellations (also known as Gross Orders)",
            "expression": "\nVAR _RATE = MAX ('Exchange Rate'[Rate])\nRETURN\n\n    -- Convert to common currency (WAT)\n    SUMX (\n        'Orders',\n        'Orders'[Net Order Value]\n            / RELATED ('Budget Rate'[Rate])\n    )\n\n        -- Convert to selected currency\n        * _RATE ",
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total"
          },
          {
            "name": "Net Order Lines",
            "expression": "\nCOUNTROWS ( 'Orders' )",
            "formatString": "#,##0",
            "displayFolder": "3. Lines"
          },
          {
            "name": "Total Net Order Quantity",
            "expression": "\nSUM ( 'Orders'[Net Order Quantity] )",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "2. Quantity"
          },
          {
            "name": "Order Lines (Yesterday)",
            "description": "Used for Debugger Demo",
            "expression": "CALCULATE (\n    [Net Order Lines],\n\tDATEADD('Date'[Date], -1, DAY)\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures\\DAX Debugger Demo"
          },
          {
            "name": "Daily Avg. Order Lines (Last 4 weeks)",
            "description": "Used for Debugger Demo",
            "expression": "VAR _LatestDate = \n    MAX ( 'Date'[Date] )\n    \nVAR _Last28Days =\n    DATESINPERIOD (\n        'Date'[Date],\n        _LatestDate,\n        -28,\n        DAY\n    )\n\nVAR _NumberDays = \n    COUNTROWS ( _Last28Days )\n\nVAR _TotalLines =\n    CALCULATE ( [Net Order Lines], _Last28Days )\n\nVAR _Result =\n    DIVIDE ( _TotalLines, _NumberDays )\n\nRETURN\n    _Result",
            "formatString": "#,##0",
            "displayFolder": "Measures\\DAX Debugger Demo"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Forecast",
        "columns": [
          {
            "name": "Forecast Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Forecast Month",
            "formatString": "Long Date",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Region Territory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Region Territory",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Type",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Forecast (EUR)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Forecast (EUR)",
            "displayFolder": "1. Facts",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Forecast",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Factview\",Item=\"Forecast\"]}[Data],\n    #\"Select Columns\" = Table.SelectColumns ( Data, {\"Forecast Month\", \"Forecast (EUR)\", \"Region Territory\", \"Product Type\"})\nin\n    #\"Select Columns\""
            }
          }
        ],
        "measures": [
          {
            "name": "Forecast MTD",
            "expression": "\n-- Calculates the target for the current month/year selection\nVAR _CURRENT_MONTH_VALUE =\n    CALCULATE (\n        [Forecast],\n        ALL ( 'Date' ),\n        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )\n    ) \n\n-- Computes rate at which Forecast increases through the month\nVAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        1.035\n    )\n\nVAR _CURRENT_MONTH_PERC_WORKDAYS =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        1.035\n    )\n\nVAR _PERIOD =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\nVAR _HASONEMONTH =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        _HASONEMONTH\n            && _PERIOD = \"Full Period\",\n        _CURRENT_MONTH_PERC_WORKDAYS\n            * _CURRENT_MONTH_VALUE,\n\n        IF (\n            _HASONEMONTH,\n            _CURRENT_MONTH_PERC_WORKDAYS_MTD\n                * _CURRENT_MONTH_VALUE\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Forecast QTD",
            "expression": "\nVAR _DATES_QTD =\n    CALCULATETABLE (\n        DATESQTD ('Date'[Date]),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _CURRENT_MONTH_Forecast = [Forecast MTD]\nVAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_QTD)\nVAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Forecast QTD]\nVAR _DELTA  = [Gross Sales] - [Forecast QTD]\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Forecast QTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD"
          },
          {
            "name": "Forecast YTD",
            "expression": "\nVAR _DATES_YTD =\n    CALCULATETABLE (\n        DATESYTD ('Date'[Date]),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _CURRENT_MONTH_Forecast = [Forecast MTD]\nVAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_YTD)\nVAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Forecast YTD]\nVAR _DELTA  = [Gross Sales] - [Forecast YTD]\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Forecast YTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD"
          },
          {
            "name": "Total Forecast",
            "expression": "\n    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )\nRETURN\n    SUM ( 'Forecast'[Forecast (EUR)] ) * _SelectedRate",
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Forecast",
            "expression": "\nIF.EAGER(\n    HASONEVALUE( '2) Selected Unit'[Select a Unit] )\n        && \n    HASONEVALUE( 'Exchange Rate'[From Currency] ),\n\n    VAR _SELECTED_CURRENCY = \n        SELECTEDVALUE( 'Exchange Rate'[From Currency] )\n\n    VAR _SELECTED_RATE_TYPE = \n        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )\n    \n    VAR _SELECTED_BUDGET_RATE =\n        MAX( 'Exchange Rate'[Rate] )\n        \n    VAR _SELECTED_MONTHLY_RATE =\n        ADDCOLUMNS(\n            SUMMARIZE(\n                'Exchange Rate',\n                'Date'[Calendar Month Year (ie Jan 21)]\n            ),\n            \"Curr\", \n            CALCULATE ( \n                MAX( 'Exchange Rate'[Rate] ) \n            )\n        )\n        \n    RETURN\n\n    IF(\n        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",\n        SUM ( 'Forecast'[Forecast (EUR)]) \n        * \n        _SELECTED_BUDGET_RATE,\n        \n        IF(\n            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",\n            SUMX(\n                _SELECTED_MONTHLY_RATE,\n                CALCULATE( \n                    SUM ( 'Forecast'[Forecast (EUR)])\n                )\n                * [Curr]\n            )\n        )\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Forecast MTD]\nVAR _DELTA  = [MTD Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (Δ)",
            "expression": "\n[MTD Gross Sales] - [Forecast MTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD"
          },
          {
            "name": "Forecast vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Forecast]\nVAR _DELTA  = [Gross Sales] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total"
          },
          {
            "name": "Forecast vs. Gross Sales (Δ)",
            "expression": "\n[Gross Sales] - [Forecast]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Order Document Type",
        "columns": [
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "displayFolder": "1. Order Doc. Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "displayFolder": "1. Order Doc. Type",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Order Document Type",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Order Document Type\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "Order Status",
        "columns": [
          {
            "name": "Order Status Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Order Status Code",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "2. Keys",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Text",
            "dataType": "string",
            "sourceColumn": "Order Status Text",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "1. Order Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Group",
            "dataType": "string",
            "sourceColumn": "Order Status Group",
            "sortByColumn": "Order Status Grouping Ordinal",
            "displayFolder": "1. Order Status",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Grouping Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Grouping Ordinal",
            "displayFolder": "3. Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Order Status",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": "let\n    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),\n    Data = Source{[Schema=\"Dimview\",Item=\"Order Status\"]}[Data]\nin\n    Data"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ]
      },
      {
        "name": "1) Selected Metric",
        "description": "It lets you select a Metric.",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Measure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Measure]",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "1) Selected Metric",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nSELECTCOLUMNS(\n    'Z01CG2 - Value (Budget Rate)',\n        \"Select a Measure\", 'Z01CG2 - Value (Budget Rate)'[Measure],\n        \"Order\", 'Z01CG2 - Value (Budget Rate)'[Ordinal]\n)"
            }
          }
        ]
      },
      {
        "name": "2) Selected Unit",
        "description": "This is a disconnected table for Measure Selection.\nIt lets you select a Unit.",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Unit",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Unit]",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "2) Selected Unit",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nSELECTCOLUMNS(\n    'Z02CG1 - Unit',\n        \"Select a Unit\", 'Z02CG1 - Unit'[Unit],\n        \"Order\", 'Z02CG1 - Unit'[Ordinal]\n) "
            }
          }
        ]
      },
      {
        "name": "3) Selected Target",
        "description": "This is a disconnected table for Measure Selection.\nIt lets you select a Target.",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD Slicer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD Slicer]",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Target",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Target]",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "3) Selected Target",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nSELECTCOLUMNS (\n    'Z03CG1 - Sales Target',\n    \"Select a Target\", 'Z03CG1 - Sales Target'[Target],\n    \"Order\", 'Z03CG1 - Sales Target'[Ordinal],\n    \"MTD Slicer\",\n        VAR _TARGET = 'Z03CG1 - Sales Target'[Target]\n        RETURN\n            SWITCH (\n                TRUE (),\n                _TARGET = \"Budget\",         \"Gross Sales MTD vs. Budget\",\n                _TARGET = \"Forecast\",       \"Gross Sales MTD vs. FCST\",\n                _TARGET = \"1 Year Prior\",   \"Gross Sales MTD vs. 1YP\",\n                _TARGET = \"2 Years Prior\",  \"Gross Sales MTD vs. 2YP\"\n            )\n)"
            }
          }
        ]
      },
      {
        "name": "4) Selected Period",
        "description": "This is a disconnected table for Measure Selection.\nIt lets you select a Period",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "displayFolder": "Columns\\1. Order",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Period",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Period]",
            "sortByColumn": "Order",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "QTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[QTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "4) Selected Period",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nUNION (\n    ROW (\n        \"Period\", {\"Full Period\"},\n        \"Order\", {0},\n        \"MTD\", {\"Full Month\"},\n        \"QTD\", {\"Full Quarter\"},\n        \"YTD\", {\"Full Year\"}\n    ),\n    ROW (\n        \"Period\", {\"Period-to-Date\"},\n        \"Order\", {1},\n        \"MTD\", {\"MTD\"},\n        \"QTD\", {\"QTD\"},\n        \"YTD\", {\"YTD\"}\n    )\n)"
            }
          }
        ]
      },
      {
        "name": "Z01CG1 - Quantity",
        "isHidden": true,
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Orders",
              "expression": "\n[Net Orders (Quantity)]",
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": "\n[Total Net Invoice Quantity]",
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": "\nBLANK()",
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": "\nBLANK()",
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": "\nBLANK()",
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": "\nBLANK()",
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": "\nBLANK()",
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": "\nBLANK()",
              "ordinal": 8
            },
            {
              "name": "Gross Sales",
              "expression": "\n[Total Net Invoice Quantity]",
              "ordinal": 0
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z01CG2 - Value (Budget Rate)",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Invoices",
              "expression": "\n[Total Net Invoice Value]",
              "ordinal": 2
            },
            {
              "name": "Orders",
              "expression": "\n[Net Orders]",
              "ordinal": 1
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": "\n[Total Net Invoice COGS]",
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": "\n[Total Delivery Cost]",
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": "\n[Total Freight Surcharge]",
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": "\n[Total Taxes & Commercial Fees]",
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": "\n[Total Overdue Payment Penalties]",
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": "\n[Total Late Delivery Penalties]",
              "ordinal": 8
            },
            {
              "name": "Gross Sales",
              "expression": "\n[Gross Sales]",
              "ordinal": 0
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z01CG4 - Lines",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 3,
          "calculationItems": [
            {
              "name": "Invoices",
              "expression": "\n[Lines]",
              "ordinal": 3
            },
            {
              "name": "Orders",
              "expression": "\n[Net Orders]",
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": "\nBLANK()",
              "ordinal": 4
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": "\nBLANK()",
              "ordinal": 5
            },
            {
              "name": "Delivery Surcharge",
              "expression": "\nBLANK()",
              "ordinal": 6
            },
            {
              "name": "Taxes",
              "expression": "\nBLANK()",
              "ordinal": 7
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": "\nBLANK()",
              "ordinal": 8
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": "\nBLANK()",
              "ordinal": 9
            },
            {
              "name": "Gross Sales",
              "expression": "\n[Invoice Lines]",
              "ordinal": 0
            },
            {
              "name": "Net Sales",
              "expression": "\nBLANK()",
              "ordinal": 1
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z02CG1 - Unit",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Value (Budget Rate)",
              "expression": "\n[Value]",
              "ordinal": 0
            },
            {
              "name": "Quantity",
              "expression": "\n[Quantity]",
              "ordinal": 1
            },
            {
              "name": "Lines",
              "expression": "\n[Lines]",
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Unit",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z03CG1 - Sales Target",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 6,
          "calculationItems": [
            {
              "name": "Budget",
              "expression": "\n[Total Budget]",
              "ordinal": 0
            },
            {
              "name": "1 Year Prior",
              "expression": "\n[Gross Sales 1YP (Selected Unit)]",
              "ordinal": 2
            },
            {
              "name": "Forecast",
              "expression": "\n[Forecast]",
              "ordinal": 1
            },
            {
              "name": "2 Years Prior",
              "expression": "\n[Gross Sales 2YP (Selected Unit)]",
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z03CG2 - Orders Target",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 7,
          "calculationItems": [
            {
              "name": "1 Year Prior",
              "expression": "\n[Net Orders 1YP]",
              "ordinal": 0
            },
            {
              "name": "2 Years Prior",
              "expression": "\n[Net Orders 2YP]",
              "ordinal": 1
            },
            {
              "name": "Budget",
              "expression": "\nBLANK()",
              "ordinal": 2
            },
            {
              "name": "Forecast",
              "expression": "\nBLANK()",
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z04CG1 - Time Intelligence",
        "isHidden": true,
        "calculationGroup": {
          "precedence": 4,
          "calculationItems": [
            {
              "name": "Daily",
              "expression": "\nSELECTEDMEASURE()",
              "ordinal": 0
            },
            {
              "name": "MTD",
              "expression": "\nCALCULATE (\n    SELECTEDMEASURE (), \n    CALCULATETABLE (\n        DATESMTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
              "ordinal": 1
            },
            {
              "name": "QTD",
              "expression": "\nCALCULATE (\n    SELECTEDMEASURE (), \n    CALCULATETABLE (\n        DATESQTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
              "ordinal": 2
            },
            {
              "name": "YTD",
              "expression": "\nVAR _YTD =\n    CALCULATE (\n        SELECTEDMEASURE (),\n        CALCULATETABLE (\n            DATESYTD ('Date'[Date]),\n            'Date'[IsDateInScope]\n        )\n    )\nVAR _FULL_YTD =\n    CALCULATE (SELECTEDMEASURE (), DATESYTD ('Date'[Date]))\nRETURN\n    IF (\n        SEARCH (\"Actuals\", SELECTEDMEASURENAME (), , 999) <> 999,\n        _YTD,\n        _FULL_YTD\n    )",
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Aggregation",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "__Measures",
        "description": "Everything in this Table Requires Measure Selection\n1. Select a Metric\n2. Select a Unit\n3. Select a Target\n4. Select a Period\n5. Select a Currency (from 'Exchange Rate')\n6. Select a Year and/or Month from 'Date'\n",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "__Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nSELECTCOLUMNS (\n    { 1 },\n    \"__Measures\", ''[Value]\n)"
            }
          }
        ],
        "measures": [
          {
            "name": "Actuals",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT ('2) Selected Unit'[Select a Unit]),\n        'Z02CG1 - Unit'[Unit]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Actuals"
          },
          {
            "name": "Actuals MTD",
            "expression": "\nCALCULATE (\n    [Actuals],\n    CALCULATETABLE (\n        DATESMTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Actuals"
          },
          {
            "name": "Actuals QTD",
            "expression": "\nCALCULATE (\n    [Actuals],\n    CALCULATETABLE (\n        DATESQTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Actuals"
          },
          {
            "name": "Actuals YTD",
            "expression": "\nCALCULATE (\n    [Actuals],\n    CALCULATETABLE (\n        DATESYTD ('Date'[Date]),\n        'Date'[IsDateInScope]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "4. YTD"
          },
          {
            "name": "Lines",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT ('1) Selected Metric'[Select a Measure]),\n        'Z01CG4 - Lines'[Measure]\n    )\n)",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals"
          },
          {
            "name": "Quantity",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT ('1) Selected Metric'[Select a Measure]),\n        'Z01CG1 - Quantity'[Measure])\n)",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (%)",
            "expression": "\nVAR _TARGET = [Sales Target YTD]\nVAR _DELTA  = [Actuals YTD] -  _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "4. YTD"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (Δ)",
            "expression": "\n[Actuals YTD] - [Sales Target YTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "4. YTD"
          },
          {
            "name": "Value",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT ('1) Selected Metric'[Select a Measure]),\n        'Z01CG2 - Value (Budget Rate)'[Measure]\n    )\n) ",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals"
          },
          {
            "name": "Sales Target YTD",
            "expression": "\nVAR YRTD =\n    CALCULATE(\n        [Sales Target],\n        CALCULATETABLE(\n            DATESYTD( 'Date'[Date] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        'Date'[IsBeforeThisMonth] = TRUE\n    ) // Calculates the target for the current month/year selection\nVAR _CurrentMonth_value =\n    CALCULATE( [Sales Target], 'Date'[IsThisMonth] = TRUE ) // Calculates the % workdays MTD together with the dynamic parameter to set the exponential rate of increase MTD\nVAR _currentMonthWorkDay =\n    POWER(\n        CALCULATE(\n            MAX( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE,\n            'Date'[IsThisMonth] = TRUE\n        ),\n        0.93\n    ) // If viewing units, hide the FCST (as there is no units FCST as of July 09, 2020)\nVAR MOTD =\n    IF(\n        _CurrentMonth_value > 0,\n        _currentMonthWorkDay * _CurrentMonth_value,\n        BLANK( )\n    )\n        + YRTD\nVAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )\nVAR _YEAR = MAX( 'Date'[Calendar Year Number (ie 2021)] )\nVAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )\nRETURN\n    IF(\n        _PERIOD = \"Full Period\",\n        CALCULATE(\n            [Sales Target],\n            ALL( 'Date' ),\n            'Date'[Calendar Year Number (ie 2021)] = _YEAR,\n            'Date'[Calendar Year Month (ie 202101)] <= _MONTH\n        ),\n        // If date is in the visual context and YTD is blank, show MTD, otherwise add YTD + MTD together\n        MOTD\n    )",
            "formatString": "#,##0",
            "displayFolder": "4. YTD"
          },
          {
            "name": "Sales Target QTD",
            "expression": "\nVAR _QTD =\n    CALCULATE(\n        [Sales Target],\n        CALCULATETABLE(\n            DATESQTD( 'Date'[Date] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _MTD =\n    CALCULATE( [Sales Target MTD], 'Date'[IsThisMonth] = TRUE )\nVAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )\nVAR _QUARTER = MAX( 'Date'[Calendar Year Quarter (ie 202101)] )\nVAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )\nRETURN\n    IF(\n        _PERIOD = \"Full Period\",\n        CALCULATE(\n            [Sales Target],\n            ALL( 'Date' ),\n            'Date'[Calendar Year Quarter (ie 202101)] = _QUARTER,\n            'Date'[Calendar Year Month (ie 202101)] <= _MONTH\n        ),\n        IF(\n            ISBLANK( _QTD ),\n            _MTD,\n            // If date is in the visual context and QTD is blank, show MTD, otherwise add QTD + MTD together\n            IF( MAX ( 'Date'[Date] ) >= MAX ('Last Refresh'[Last Refresh]), _QTD + _MTD, _QTD )\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Sales Target"
          },
          {
            "name": "Sales Target MTD",
            "expression": "\n-- Calculates the target for the current month/year selection\nVAR _CurrentMonth =\n    CALCULATE (\n        [Sales Target],\n        ALL ( 'Date' ),\n        VALUES (\n            'Date'[Calendar Month Year (ie Jan 21)]\n        )\n    )\n\n-- Computes rate at which Budget increases through the month\nVAR _CurrentMonthWDMTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        1.035\n    )\nVAR CurrentMonthWDTotal =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        1.035\n    )\nVAR _Period =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\nVAR _HasOneMonth =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        _HasOneMonth && _Period = \"Full Period\",\n        CurrentMonthWDTotal\n            * _CurrentMonth,\n        IF (\n            _HasOneMonth,\n            _CurrentMonthWDMTD\n                * _CurrentMonth\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Sales Target"
          },
          {
            "name": "Sales Target",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT (\n            '3) Selected Target'[Select a Target]\n        ),\n        'Z03CG1 - Sales Target'[Target]\n    )\n)",
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Sales Target"
          },
          {
            "name": "Sales Target vs. Actuals (Δ)",
            "expression": "\n[Actuals] - [Sales Target]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Sales Target"
          },
          {
            "name": "Sales Target vs. Actuals (%)",
            "expression": "\nVAR _TARGET = [Sales Target]\nVAR _ACTUAL = [Actuals]\nVAR _DELTA  = _ACTUAL - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\n\nRETURN\n\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Sales Target"
          },
          {
            "name": "Sales Target MTD vs. Actuals (Δ)",
            "expression": "\n[Actuals MTD] - [Sales Target MTD]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "2. MTD\\Sales Target"
          },
          {
            "name": "Sales Target MTD vs. Actuals (%)",
            "expression": "\nVAR _TARGET = [Sales Target MTD]\nVAR _ACTUAL = [Actuals MTD]\nVAR _DELTA  = _ACTUAL - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\n\nRETURN\n\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "2. MTD\\Sales Target"
          },
          {
            "name": "Actuals MTD, Latest Data Point",
            "expression": "\n-- Max workday in scope\nVAR _MAXWD =\n    CALCULATE (\n        MAX ( 'Date'[Workdays MTD] ),\n        'Date'[IsDateInScope],\n        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])\n    )\n\n-- Max date in scope\nVAR _MAXDT =\n    CALCULATE ( MAX ('Date'[Date] ),\n        'Date'[IsDateInScope],\n        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )\nRETURN\n\n    -- If the selected workday = the max workday in scope, return the value\n    -- Otherwise return blank (don't show the marker / value)\n    IF (\n        MAX ('Date'[Workdays MTD]) = _MAXWD\n            || MAX ('Date'[Date]) = _MAXDT,\n        [Actuals MTD]\n    )",
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures"
          },
          {
            "name": "Actuals MTD, Data Label",
            "expression": "\n-- Max workday in scope\nVAR _MAXWD =\n    CALCULATE (\n        MAX ( 'Date'[Workdays MTD] ),\n        'Date'[IsDateInScope],\n        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])\n    )\n\n-- Max date in scope\nVAR _MAXDT =\n    CALCULATE ( MAX ('Date'[Date] ),\n        'Date'[IsDateInScope],\n        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )\nRETURN\n\n    -- If the selected workday = the max workday in scope, return the value\n    -- Otherwise return blank (don't show the marker / value)\n    IF (\n        MAX ('Date'[Workdays MTD]) = _MAXWD\n            || MAX ('Date'[Date]) = _MAXDT,\n        \"#6e8c95\",\n        \"#FFFFFF00\"\n    )",
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures"
          },
          {
            "name": "Blank",
            "expression": "\nBLANK ()",
            "isHidden": true,
            "displayFolder": "9. Technical Measures"
          },
          {
            "name": "Orders Target",
            "expression": "\nCALCULATE (\n    [Blank],\n    TREATAS (\n        DISTINCT ( '3) Selected Target'[Select a Target] ), 'Z03CG2 - Orders Target'[Target] )\n    )",
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Orders Target"
          },
          {
            "name": "Orders Target vs. Net Orders (%)",
            "description": "Net orders exclude cancellation document types",
            "expression": "\nVAR _TARGET = [Orders Target]\nVAR _DELTA  = [Net Orders] - _TARGET\nVAR _PERC   = DIVIDE ( _DELTA, _TARGET )\nRETURN\n_PERC",
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Orders Target"
          },
          {
            "name": "Orders Target vs. Net Orders (Δ)",
            "description": "Net orders exclude cancellation document types",
            "expression": "\n[Net Orders] - [Orders Target]",
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Orders Target"
          },
          {
            "name": "Orders Target MTD",
            "expression": "\n-- Calculates the target for the current month/year selection\nVAR _CurrentMonth =\n    CALCULATE (\n        [Orders Target],\n        ALL ( 'Date' ),\n        VALUES (\n            'Date'[Calendar Month Year (ie Jan 21)]\n        )\n    )\n\n-- Computes rate at which Budget increases through the month\nVAR _CurrentMonthWDMTD =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] ),\n            'Date'[IsDateInScope] = TRUE\n        ),\n        0.93\n    )\nVAR _CurrentMonthWDTotal =\n    POWER (\n        CALCULATE (\n            MAX ( 'Date'[Workdays MTD %] )\n        ),\n        0.93\n    )\nVAR _Period =\n    SELECTEDVALUE (\n        '4) Selected Period'[Period]\n    )\n    \nVAR __HasOneMonth =\n    HASONEVALUE (\n        'Date'[Calendar Month Year (ie Jan 21)]\n    )\nRETURN\n    -- return MTD value if a month is selected\n    IF.EAGER (\n        __HasOneMonth && _Period = \"Full Period\",\n        _CurrentMonthWDTotal\n            * _CurrentMonth,\n        IF (\n            __HasOneMonth,\n            _CurrentMonthWDMTD\n                * _CurrentMonth\n        )\n    )",
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Orders Target"
          },
          {
            "name": "Orders Target QTD",
            "expression": "\nVAR _DATES_QTD =\n    CALCULATETABLE (\n        DATESQTD ('Date'[Date]),\n        'Date'[IsThisMonth] = FALSE\n    )\nVAR _CURRENT_MONTH_Forecast = [Orders Target MTD]\nVAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Orders Target], _DATES_QTD)\nVAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Orders Target"
          },
          {
            "name": "Orders Target YTD",
            "expression": "\nVAR _CURRENT_MONTH_TARGET = [Orders Target MTD]\nVAR _YTD_TARGET_BEFORE_THIS_MONTH =\n    CALCULATE (\n        [Orders Target],\n        CALCULATETABLE (\n            DATESYTD ('Date'[Date]),\n            'Date'[IsThisMonth] = FALSE,\n            'Date'[IsDateInScope] = TRUE\n        )\n    )\nVAR _RESULT = _CURRENT_MONTH_TARGET + _YTD_TARGET_BEFORE_THIS_MONTH\nRETURN\n    _RESULT",
            "formatString": "#,##0",
            "displayFolder": "4. YTD"
          },
          {
            "name": "Gross Sales 2YP (Selected Unit)",
            "expression": "\nCALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -2, YEAR ))",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target"
          },
          {
            "name": "Gross Sales 1YP (Selected Unit)",
            "expression": "\nCALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -1, YEAR ))",
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target"
          }
        ]
      },
      {
        "name": "__Demo Measures",
        "description": "5 measures usable without any selection; quick-start",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "__Demo Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "\nSELECTCOLUMNS (\n    { 1 },\n    \"__Measures\", ''[Value]\n)"
            }
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": "\nCALCULATE (\n    [Gross Sales],\n    'Exchange Rate'[From Currency] = \"EUR\"\n)",
            "formatString": "#,##0"
          },
          {
            "name": "Sales Budget",
            "expression": "\nCALCULATE (\n    [Budget],\n    'Exchange Rate'[From Currency] = \"EUR\"\n)",
            "formatString": "#,##0"
          },
          {
            "name": "Sales Forecast",
            "expression": "\nCALCULATE (\n    [Forecast],\n    'Exchange Rate'[From Currency] = \"EUR\"\n)",
            "formatString": "#,##0"
          },
          {
            "name": "Billing Document Lines",
            "expression": "\n[Invoice Lines]",
            "formatString": "#,##0"
          },
          {
            "name": "# Accounts",
            "expression": "\n[# Customers]",
            "formatString": "#,##0"
          }
        ]
      },
      {
        "name": "Last Refresh",
        "columns": [
          {
            "name": "Last Refresh",
            "dataType": "dateTime",
            "sourceColumn": "Last Refresh",
            "formatString": "General Date",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Last Refresh-01ea78bc-dff4-4eac-b58e-527fab59801b",
            "mode": "import",
            "queryGroup": "Scalar Values",
            "source": {
              "type": "m",
              "expression": "let\n    Source = DateTimeZone.FixedLocalNow()\nin\n    Source"
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTimeZone"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "0e6e4252-95c4-4e0e-a4c8-874e5463ec4c",
        "fromTable": "Invoices",
        "fromColumn": "Billing Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "7dacb5b5-3b77-45fe-85f9-cdebc76b1d56",
        "fromTable": "Invoices",
        "fromColumn": "Billing Document Type Code",
        "toTable": "Invoice Document Type",
        "toColumn": "Billing Document Type Code"
      },
      {
        "name": "a9b264e6-c155-4643-adc9-e01ad2b308ea",
        "fromTable": "Invoices",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "2fe91495-a480-42d8-bcf5-63ce2f84e4d0",
        "fromTable": "Invoices",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "03e537eb-3ddb-4c20-b5ad-9090c0aadd0d",
        "fromTable": "Customers",
        "fromColumn": "Station",
        "toTable": "Regions",
        "toColumn": "Station"
      },
      {
        "name": "aee91ed3-e637-4150-a8d4-22619ecc0034",
        "fromTable": "Products",
        "fromColumn": "Sub Brand Name",
        "toTable": "Brands",
        "toColumn": "Sub Brand"
      },
      {
        "name": "bbcee627-b8b2-4604-9ad8-9d2036321cfb",
        "fromTable": "Budget",
        "fromColumn": "Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "583c271a-a6ae-4f4b-bdb0-dfc91a31493e",
        "fromTable": "Budget",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "b9c4b659-0116-4f12-af8c-704fe07f3112",
        "fromTable": "Budget",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "4a26dc2c-f944-4c6e-9670-5e66e566c970",
        "fromTable": "Exchange Rate",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "7a4bdc99-ebb9-4dc1-92bd-c20e0460b638",
        "fromTable": "Invoices",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "4eade231-e4d9-4b9f-8568-0f8dd9162e6f",
        "fromTable": "Invoices",
        "fromColumn": "OTD Indicator",
        "toTable": "On-Time Delivery",
        "toColumn": "OTD Indicator"
      },
      {
        "name": "1ae64f29-da13-4294-bde5-4320a84af2c1",
        "fromTable": "Orders",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "34c786fb-4d8e-41d3-a86c-fd83e71d8cc1",
        "fromTable": "Orders",
        "fromColumn": "Request Goods Receipt Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6ef67eab-1e07-436d-a358-6197853f0064",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Line Item Status",
        "toTable": "Order Status",
        "toColumn": "Order Status Code"
      },
      {
        "name": "5c8f76eb-7c06-4ed5-bdc2-6368b1f0ef0a",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Type Code",
        "toTable": "Order Document Type",
        "toColumn": "Sales Order Document Type Code"
      },
      {
        "name": "7664202a-acbb-4942-a83e-60eb3b8537f9",
        "fromTable": "Orders",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "c97e9cf2-9441-4f5a-8609-f53e6a3a7571",
        "fromTable": "Orders",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "3795aac2-e6ba-48a7-9722-b7dd7af7b762",
        "fromTable": "Forecast",
        "fromColumn": "Forecast Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "599b10ac-8bcb-4550-b452-56d8954b2a35",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Product Type",
        "toTable": "Products",
        "toColumn": "Type"
      },
      {
        "name": "703b86a0-df9c-47d6-82e4-7c457de95971",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Region Territory",
        "toTable": "Regions",
        "toColumn": "Territory"
      },
      {
        "name": "d3b21caa-eed5-4a2b-85a1-92a599807a8a",
        "fromTable": "Orders",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "perspectives": [
      {
        "name": "No Measure Selection",
        "tables": [
          {
            "name": "Orders",
            "measures": [
              {
                "name": "Total Net Order Quantity"
              },
              {
                "name": "Net Order Lines"
              },
              {
                "name": "Net Orders (Quantity)"
              },
              {
                "name": "Total Net Order Value"
              },
              {
                "name": "Net Orders"
              },
              {
                "name": "Net Orders 1YP"
              },
              {
                "name": "Net Orders 2YP"
              }
            ]
          },
          {
            "name": "Order Status",
            "columns": [
              {
                "name": "Order Status Group"
              },
              {
                "name": "Order Status Text"
              }
            ]
          },
          {
            "name": "Order Document Type",
            "columns": [
              {
                "name": "Text"
              },
              {
                "name": "Group"
              }
            ]
          },
          {
            "name": "On-Time Delivery",
            "measures": [
              {
                "name": "OTD % (Lines)"
              },
              {
                "name": "OTD (Lines)"
              },
              {
                "name": "OTD (Quantity)"
              },
              {
                "name": "OTD % (Quantity)"
              },
              {
                "name": "OTD (Value)"
              },
              {
                "name": "OTD % (Value)"
              }
            ]
          }
        ]
      },
      {
        "name": "Measure Selection"
      }
    ],
    "roles": [
      {
        "name": "Territory Managers",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Regions",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Regions'[Territory Directors] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "6d4eacc1cfdf475eb3dac207196ec47f"
          }
        ]
      },
      {
        "name": "Account Managers",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Customers",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Customers'[Account Manager] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "dbdfbff19eea4f0d84010925e3c7f23e"
          }
        ]
      },
      {
        "name": "Brand VPs",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Brands",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Brands'[Product Brand VP] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "0b8d41815400413293ab3942e184b53e"
          }
        ]
      },
      {
        "name": "Business Line Leaders",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Products",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Products'[Product Business Line Leader] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "b975518cd80041dabbaf5d904a66b92f"
          }
        ]
      },
      {
        "name": "Station Sales Managers",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Regions",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Regions'[Station Sales Managers] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "fa0b2f174d25400296ad332b392a1c57"
          }
        ]
      },
      {
        "name": "System Regional Managers",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Regions",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Regions'[System Regional Managers] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "eaa78ebe59c245ccab75056fa76172e9"
          }
        ]
      },
      {
        "name": "System Sales Directors",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Regions",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Regions'[System Sales Directors] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "e1130bdac9114fbabf57e2875f59743b"
          }
        ]
      },
      {
        "name": "Key Account Managers",
        "modelPermission": "read",
        "tablePermissions": [
          {
            "name": "Customers",
            "filterExpression": "\nVAR _CurrentUser =\n    SELECTCOLUMNS (\n        FILTER (\n            'Employees',\n            'Employees'[Employee Email]\n                = USERPRINCIPALNAME ( )\n        ),\n        \"@Name\", 'Employees'[Employee Name]\n    )\nRETURN\n    'Customers'[Key Account Manager] IN _CurrentUser"
          }
        ],
        "annotations": [
          {
            "name": "PBI_Id",
            "value": "74b5a908a58f4954b252fd5d2c9cb895"
          }
        ]
      }
    ],
    "expressions": [
      {
        "name": "SqlEndpoint",
        "kind": "m",
        "expression": "\"te3-training-eu.database.windows.net\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "Database",
        "kind": "m",
        "expression": "\"SpacePartsCoDW\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "RangeStart",
        "kind": "m",
        "expression": "#datetime(2022, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ]
      },
      {
        "name": "RangeEnd",
        "kind": "m",
        "expression": "#datetime(2022, 8, 19, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Parameters",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Scalar Values",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      }
    ],
    "functions": [
      {
        "name": "Comparison.RelativeToTarget",
        "expression": "//Compare to a target and return the relative percent\n//Example usage: Comparing Sales to budget or forecast to get relative performance\n//Examples:\n// - 9/10 is -10%\n// - 11/10 is +10%\n(\n    // The actual value\n    actual: SCALAR NUMERIC VAL,\n \n    // The target that you are comparing to\n    target: SCALAR NUMERIC VAL\n) =>\nVAR _target = target\nVAR _actual = actual\nVAR _delta  = _actual - _target\nVAR _percent  = DIVIDE ( _delta, _target )\n\nRETURN\n    _percent\n"
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":false,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"],\"IgnoreLineageTags\":true,\"IgnorePrivacySettings\":true,\"IgnoreIncrementalRefreshPartitions\":true}"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "0"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Brands\",\"Budget Rate\",\"Customers\",\"Employees\",\"Exchange Rate\",\"Invoice Document Type\",\"Products\",\"Regions\",\"Budget\",\"Invoices\",\"Orders\",\"Forecast\",\"Order Document Type\",\"Order Status\",\"SqlEndpoint\",\"Database\",\"RangeStart\",\"RangeEnd\",\"Last Refresh\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "BestPracticeAnalyzer_IgnoreRules",
        "value": "{\"RuleIDs\":[]}"
      }
    ]
  }
}