{
  "name": "SpaceParts_PBIG2026",
  "compatibilityLevel": 1600,
  "model": {
    "culture": "en-US",
    "discourageImplicitMeasures": true,
    "dataSources": [
      {
        "name": "SpacePartsCoDW",
        "connectionString": "data source=te3-training-eu.database.windows.net;initial catalog=SpacePartsCoDW;persist security info=True;user id=dwreader",
        "impersonationMode": "impersonateServiceAccount",
        "provider": "System.Data.SqlClient",
        "annotations": [
          {
            "name": "ConnectionEditUISource",
            "value": "SqlServer"
          }
        ]
      }
    ],
    "tables": [
      {
        "name": "Brands",
        "lineageTag": "a0525593-73c7-47be-9ed9-a2183e093104",
        "columns": [
          {
            "name": "Flagship",
            "dataType": "string",
            "sourceColumn": "Flagship",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "b65b6e3e-7dce-43ed-9314-433211d70d90",
            "summarizeBy": "none"
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "Class",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "6179bb92-8f2b-42c5-9985-4dcba5a50c19",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "2. Brand Attributes",
            "lineageTag": "58cbe9d6-4965-4239-ad69-32f1368a4a82",
            "summarizeBy": "none"
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "Brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "c84d2a1a-eab1-4093-a9ff-c83ffcc85a35",
            "summarizeBy": "none"
          },
          {
            "name": "Sub Brand",
            "dataType": "string",
            "sourceColumn": "Sub Brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "0afccf44-bcfd-493c-aaf4-408b56321d50",
            "summarizeBy": "none"
          },
          {
            "name": "Product Brand VP",
            "dataType": "string",
            "sourceColumn": "Product Brand VP",
            "displayFolder": "3. Managers",
            "lineageTag": "b5b39f56-c9f9-454c-8ec6-c1c912158f1a",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Brands",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Brands]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Brand Hierarchy",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "61502953-3a7c-4a49-9860-481ee3e96d59",
            "levels": [
              {
                "name": "Class",
                "ordinal": 0,
                "column": "Class",
                "lineageTag": "4d2715aa-b5d8-4ef5-94aa-87b6b2d19530"
              },
              {
                "name": "Flagship",
                "ordinal": 1,
                "column": "Flagship",
                "lineageTag": "5162653f-2f1e-4973-b4e7-3bc146bfdd4b"
              },
              {
                "name": "Brand",
                "ordinal": 2,
                "column": "Brand",
                "lineageTag": "b7e6795e-211b-4126-bc7c-ff440b2d4894"
              },
              {
                "name": "Sub Brand",
                "ordinal": 3,
                "column": "Sub Brand",
                "lineageTag": "3a5f2066-a5a3-474a-9cd0-72d233ba663c"
              }
            ]
          }
        ]
      },
      {
        "name": "Budget Rate",
        "isHidden": true,
        "lineageTag": "078da553-289e-4e12-be96-7f47a2414e28",
        "columns": [
          {
            "name": "Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "1. Facts",
            "lineageTag": "62ac5913-0b86-44b9-9603-859eb92e2616",
            "summarizeBy": "none"
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "From Currency",
            "displayFolder": "2. Keys",
            "lineageTag": "aeae9a6c-0ad9-4175-817f-2b3df56f4ef8",
            "summarizeBy": "none"
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "c7977ea3-3cbc-4f84-a3f0-744cf7dc7bb1",
            "summarizeBy": "none"
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "ed00cddc-f22d-4a4f-9769-e3120a0c7607",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Budget Rate",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Budget Rate]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularProcessingBatch_Budget",
            "value": "1"
          }
        ]
      },
      {
        "name": "Customers",
        "lineageTag": "e18b3987-9b92-4a16-9598-8690e470beb9",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "4. Keys",
            "lineageTag": "ebd42b5b-8a45-4d30-afbd-7b3f445c5ff4",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Sold-To Name",
            "dataType": "string",
            "sourceColumn": "Customer Sold-To Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "05481fb5-372d-4c27-826f-4e15ef227a73",
            "summarizeBy": "none"
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "dcac407a-2eda-49c0-85c5-b48f7f956ee8",
            "summarizeBy": "none"
          },
          {
            "name": "Key Account Name",
            "dataType": "string",
            "sourceColumn": "Key Account Name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "08be59c7-f6bb-4340-ba22-7390793441a6",
            "summarizeBy": "none"
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "Transaction Type",
            "displayFolder": "2. Other Customer Attributes",
            "lineageTag": "be590c6c-8dc3-42f7-a1b1-933584330cd2",
            "summarizeBy": "none"
          },
          {
            "name": "Account Type",
            "dataType": "string",
            "sourceColumn": "Account Type",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "11e66622-29b2-4a2e-90d7-e9e152c50375",
            "summarizeBy": "none"
          },
          {
            "name": "Station",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Station",
            "displayFolder": "4. Keys",
            "lineageTag": "2ad83035-1a13-492e-bdad-6ec234f2cca1",
            "summarizeBy": "none"
          },
          {
            "name": "Account Manager",
            "dataType": "string",
            "sourceColumn": "Account Manager",
            "displayFolder": "3. Managers",
            "lineageTag": "ca7a05c9-a568-457c-9f44-078d2b82ee84",
            "summarizeBy": "none"
          },
          {
            "name": "Key Account Manager",
            "dataType": "string",
            "sourceColumn": "Key Account Manager",
            "displayFolder": "3. Managers",
            "lineageTag": "87b9ba0a-3512-4db8-b24c-307b8a82b114",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Customers]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "# Customers",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "3ce1875b-6408-4c6a-a46f-94ef47bbc7d1"
          },
          {
            "name": "# Key Accounts",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Key Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "dda87f6a-de3b-4f21-9eaa-7148bb084462"
          },
          {
            "name": "Customer Label",
            "expression": [
              "SELECTEDVALUE (",
              "    Customers[Account Name],",
              "    \"All customers\"",
              ")"
            ],
            "lineageTag": "57e677f7-3cc6-4a8c-b9c4-925afe40e3bd"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "5a971dae-bfea-4d58-ba65-d3370f1a820d",
            "levels": [
              {
                "name": "Account Type",
                "ordinal": 0,
                "column": "Account Type",
                "lineageTag": "5ff387e0-67c8-4db1-b878-9bbcb280d1ab"
              },
              {
                "name": "Key Account Name",
                "ordinal": 1,
                "column": "Key Account Name",
                "lineageTag": "609f18c7-51a8-4f5e-95f9-e20df4d209e8"
              },
              {
                "name": "Account Name",
                "ordinal": 2,
                "column": "Account Name",
                "lineageTag": "108a0ddb-f7f1-44e0-8b88-a135dbd8b76a"
              },
              {
                "name": "Customer Sold-To Name",
                "ordinal": 3,
                "column": "Customer Sold-To Name",
                "lineageTag": "5b383e1e-9f1e-4fcb-946e-b82afec627ab"
              }
            ]
          }
        ]
      },
      {
        "name": "Employees",
        "isHidden": true,
        "lineageTag": "ad9a727a-b472-45eb-9eb7-45ef057f383f",
        "columns": [
          {
            "name": "Role",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Role",
            "displayFolder": "Columns",
            "lineageTag": "94c63c36-2568-486e-8696-b32ffe9ab417",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Name",
            "displayFolder": "Columns",
            "lineageTag": "0858e45f-87b4-40eb-b874-0dc268924add",
            "summarizeBy": "none"
          },
          {
            "name": "Employee Email",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Employee Email",
            "displayFolder": "Columns",
            "lineageTag": "8cf2ecaf-582c-445e-80ad-7eeca65997f7",
            "summarizeBy": "none"
          },
          {
            "name": "Data Security Rule",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Data Security Rule",
            "displayFolder": "Columns",
            "lineageTag": "749f0f09-0de1-4145-9027-b520d4ae06ce",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Employees",
            "mode": "import",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Employees]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Exchange Rate",
        "lineageTag": "8c239dee-49d7-432a-ac81-29706f9c3505",
        "columns": [
          {
            "name": "Rate Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Rate Type",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "f409c4cd-c7b9-4a1c-9f41-38a7c3b3b5e5",
            "summarizeBy": "none"
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "sourceColumn": "From Currency",
            "displayFolder": "1. Select a Currency",
            "lineageTag": "9e000f37-9bff-4801-a003-fa594f1b9696",
            "summarizeBy": "none"
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "To Currency",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "2b4e8df9-d0f4-4fa1-92d9-426c534dca0a",
            "summarizeBy": "none"
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Currency System",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "7bcdfbbf-1fff-4f38-9491-deb4b21e6bba",
            "summarizeBy": "none"
          },
          {
            "name": "Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Rate",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "55a899c1-06b2-481a-a0e2-5fd9f8760c76",
            "summarizeBy": "sum"
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Date",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "78927664-f26a-43d5-a325-d252713e3d78",
            "summarizeBy": "none"
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Month",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "7252e8e1-9477-4512-92b1-be0e32fe9782",
            "summarizeBy": "none"
          },
          {
            "name": "Exchange Rate Composite Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Exchange Rate Composite Key",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "3e7c4e89-d24a-45ae-a2a9-244badbbdf14",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Exchange Rate",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Exchange Rate]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Invoice Document Type",
        "lineageTag": "705e8d89-8082-4a53-bdb8-6c15ce5e6309",
        "columns": [
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "sourceColumn": "Billing Document Type Code",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "eea86826-f3b3-4e89-803d-99ec7c7c47cb",
            "summarizeBy": "none"
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "083b5a55-9fa2-4b51-97b6-e483bcfa31fc",
            "summarizeBy": "none"
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "2b0ed245-4614-4428-a988-e9f9af5ed45b",
            "summarizeBy": "sum"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "sortByColumn": "Group Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "2cf99054-fb2a-4053-89fe-87d690634037",
            "summarizeBy": "none"
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "c30c96f9-a9f9-431d-bf7c-0e93e532263a",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Invoice Document Type",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Invoice Document Type]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Products",
        "lineageTag": "bd51825c-1ec6-4891-a44f-3bfec6f788aa",
        "columns": [
          {
            "name": "Sub Brand Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sub Brand Name",
            "displayFolder": "5. Keys",
            "lineageTag": "ef343926-134a-42af-b938-684f7fc4959a",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Class for Part",
            "dataType": "string",
            "sourceColumn": "Ship Class for Part",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "c7678e17-82d0-47ce-97d8-e419ab0ebfa0",
            "summarizeBy": "none"
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "Product Name",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "d2893dee-bb40-4e7f-ab11-7117a566937e",
            "summarizeBy": "none"
          },
          {
            "name": "Part Fit Grading",
            "dataType": "string",
            "sourceColumn": "Part Fit Grading",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "98c5466b-0bb7-48c1-b723-68340005fbb3",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "5. Keys",
            "lineageTag": "4fd7da35-d667-4b2d-a604-92a00f20e0f1",
            "summarizeBy": "none"
          },
          {
            "name": "Subtype",
            "dataType": "string",
            "sourceColumn": "Subtype",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "d1e591c7-26ab-40f4-b687-9b176cddb21d",
            "summarizeBy": "none"
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "Type",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "57cd0f5d-0ecf-4025-a116-1b412584eecd",
            "summarizeBy": "none"
          },
          {
            "name": "MK",
            "dataType": "string",
            "sourceColumn": "MK",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "b3e0b1b0-69b8-45bb-a36c-8441a58aee88",
            "summarizeBy": "none"
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "Color",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "889d8538-0d6c-48d9-908e-d8e1688c69bf",
            "summarizeBy": "none"
          },
          {
            "name": "Production Series",
            "dataType": "string",
            "sourceColumn": "Production Series",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "bf2d4460-3a50-46bd-a8a8-84bd194cbae0",
            "summarizeBy": "none"
          },
          {
            "name": "Nameplate",
            "dataType": "string",
            "sourceColumn": "Nameplate",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "846a5be0-8e26-4f9d-98da-8f1013d67e07",
            "summarizeBy": "none"
          },
          {
            "name": "Material",
            "dataType": "string",
            "sourceColumn": "Material",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "c5b91576-d4db-4a14-98a2-ca4cf6e0533f",
            "summarizeBy": "none"
          },
          {
            "name": "Maximum Temperature (K)",
            "dataType": "int64",
            "sourceColumn": "Maximum Temperature (K)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "3b2cacd1-9c4e-4e1d-9064-1e6498d5b150",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Business Line Leader",
            "dataType": "string",
            "sourceColumn": "Product Business Line Leader",
            "displayFolder": "3. Product Managers",
            "lineageTag": "e9c402f6-0661-4093-9bb9-24ef0af243d3",
            "summarizeBy": "none"
          },
          {
            "name": "Tolerance (g)",
            "dataType": "int64",
            "sourceColumn": "Tolerance (g)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "91eb4e55-44c0-4a04-b44a-7fb146459855",
            "summarizeBy": "sum"
          },
          {
            "name": "Velocity Tolerance (Meters / Second)",
            "dataType": "int64",
            "sourceColumn": "Velocity Tolerance (Meters / Second)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "de65d08e-ad4a-47f8-9c9c-2cd688a4b4a4",
            "summarizeBy": "sum"
          },
          {
            "name": "Weight (Tonnes)",
            "dataType": "double",
            "sourceColumn": "Weight (Tonnes)",
            "displayFolder": "4. Product Facts",
            "lineageTag": "88f2b684-08c3-41ab-86bf-f2a03072b2f6",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Products]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "# Products",
            "expression": [
              "",
              "COUNTROWS ( ",
              "    VALUES ( 'Products'[Product Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "6662876f-e42c-4eaf-a7c4-4c5b3b898716"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "a38f5b59-6c2d-4593-bbd4-aa4e6d1f8c84",
            "levels": [
              {
                "name": "Type",
                "ordinal": 0,
                "column": "Type",
                "lineageTag": "2df8339d-619c-4d48-808f-b9065e14aeab"
              },
              {
                "name": "Subtype",
                "ordinal": 1,
                "column": "Subtype",
                "lineageTag": "acacd6cc-3983-43c9-b450-9dc8d9f87a15"
              },
              {
                "name": "Product Name",
                "ordinal": 2,
                "column": "Product Name",
                "lineageTag": "8f661c7c-151a-4fdc-8501-203a201d0965"
              },
              {
                "name": "Material",
                "ordinal": 3,
                "column": "Material",
                "lineageTag": "b22e4c20-6cd5-4835-a4f3-21b30285385e"
              }
            ]
          }
        ]
      },
      {
        "name": "Regions",
        "lineageTag": "3dbb1d9f-0eb0-437e-a692-e1ac94a33d42",
        "columns": [
          {
            "name": "System",
            "dataType": "string",
            "sourceColumn": "System",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "c623a134-36d7-4612-aff3-2ff3cd91af06",
            "summarizeBy": "none"
          },
          {
            "name": "Interplanetary Region",
            "dataType": "string",
            "sourceColumn": "Interplanetary Region",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "926b0590-2161-4fe7-b8ec-be9620a25595",
            "summarizeBy": "none"
          },
          {
            "name": "Territory",
            "dataType": "string",
            "sourceColumn": "Territory",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "907c2687-e807-43ec-a8eb-5d6cd51b891f",
            "summarizeBy": "none"
          },
          {
            "name": "Station",
            "dataType": "string",
            "sourceColumn": "Station",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "bd1c9c97-5c7d-4b85-8ed5-99503b3e8e4e",
            "summarizeBy": "none"
          },
          {
            "name": "Station Type",
            "dataType": "string",
            "sourceColumn": "Station Type",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "b99d6e89-eb7a-444c-af67-9919d938403e",
            "summarizeBy": "none"
          },
          {
            "name": "Territory Directors",
            "dataType": "string",
            "sourceColumn": "Territory Directors",
            "displayFolder": "3. Managers",
            "lineageTag": "9dff432c-b34d-43d7-a7cd-ae674c85b4cd",
            "summarizeBy": "none"
          },
          {
            "name": "All",
            "dataType": "string",
            "sourceColumn": "All",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "9b8c5122-2b52-4c23-a7ca-82d3f48d1e2f",
            "summarizeBy": "none"
          },
          {
            "name": "Station Sales Managers",
            "dataType": "string",
            "sourceColumn": "Station Sales Managers",
            "displayFolder": "3. Managers",
            "lineageTag": "7a274aab-9276-4b7c-8f89-09b18ed93e2c",
            "summarizeBy": "none"
          },
          {
            "name": "System Regional Managers",
            "dataType": "string",
            "sourceColumn": "System Regional Managers",
            "displayFolder": "3. Managers",
            "lineageTag": "adeb8350-35db-4a58-8dc9-09cbe565ee8f",
            "summarizeBy": "none"
          },
          {
            "name": "System Sales Directors",
            "dataType": "string",
            "sourceColumn": "System Sales Directors",
            "displayFolder": "3. Managers",
            "lineageTag": "cabeca23-dd42-4e6a-80db-ad077cd4c1e6",
            "summarizeBy": "none"
          },
          {
            "name": "Tax Rate",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Tax Rate",
            "formatString": "#,##0.000",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "cc054ff6-847e-44c8-a61b-0490b2e0b777",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Regions",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Regions]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Regional Hierarchy",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "d8c2c7d8-9c53-48be-83f4-bc774269d1f0",
            "levels": [
              {
                "name": "All",
                "ordinal": 0,
                "column": "All",
                "lineageTag": "7f023c7f-ff05-4b30-bd85-5145f3410b32"
              },
              {
                "name": "System",
                "ordinal": 1,
                "column": "System",
                "lineageTag": "5e9c27e8-997b-481c-89c8-692f545b294d"
              },
              {
                "name": "Interplanetary Region",
                "ordinal": 2,
                "column": "Interplanetary Region",
                "lineageTag": "f3f2b44d-e458-45e8-b116-f97cbaad139e"
              },
              {
                "name": "Territory",
                "ordinal": 3,
                "column": "Territory",
                "lineageTag": "5d5dbd46-4b8c-46f5-8c8e-dfa76475e517"
              },
              {
                "name": "Station",
                "ordinal": 4,
                "column": "Station",
                "lineageTag": "99b8eb4d-8258-4aa8-a57b-257a2269ec11"
              }
            ]
          }
        ]
      },
      {
        "name": "Budget",
        "lineageTag": "b64e3e5a-db8f-4549-a386-aca65b9b64e7",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Month",
            "formatString": "Long Date",
            "displayFolder": "1. Keys",
            "lineageTag": "3caf80d1-1bcc-4cdc-b6fd-eace1395db3b",
            "summarizeBy": "none"
          },
          {
            "name": "Budget (EUR)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Total Budget",
            "displayFolder": "2. Facts",
            "lineageTag": "92d0b9a1-7c0c-4119-a1bb-4bce0f74683e",
            "summarizeBy": "sum"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "1. Keys",
            "lineageTag": "81885401-68c8-4b5e-abf0-a7c26b787815",
            "summarizeBy": "none"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "1. Keys",
            "lineageTag": "bb6b5991-f1e5-4826-9b94-3c76425f95b4",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Budget",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Factview].[Budget]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "2022 Budget Achievement %",
            "expression": [
              "",
              "VAR _Sales =",
              "    CALCULATE (",
              "        [Gross Sales],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Budget =",
              "    CALCULATE (",
              "        [Total Budget],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Delta = _Sales - _Budget",
              "VAR _Perc = DIVIDE ( _Delta, _Budget )",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "fbc166ce-60ce-4cad-9996-37965c085cd1"
          },
          {
            "name": "Budget MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Budget],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "c451cb33-be27-40a3-a51a-ade57b4e21f6"
          },
          {
            "name": "Budget MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "6e15506f-dbfc-4b77-bede-fe123c86a19c"
          },
          {
            "name": "Budget MTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [Budget MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "8fcd3f9d-9513-420a-baff-3a130e4f5c7e"
          },
          {
            "name": "Budget QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_BUDGET_BEFORE_THIS_MONTH = CALCULATE ([Budget], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Budget + QTD_BUDGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "07b11bb9-eaaf-45e1-8e1f-b55c3185667a"
          },
          {
            "name": "Budget QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget QTD]",
              "VAR _DELTA  = [Gross Sales] - [Budget QTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "d62e2789-2fcb-4fb1-8a8e-3a5d4a097dfc"
          },
          {
            "name": "Budget QTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget QTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "9e1bd5eb-ddec-4c48-93c6-fbf8cb17f799"
          },
          {
            "name": "Budget YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ( 'Date'[Date] ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_Budget_BEFORE_THIS_MONTH =",
              "    CALCULATE ( [Budget], _DATES_YTD )",
              "VAR _RESULT =",
              "    _CURRENT_MONTH_Budget",
              "        + QTD_Budget_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "959f7930-6074-4e20-9f40-7599839f1288"
          },
          {
            "name": "Budget YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget YTD]",
              "VAR _DELTA  = [Gross Sales] - [Budget YTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "98a925d8-1648-4994-b243-9efa68dc7a58"
          },
          {
            "name": "Budget YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "c44740fd-fbd2-407c-b415-3b03988f4956"
          },
          {
            "name": "Total Budget",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Budget'[Budget (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "e7e24e69-df65-484a-8977-f8876ab1fcb6"
          },
          {
            "name": "Budget",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[From Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[From Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Budget'[Budget (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Budget'[Budget (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "a131b825-ce4d-47f1-ab0c-17bfa4a7b7fb"
          },
          {
            "name": "Budget vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget]",
              "VAR _DELTA  = [Gross Sales] - [Budget]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "efc59f0f-9a58-46f2-ba52-9c5a236b761e"
          },
          {
            "name": "Budget vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Budget]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "a8ec6389-79f3-433f-97c8-e83c78a00a71"
          }
        ],
        "annotations": [
          {
            "name": "TabularProcessingBatch_Budget",
            "value": "1"
          }
        ]
      },
      {
        "name": "Orders",
        "lineageTag": "dfc0956e-a3aa-458e-b6b1-60ae2606edb6",
        "columns": [
          {
            "name": "Sales Order Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "3945c229-5173-460c-b656-aab7a677d3ec",
            "summarizeBy": "sum"
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Order Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "4e6935ca-d6ec-4c08-9838-de0c2cf8f4fa",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "a3194ca6-f633-4faa-bed4-15cd181150a0",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Line Item Number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "2a7791e0-0a9e-4f19-a90d-e08aa3b9d3aa",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "246d50a6-24c1-44db-a027-604f3d2bb5e8",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "5cfef2ac-2162-4e47-9388-c5892e57e4b0",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "4f2b23a1-9def-49ea-8507-de16d7859c64",
            "summarizeBy": "none"
          },
          {
            "name": "Request Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Request Goods Receipt Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "ab41acca-6880-48ba-944b-cea531983d6c",
            "summarizeBy": "none"
          },
          {
            "name": "Confirm Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Confirm Goods Receipt Date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "615e22dd-89ca-45aa-95cf-1113df3c50df",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "9d3e7347-2a47-4d09-91f5-b9b1f037c527",
            "summarizeBy": "none"
          },
          {
            "name": "Sales Order Document Line Item Status",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Line Item Status",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "10ecf093-cb75-4466-9bc4-60b807c415a2",
            "summarizeBy": "none"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "474c78c8-977b-40fd-b049-67ea3ba25b9f",
            "summarizeBy": "none"
          },
          {
            "name": "Net Order Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Order Value",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "74532531-64e8-45f9-9baa-b8e9d4dab654",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Order Quantity",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "f0a9eec5-8e84-4ac9-9dc3-4782f22418a7",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Orders",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Factview].[Orders]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "Net Orders",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Value],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "226dacc8-7651-47c9-9b99-fc5e70821b98"
          },
          {
            "name": "Net Orders (Quantity)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Quantity],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "3d009cb5-7421-4465-9a9f-7fc1380724cf"
          },
          {
            "name": "Net Orders 1YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\ii. 1YP",
            "lineageTag": "c80efb51-8386-4ad7-ac1e-b97b40f32565"
          },
          {
            "name": "Net Orders 2YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\iii. 2YP",
            "lineageTag": "70c3973e-02cb-439c-a94f-90a47b804527"
          },
          {
            "name": "Total Net Order Value",
            "description": "The net order value is the sum of all order intake including cancellations (also known as Gross Orders)",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "",
              "    -- Convert to common currency (WAT)",
              "    SUMX (",
              "        'Orders',",
              "        'Orders'[Net Order Value]",
              "            / RELATED ('Budget Rate'[Rate])",
              "    )",
              "",
              "        -- Convert to selected currency",
              "        * _RATE "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "9ee7fec0-c8f0-4d20-a21e-551524c19581"
          },
          {
            "name": "Order Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Orders' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "79417c7b-e6d3-4cc6-b9a0-a942852749e6"
          },
          {
            "name": "Total Net Order Quantity",
            "expression": [
              "",
              "SUM ( 'Orders'[Net Order Quantity] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "2. Quantity",
            "lineageTag": "c60cdaed-a1e2-4d62-93d9-1c68c68e7a0e"
          }
        ]
      },
      {
        "name": "Forecast",
        "lineageTag": "0138474f-c40c-4541-a7da-2fc78594f8a8",
        "columns": [
          {
            "name": "Forecast Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Forecast Month",
            "formatString": "Long Date",
            "displayFolder": "2. Keys",
            "lineageTag": "6fd4df8c-44db-4409-8315-b40e45f5abd8",
            "summarizeBy": "none"
          },
          {
            "name": "Region Territory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Region Territory",
            "displayFolder": "2. Keys",
            "lineageTag": "6c78a402-ead1-478f-992f-8441afc5e56f",
            "summarizeBy": "none"
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Product Type",
            "displayFolder": "2. Keys",
            "lineageTag": "520b9888-4cbb-48c2-8477-f47ac4e7db8d",
            "summarizeBy": "none"
          },
          {
            "name": "Forecast (EUR)",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Forecast (EUR)",
            "displayFolder": "1. Facts",
            "lineageTag": "d10f2d0f-43f4-4046-a7c1-fb6776ee8be2",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Forecast",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Factview].[Forecast]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "Forecast MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Forecast],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Forecast increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "12942bf1-1f34-4200-8038-600478765f5c"
          },
          {
            "name": "Forecast QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "1981a533-3cb2-4bd1-97e1-2f4d01e27d4e"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast QTD]",
              "VAR _DELTA  = [Gross Sales] - [Forecast QTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "fb19f74f-2e88-4edb-bc5b-4f76834f6d7f"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast QTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "c855f2a3-d4a0-4864-88e7-cd34b11971bc"
          },
          {
            "name": "Forecast YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_YTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "60023d30-549e-400c-ba14-886e6841dc78"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast YTD]",
              "VAR _DELTA  = [Gross Sales] - [Forecast YTD]",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "7866e72b-8135-4bb6-b1c8-71801e93630e"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "dcdbf7fa-a675-45f6-9c32-663af23b30bb"
          },
          {
            "name": "Total Forecast",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Forecast'[Forecast (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "459bf9c6-c2c5-45cb-9572-8a3b72febdd4"
          },
          {
            "name": "Forecast",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[From Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[From Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Forecast'[Forecast (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Forecast'[Forecast (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "f06ae201-2cdc-436c-a294-bf86798ba4d1"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "cf24c709-2d75-4bcc-b628-575bd04c05c6"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [Forecast MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "2ba4ac80-c8bb-49c1-8eed-cb7280903306"
          },
          {
            "name": "Forecast vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "9a88b7d1-d518-410d-93a9-e7b6155afaff"
          },
          {
            "name": "Forecast vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Forecast]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "0117fd99-3132-49f8-a931-24976ff0df43"
          }
        ]
      },
      {
        "name": "Order Document Type",
        "lineageTag": "98dc4ee1-f2b2-4268-8f55-764f78cb8de9",
        "columns": [
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Sales Order Document Type Code",
            "displayFolder": "2. Keys",
            "lineageTag": "23989504-d4f7-40a5-80ca-da1e6d82cfe2",
            "summarizeBy": "none"
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "Text",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "0e6ab05d-0471-48c9-9832-dd5d693a3723",
            "summarizeBy": "none"
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Doc. Type Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "5e6fe644-e133-4a23-b3cf-c883fdb0b32d",
            "summarizeBy": "none"
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "Group",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "05be21a1-fda0-4480-9fcb-4ed07b969c6e",
            "summarizeBy": "none"
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Group Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "784d3791-105f-4093-aefb-d4decc314b10",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Order Document Type",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Order Document Type]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Order Status",
        "lineageTag": "c23160dc-06d3-49ab-b846-2cc393c6a3e1",
        "columns": [
          {
            "name": "Order Status Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Order Status Code",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "11460a7e-4e41-4c0b-a4b6-193d0206433e",
            "summarizeBy": "none"
          },
          {
            "name": "Order Status Text",
            "dataType": "string",
            "sourceColumn": "Order Status Text",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "a563ccf3-3694-4da1-b86c-0fb1eaed9ce7",
            "summarizeBy": "none"
          },
          {
            "name": "Order Status Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "d46b6c7d-011f-4bd9-b177-be70e1149f17",
            "summarizeBy": "none"
          },
          {
            "name": "Order Status Group",
            "dataType": "string",
            "sourceColumn": "Order Status Group",
            "sortByColumn": "Order Status Grouping Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "5ce86bc0-0ab5-4e34-b2df-73ba6f1a51bc",
            "summarizeBy": "none"
          },
          {
            "name": "Order Status Grouping Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Order Status Grouping Ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "e7b244d3-2773-4972-9946-6658d2afa5f1",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Order Status",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Dimview].[Order Status]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Last Refresh",
        "lineageTag": "b9c79b75-8023-455a-878a-511564ddc8c3",
        "columns": [
          {
            "name": "Last Refresh",
            "dataType": "dateTime",
            "sourceColumn": "Last Refresh",
            "formatString": "General Date",
            "lineageTag": "1a749a74-c3d7-4e91-b74e-42e9fe4c90a9",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "Last Refresh",
            "dataView": "full",
            "source": {
              "type": "query",
              "query": "SELECT GETDATE() AS [Last Refresh]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ]
      },
      {
        "name": "Invoices",
        "lineageTag": "c77cd123-26c5-4d3d-aaf0-9bf4acaa8d1c",
        "columns": [
          {
            "name": "Billing Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Number",
            "formatString": "0",
            "displayFolder": "Columns",
            "lineageTag": "fb5543d4-9841-4997-9814-adce6fab5fcc",
            "summarizeBy": "sum"
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Billing Date",
            "formatString": "Long Date",
            "displayFolder": "Columns",
            "lineageTag": "5ee1bb70-4682-4b7e-8b0b-d01cbd531a59",
            "summarizeBy": "none"
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Customer Key",
            "displayFolder": "Columns",
            "lineageTag": "03a90a69-7d99-4b1e-9b67-9fde82d38979",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Billing Document Line Item Number",
            "formatString": "0",
            "displayFolder": "Columns",
            "lineageTag": "a30ecbe1-2039-401c-98f2-2cb39c941f95",
            "summarizeBy": "sum"
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Product Key",
            "formatString": "0",
            "displayFolder": "Columns",
            "lineageTag": "c0a3fb74-7f0a-41ca-8eb1-7ea4293c3932",
            "summarizeBy": "none"
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "Ship Date",
            "formatString": "Long Date",
            "displayFolder": "Columns",
            "lineageTag": "912ce4e0-c50a-4dcc-a105-2d460e3fe033",
            "summarizeBy": "none"
          },
          {
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "OTD Indicator",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "displayFolder": "Columns",
            "lineageTag": "9a677935-2aab-4d99-b858-eaf55e1f1109",
            "summarizeBy": "none"
          },
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Billing Document Type Code",
            "displayFolder": "Columns",
            "lineageTag": "9cadb0fc-91ec-4c90-b0ff-897b7a046eee",
            "summarizeBy": "none"
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Local Currency",
            "displayFolder": "Columns",
            "lineageTag": "47f9edab-7cab-440b-8fd1-ca08d9b50bda",
            "summarizeBy": "none"
          },
          {
            "name": "Delivery Cost",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Delivery Cost",
            "displayFolder": "Columns",
            "lineageTag": "8d0f4e66-fdc2-46a0-ad00-c1bd4d1ac62b",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Invoice COGS",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Invoice COGS",
            "displayFolder": "Columns",
            "lineageTag": "31ee6930-3c3c-4a19-a5f1-c2d791a55631",
            "summarizeBy": "sum"
          },
          {
            "name": "Late Delivery Penalties",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Late Delivery Penalties",
            "displayFolder": "Columns",
            "lineageTag": "4f39beb4-d8fd-48a4-989b-d60283ab8d6c",
            "summarizeBy": "sum"
          },
          {
            "name": "Overdue Payment Penalties",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Overdue Payment Penalties",
            "displayFolder": "Columns",
            "lineageTag": "0a6f5da8-1113-4854-9d08-52e4d470c866",
            "summarizeBy": "sum"
          },
          {
            "name": "Taxes & Commercial Fees",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Taxes & Commercial Fees",
            "displayFolder": "Columns",
            "lineageTag": "aada0d25-8847-400b-9bc7-e48968e6d628",
            "summarizeBy": "sum"
          },
          {
            "name": "Freight",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Freight",
            "displayFolder": "Columns",
            "lineageTag": "438c6902-b5f9-4444-aff1-01b95b4199d0",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Invoice Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "Net Invoice Value",
            "displayFolder": "Columns",
            "lineageTag": "53a73d5c-99b5-4b56-bfd6-0d19c8dde3ca",
            "summarizeBy": "sum"
          },
          {
            "name": "Net Invoice Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Net Invoice Quantity",
            "formatString": "0",
            "displayFolder": "Columns",
            "lineageTag": "c95db9ca-9896-4210-a1af-fb905e69573d",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Invoices",
            "source": {
              "type": "query",
              "query": "SELECT * FROM [Factview].[Invoices]",
              "dataSource": "SpacePartsCoDW"
            }
          }
        ],
        "measures": [
          {
            "name": "Delivery Margin (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "",
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Freight Surcharge],",
              "        'Invoice Document Type'[Billing Document Type Code] IN {\"invoice\", \"express\"}",
              "    )",
              "VAR _MARGIN = [Delivery Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "fb011f9c-2f34-46df-af78-a3c25369e485"
          },
          {
            "name": "Delivery Margin 1YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "149849fa-faf9-4a93-a59e-bcf2e1e05c86"
          },
          {
            "name": "Delivery Margin 2YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "c6c57103-47b0-43ab-9686-e7a6f8ba3c3d"
          },
          {
            "name": "Delivery Margin (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Freight] - 'Invoices'[Delivery Cost]",
              "    ),",
              "    'Invoice Document Type'[Billing Document Type Code] IN { \"invoice\", \"express\" }",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "33afda90-268b-4d95-bbd3-24af998516d7"
          },
          {
            "name": "Delivery Margin 1YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "7ee13fca-4ce3-4cec-946b-7654d9f8b075"
          },
          {
            "name": "Delivery Margin 2YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "317ca015-569e-48f4-9546-e68e46c2307a"
          },
          {
            "name": "Selling Margin (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Billing Document Type Code] = \"invoice\"",
              "    )",
              "VAR _MARGIN = [Selling Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "db3928a6-cd2e-453c-9349-e9c6d7b49c5e"
          },
          {
            "name": "Selling Margin 1YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "8ca017a3-e7e4-43a3-b4c8-a6b08381e46f"
          },
          {
            "name": "Selling Margin 2YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "6442826e-ce55-46c0-8a2f-50897b2b1650"
          },
          {
            "name": "Selling Margin (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Net Invoice Value] - 'Invoices'[Net Invoice COGS]",
              "    ),",
              "    'Invoice Document Type'[Billing Document Type Code] = \"invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "5231a576-730b-41ad-be7a-21af5e1f4e6c"
          },
          {
            "name": "Selling Margin 1YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "ab1af0ea-0c4e-4f83-87a5-35ec7eab1037"
          },
          {
            "name": "Selling Margin 2YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "fc22c604-2b60-4b8f-88d1-615ea35424c0"
          },
          {
            "name": "Standard Margin (%)",
            "description": "System.Object[]",
            "expression": [
              "",
              "DIVIDE ( [Standard Margin (Value)], [Net Sales] ) "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "84c12c4c-53a8-404a-97f0-1c7aceebf46b"
          },
          {
            "name": "Standard Margin 1YP (%)",
            "description": "System.Object[]",
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "ec3f7a2a-15a5-4f79-a6aa-82fa342a7e3d"
          },
          {
            "name": "Standard Margin 2YP (%)",
            "description": "System.Object[]",
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "ea3fcc4f-4b75-4813-a569-4c7da0414dd0"
          },
          {
            "name": "Standard Margin (Value)",
            "description": "System.Object[]",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net Sales",
              "            VAR _NET = ",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "            -- COGS",
              "            VAR _COST =",
              "            ('Invoices'[Net Invoice COGS] ",
              "                + 'Invoices'[Delivery Cost] )",
              "",
              "            RETURN",
              "",
              "            ( _NET - _COST ) / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected rate",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "923773ba-9acc-4940-bb99-94209041f5ab"
          },
          {
            "name": "Standard Margin 1YP (Value)",
            "description": "System.Object[]",
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "c46fb0ae-d20b-4f08-bcc8-21cb602acd87"
          },
          {
            "name": "Standard Margin 2YP (Value)",
            "description": "System.Object[]",
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "5fecd6fa-9f00-4aec-8df7-2737af12b027"
          },
          {
            "name": "Gross Sales",
            "expression": [
              "",
              "[Total Net Invoice Value]",
              "    + [Total Freight Surcharge]",
              "    + [Total Late Delivery Penalties]",
              "    + [Total Overdue Payment Penalties]",
              "    - [Total Taxes & Commercial Fees]"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "e6998c9b-e42f-4f35-bb88-344f6acd08ed"
          },
          {
            "name": "Gross Sales (Selected Unit)",
            "expression": [
              "",
              "-- Sideways recursion",
              "CALCULATE (",
              "    [Actuals],",
              "    ALL ( '1) Selected Metric'[Select a Measure] ),",
              "    '1) Selected Metric'[Select a Measure] = \"Gross Sales\"",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "d2222fda-9ec6-4bce-ad4c-0915bac91ac2"
          },
          {
            "name": "MTD Gross Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "30264af0-8f27-4c4b-8957-da4d9d122d26"
          },
          {
            "name": "Total Net Invoice Value",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Value]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice Value]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "24a1eb0b-0a82-4752-87ac-d38fddce5077"
          },
          {
            "name": "Gross Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "b744eb43-ce5d-44d7-9c8f-9d13a1d4ee0f"
          },
          {
            "name": "Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 1YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "47a1e7b2-4688-46be-9ee9-fedc4f1c9fba"
          },
          {
            "name": "Gross Sales vs 1YP (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "b32adc9a-6bb3-4d5e-a762-9026362a3a5b"
          },
          {
            "name": "MTD Gross Sales 1YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 1YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "23e08328-1ab8-48bb-b6c2-e35631d4a617"
          },
          {
            "name": "MTD Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "3119048f-c463-4acf-9756-b5ccc6516e6d"
          },
          {
            "name": "MTD Gross Sales vs 1YP (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "b80dda13-bc99-45e2-bc92-1764f987c1d1"
          },
          {
            "name": "Gross Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "2541eb43-9d57-4fb0-9875-fb5acfba73ec"
          },
          {
            "name": "Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 2YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "cb15f4ba-91a7-4a06-a5db-262f078c0aa0"
          },
          {
            "name": "Gross Sales vs 2YP (Δ)",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 2YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "d82913f1-7376-48b3-b8b0-3d582972d31c"
          },
          {
            "name": "MTD Gross Sales 2YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 2YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "b5dbd8b5-a868-473d-b3ad-81078c659042"
          },
          {
            "name": "MTD Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "da399abb-6590-435e-a84a-241057d0e939"
          },
          {
            "name": "MTD Gross Sales vs. 2YP (Δ)",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "9938f8a9-939c-49e7-a947-e2f42db98c0d"
          },
          {
            "name": "Net Sales",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net sales",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "2688ee31-a076-4ec0-8159-2ff3627205b0"
          },
          {
            "name": "Net Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "ac188433-386e-40e3-8e8c-1de4fa6e5782"
          },
          {
            "name": "Net Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "bd9adac8-52e8-4651-9ac6-2ca7e1f3d63f"
          },
          {
            "name": "Total Cost",
            "description": "The cost of the product sold and the shipment / delivery",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- COGS",
              "            ('Invoices'[Net Invoice COGS] + 'Invoices'[Delivery Cost])",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "5544ced7-6ea7-4ef5-a818-a580406a5433"
          },
          {
            "name": "Total Delivery Cost",
            "description": "The cost of the delivery only",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Delivery Cost]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "7ae97de2-8134-420b-989b-79a623f05015"
          },
          {
            "name": "Total Net Invoice COGS",
            "description": "All costs associated with the sold product",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice COGS]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "9e687e2e-0cbf-41d4-9f44-2cfe43c4b095"
          },
          {
            "name": "Total Fees & Penalties",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Total fees & penalties",
              "            ('Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties]",
              "                - 'Invoices'[Taxes & Commercial Fees])",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "58e18ed3-f759-4d76-90a5-c0eb99ebb447"
          },
          {
            "name": "Total Late Delivery Penalties",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Late Delivery Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "7e4f5411-428c-4e38-8408-b3c0707cdc2c"
          },
          {
            "name": "Total Overdue Payment Penalties",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Overdue Payment Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "67f9bc32-0688-44fd-b143-a11976410329"
          },
          {
            "name": "Total Taxes & Commercial Fees",
            "description": "This measure is theSumof column 'Invoices'[Taxes & Commercial Fees]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Taxes & Commercial Fees]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "64616f1e-14ae-4f8b-8f55-62be00f3dcaf"
          },
          {
            "name": "Total Freight Surcharge",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "            'Invoices'[Freight]",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\III. Freight",
            "lineageTag": "17212cd2-ee0a-474f-8e18-c6dc5845ce28"
          },
          {
            "name": "Invoice Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Invoices' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "66c6dcc7-d6ad-4e18-a894-f96e7a4ca4d6"
          },
          {
            "name": "Gross Sales (Quantity)",
            "expression": [
              "",
              "[Total Net Invoice Quantity]"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "46079247-7d94-4628-b3d1-3e502ed0d89f"
          },
          {
            "name": "Gross Sales 1YP (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales (Quantity)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "2507e48b-8b08-4614-ae12-36ec1bc81819"
          },
          {
            "name": "Total Net Invoice Quantity",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Quantity]",
            "expression": "SUM ( 'Invoices'[Net Invoice Quantity] )",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "fc0da561-733c-44b7-9a27-baa9f3350d06"
          }
        ]
      },
      {
        "name": "Z01CG1 - Quantity",
        "isHidden": true,
        "lineageTag": "34170c94-662f-4b33-866a-df75e8a09b11",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 0
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders (Quantity)]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z01CG2 - Value (Budget Rate)",
        "isHidden": true,
        "lineageTag": "6eac316b-7209-4aa5-9b95-713214da26bd",
        "calculationGroup": {
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Gross Sales]"
              ],
              "ordinal": 0
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Value]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "[Total Net Invoice COGS]"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "[Total Delivery Cost]"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "[Total Freight Surcharge]"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "[Total Taxes & Commercial Fees]"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "[Total Overdue Payment Penalties]"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "[Total Late Delivery Penalties]"
              ],
              "ordinal": 8
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z01CG4 - Lines",
        "isHidden": true,
        "lineageTag": "b56f8923-c2b2-4bcf-81b3-fb525a3e6ecd",
        "calculationGroup": {
          "precedence": 3,
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Invoice Lines]"
              ],
              "ordinal": 0
            },
            {
              "name": "Net Sales",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 1
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 3
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 9
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z02CG1 - Unit",
        "isHidden": true,
        "lineageTag": "2e15af20-4180-4a93-ba59-84f7ca511e1a",
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Value (Budget Rate)",
              "expression": [
                "",
                "[Value]"
              ],
              "ordinal": 0
            },
            {
              "name": "Quantity",
              "expression": [
                "",
                "[Quantity]"
              ],
              "ordinal": 1
            },
            {
              "name": "Lines",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Unit",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z03CG1 - Sales Target",
        "isHidden": true,
        "lineageTag": "e06e9541-0883-4c06-a218-ed4bb2335b39",
        "calculationGroup": {
          "precedence": 6,
          "calculationItems": [
            {
              "name": "Budget",
              "expression": [
                "",
                "[Total Budget]"
              ],
              "ordinal": 0
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "[Forecast]"
              ],
              "ordinal": 1
            },
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Gross Sales 1YP (Selected Unit)]"
              ],
              "ordinal": 2
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Gross Sales 2YP (Selected Unit)]"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z03CG2 - Orders Target",
        "isHidden": true,
        "lineageTag": "d13081d2-ddac-49e0-ad85-3f8ea2c5619a",
        "calculationGroup": {
          "precedence": 7,
          "calculationItems": [
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Net Orders 1YP]"
              ],
              "ordinal": 0
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Net Orders 2YP]"
              ],
              "ordinal": 1
            },
            {
              "name": "Budget",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 2
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Z04CG1 - Time Intelligence",
        "isHidden": true,
        "lineageTag": "1e2e1320-0522-4e6d-ae4c-bb027e82efab",
        "calculationGroup": {
          "precedence": 4,
          "calculationItems": [
            {
              "name": "Daily",
              "expression": [
                "",
                "SELECTEDMEASURE()"
              ],
              "ordinal": 0
            },
            {
              "name": "MTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESMTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "QTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESQTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "YTD",
              "expression": [
                "",
                "VAR _YTD =",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        CALCULATETABLE (",
                "            DATESYTD ('Date'[Date]),",
                "            'Date'[IsDateInScope]",
                "        )",
                "    )",
                "VAR _FULL_YTD =",
                "    CALCULATE (SELECTEDMEASURE (), DATESYTD ('Date'[Date]))",
                "RETURN",
                "    IF (",
                "        SEARCH (\"Actuals\", SELECTEDMEASURENAME (), , 999) <> 999,",
                "        _YTD,",
                "        _FULL_YTD",
                "    )"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Aggregation",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal"
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal"
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "6513c6c1-edcf-4854-95ac-6bb9b0043719",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": false,
            "isKey": true,
            "sourceColumn": "[Date]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "2f663a4a-9815-445d-92c4-231123627a27",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Number (ie 2021)",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Calendar Year Number (ie 2021)]",
            "displayFolder": "1. Year",
            "lineageTag": "129c4ab8-c4a6-45dd-bc2c-fe1695b9850c",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year (ie 2021)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year (ie 2021)]",
            "sortByColumn": "Calendar Year Number (ie 2021)",
            "displayFolder": "1. Year",
            "lineageTag": "48d8a5f7-7809-4cf8-a319-1c270d8bb0c8",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter Year (ie Q1 2021)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter Year (ie Q1 2021)]",
            "sortByColumn": "Calendar Year Quarter (ie 202101)",
            "displayFolder": "2. Quarter",
            "lineageTag": "55d80110-3269-4ee4-825c-4b3ac4635d3e",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Quarter (ie 202101)",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Calendar Year Quarter (ie 202101)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "f1b1c176-3e6f-4632-9c96-4698fbcf3320",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Year (ie Jan 21)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Year (ie Jan 21)]",
            "sortByColumn": "Calendar Year Month (ie 202101)",
            "displayFolder": "3. Month",
            "lineageTag": "a9928fdf-fad1-4276-8858-b28f9fa55085",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Month (ie 202101)",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Calendar Year Month (ie 202101)]",
            "displayFolder": "3. Month",
            "lineageTag": "095e7dad-51e4-4b76-8876-d2c1ea074631",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month (ie Jan)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month (ie Jan)]",
            "sortByColumn": "Calendar Month # (ie 1)",
            "displayFolder": "3. Month",
            "lineageTag": "3c3fd413-a6f6-4f29-bc44-21519c11b33d",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month # (ie 1)",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Calendar Month # (ie 1)]",
            "displayFolder": "3. Month",
            "lineageTag": "c4104480-4ac9-4cae-bbb3-eeb6c431543f",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week EU (ie WK25)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week EU (ie WK25)]",
            "sortByColumn": "Calendar Week Number EU (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "0193d648-33b7-4f1e-b0e2-aa234feb3668",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number EU (ie 25)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number EU (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "44cfee4b-aa96-4d54-9268-985d7b2c2ab0",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number EU (ie 202125)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number EU (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "dbd38bb5-d0d7-4315-9de0-10c65edb3948",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week US (ie WK25)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week US (ie WK25)]",
            "sortByColumn": "Calendar Week Number US (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "5c24907e-9759-4e08-b9ae-0a3330385365",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number US (ie 25)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number US (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "c16d636b-9026-4f53-addf-ba7998bbb08c",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number US (ie 202125)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number US (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "e69bf8b5-05e1-4140-8494-05c39fd33bad",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week ISO (ie WK25)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week ISO (ie WK25)]",
            "sortByColumn": "Calendar Week Number ISO (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "794e3e1d-f609-4249-aa56-1322c5a7a7cc",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number ISO (ie 25)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number ISO (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "66104697-ade2-4b53-bacd-d83f4e849a82",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number ISO (ie 202125)",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number ISO (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "5e80a080-3dd0-4b5a-bf62-632734b4ef42",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Short (i.e. Mon)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Short (i.e. Mon)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "cdb5d03e-8cc4-4811-980a-6c1cfeca8fa5",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Name (i.e. Monday)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Name (i.e. Monday)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "b81b306e-eb7a-465a-9cac-6a98683e2f6e",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Number EU (i.e. 1)",
            "dataType": "int64",
            "isNameInferred": false,
            "sourceColumn": "[Weekday Number EU (i.e. 1)]",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "8e093eee-8cba-43c3-87d1-232524636df4",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. Jan 05)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. Jan 05)]",
            "sortByColumn": "Calendar Month Day (i.e. 0105)",
            "displayFolder": "3. Month",
            "lineageTag": "4948fb1e-a6b8-4a8e-9aa5-72a3e67c6a2b",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. 0105)",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. 0105)]",
            "displayFolder": "3. Month",
            "lineageTag": "4d02afdc-d075-43bc-afcf-89f41d70830a",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YYYYMMDD",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YYYYMMDD]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "8042d5ff-0eec-46d9-bc45-d363ee973f0b",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsDateInScope",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsDateInScope]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "21b58a7f-d22c-409b-9b23-f8292b6283e7",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsBeforeThisMonth",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsBeforeThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "a513ed29-a43c-40f1-99ba-8d0133977321",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsLastMonth",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsLastMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "17e71bdb-08f0-4744-9713-9a7793f581b8",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsYTD",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsYTD]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "0329dbfa-0a08-4e28-b5b4-e206aac2f4f1",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsActualToday",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsActualToday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "78b8ea00-60d6-4da7-976f-04e910d3c462",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsRefDate",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsRefDate]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "4bbbc8d1-26e6-4647-943c-3229ad0e245f",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsHoliday",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsHoliday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "02a8a09c-1b00-4e84-a184-b67c5cebad6a",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWeekday",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWeekday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "f5c4b667-27a5-4d00-b0f9-a76de9aa8ae1",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisYear",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisYear]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "a6db2123-59e7-44e1-ba69-8660028011f7",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisMonth",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "e55a4ae7-dab1-4cb0-bde1-cf4f21ad0681",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisQuarter",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisQuarter]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "535b7a6d-b3bb-4041-b46d-7bb1a0b17e43",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisWeek",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisWeek]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "d6df94d6-ab22-4e5e-b4ab-334f827fa630",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter (ie Q1)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter (ie Q1)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "b10a6eec-5bd0-4297-a207-9550ce4df729",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year Number (ie 2025)",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Year Number (ie 2025)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "9c16e282-ad27-4924-b1fe-d4a6bb323521",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year (ie FY25)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Year (ie FY25)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "934b1bfe-9f4d-42fb-b82a-5a11e139e950",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Quarter (ie FQ1)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Quarter (ie FQ1)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "fb2dfe5c-d334-4de8-9842-8aafb6505bb9",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Quarter Number (ie 1)",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Quarter Number (ie 1)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "c0435800-6df1-48a1-a5e6-856ab34ad0f2",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Year Quarter (ie FY25 Q1)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Year Quarter (ie FY25 Q1)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "f8545802-c686-4b9a-8a99-b232acf8ecab",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Month Number (ie 1)",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Month Number (ie 1)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "fd3c4201-c6b2-480a-a2dd-1509ea71d46d",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Fiscal Month (ie FM01)",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Fiscal Month (ie FM01)]",
            "displayFolder": "8. Fiscal",
            "lineageTag": "f63dc5b7-765d-4f3f-af72-b697a688a804",
            "summarizeBy": "none"
          },
          {
            "type": "calculated",
            "name": "Workdays MTD",
            "dataType": "int64",
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "bc4217ea-bd02-4b15-819d-d355284b0dcd",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Workdays QTD",
            "dataType": "int64",
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Quarter Year (ie Q1 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "35d5f8ad-882c-40c2-9de5-62ff269cd342",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Workdays YTD",
            "dataType": "int64",
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Year (ie 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "065c64d8-8eb5-4cf2-9c64-d88da28d9fdb",
            "summarizeBy": "sum"
          },
          {
            "type": "calculated",
            "name": "Workdays MTD %",
            "dataType": "double",
            "expression": [
              "DIVIDE (",
              "    'Date'[Workdays MTD],",
              "    /* Number of weekdays MTD for selected month */",
              "    CALCULATE (",
              "        [# Workdays in Selected Month],",
              "        ALLEXCEPT ( 'Date', 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ),",
              "    /* Total number of weekdays for selected month */",
              "    0",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "209f26f9-6f84-4cf6-9c75-dceb086ef52a",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "-- Reference date for the latest date in the report",
                "-- Until when the business wants to see data in reports",
                "VAR _Refdate_Measure = [RefDate]",
                "VAR _Today = TODAY ( )",
                "",
                "-- Replace with \"Today\" if [RefDate] evaluates blank",
                "VAR _Refdate = IF ( ISBLANK ( _Refdate_Measure ), _Today, _Refdate_Measure )",
                "    VAR _RefYear        = YEAR ( _Refdate )",
                "    VAR _RefQuarter     = _RefYear * 100 + QUARTER(_Refdate)",
                "    VAR _RefMonth       = _RefYear * 100 + MONTH(_Refdate)",
                "    VAR _RefWeek_EU     = _RefYear * 100 + WEEKNUM(_Refdate, 2)",
                "",
                "-- Fiscal calendar settings (July start)",
                "VAR _FiscalYearStartMonth = 7",
                " ",
                "-- Earliest date in the model scope",
                "VAR _EarliestDate       = DATE ( YEAR ( MIN ( 'Orders'[Order Date] ) ) - 2, 1, 1 )",
                "VAR _EarliestDate_Safe  = MIN ( _EarliestDate, DATE ( YEAR ( _Today ) + 1, 1, 1 ) )",
                "",
                "-- Latest date in the model scope",
                "VAR _LatestDate_Safe    = DATE ( YEAR ( _Refdate ) + 2, 12, 1 )",
                "",
                "------------------------------------------",
                "-- Base calendar table",
                "VAR _Base_Calendar      = CALENDAR ( _EarliestDate_Safe, _LatestDate_Safe )",
                "------------------------------------------",
                "",
                "",
                "",
                "------------------------------------------",
                "VAR _IntermediateResult = ",
                "    ADDCOLUMNS ( _Base_Calendar,",
                "",
                "            ------------------------------------------",
                "        \"Calendar Year Number (ie 2021)\",           --|",
                "            YEAR ([Date]),                          --|-- Year",
                "                                                    --|",
                "        \"Calendar Year (ie 2021)\",                  --|",
                "            FORMAT ([Date], \"YYYY\"),                --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Quarter Year (ie Q1 2021)\",       --|",
                "            \"Q\" &                                   --|-- Quarter",
                "            CONVERT(QUARTER([Date]), STRING) &      --|",
                "            \" \" &                                   --|",
                "            CONVERT(YEAR([Date]), STRING),          --|",
                "                                                    --|",
                "        \"Calendar Year Quarter (ie 202101)\",        --|",
                "            YEAR([Date]) * 100 + QUARTER([Date]),   --|",
                "                                                    --| ",
                "        \"Calendar Quarter (ie Q1)\",                 --|",
                "            \"Q\" &                                   --|",
                "            CONVERT(QUARTER([Date]), STRING),       --|  ",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Month Year (ie Jan 21)\",          --|",
                "            FORMAT ( [Date], \"MMM YY\" ),            --|-- Month",
                "                                                    --|",
                "        \"Calendar Year Month (ie 202101)\",          --|",
                "            YEAR([Date]) * 100 + MONTH([Date]),     --|",
                "                                                    --|",
                "        \"Calendar Month (ie Jan)\",                  --|",
                "            FORMAT ( [Date], \"MMM\" ),               --|",
                "                                                    --|",
                "        \"Calendar Month # (ie 1)\",                  --|",
                "            MONTH ( [Date] ),                       --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Week EU (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 2 ),            --|-- Week",
                "                                                    --|",
                "        \"Calendar Week Number EU (ie 25)\",          --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number EU (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week US (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 1 ),            --|",
                "                                                    --|",
                "        \"Calendar Week Number US (ie 25)\",          --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number US (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week ISO (ie WK25)\",              --|",
                "            \"WK\" & WEEKNUM( [Date], 21 ),           --|",
                "                                                    --|",
                "        \"Calendar Week Number ISO (ie 25)\",         --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "                                                    --|",
                "        \"Calendar Year Week Number ISO (ie 202125)\",--|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Weekday Short (i.e. Mon)\",                 --|",
                "            FORMAT ( [Date], \"DDD\" ),               --|-- Weekday",
                "                                                    --|",
                "        \"Weekday Name (i.e. Monday)\",               --|",
                "            FORMAT ( [Date], \"DDDD\" ),              --|",
                "                                                    --|",
                "        \"Weekday Number EU (i.e. 1)\",               --|",
                "            WEEKDAY ( [Date], 2 ),                  --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Month Day (i.e. Jan 05)\",         --|",
                "            FORMAT ( [Date], \"MMM DD\" ),            --|-- Day",
                "                                                    --|",
                "        \"Calendar Month Day (i.e. 0105)\",           --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date]),                            --|",
                "                                                    --|",
                "        \"YYYYMMDD\",                                 --|",
                "            YEAR ( [Date] ) * 10000                 --|",
                "            +                                       --|",
                "            MONTH ( [Date] ) * 100                  --|",
                "            +                                       --|",
                "            DAY ( [Date] ),                         --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Fiscal Year Number (ie 2025)\",             --|",
                "            IF (                                    --|-- Fiscal Year",
                "                MONTH([Date]) >= _FiscalYearStartMonth,",
                "                YEAR([Date]) + 1,                   --|",
                "                YEAR([Date])                        --|",
                "            ),                                      --|",
                "                                                    --|",
                "        \"Fiscal Year (ie FY25)\",                    --|",
                "            \"FY\" &                                  --|",
                "            RIGHT(                                  --|",
                "                IF (                                --|",
                "                    MONTH([Date]) >= _FiscalYearStartMonth,",
                "                    YEAR([Date]) + 1,               --|",
                "                    YEAR([Date])                    --|",
                "                ),                                  --|",
                "                2                                   --|",
                "            ),                                      --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Fiscal Quarter (ie FQ1)\",                  --|",
                "            \"FQ\" &                                  --|-- Fiscal Quarter",
                "            SWITCH (                                --|",
                "                TRUE(),                             --|",
                "                MONTH([Date]) IN {7, 8, 9}, 1,      --|",
                "                MONTH([Date]) IN {10, 11, 12}, 2,   --|",
                "                MONTH([Date]) IN {1, 2, 3}, 3,      --|",
                "                4                                   --|",
                "            ),                                      --|",
                "                                                    --|",
                "        \"Fiscal Quarter Number (ie 1)\",             --|",
                "            SWITCH (                                --|",
                "                TRUE(),                             --|",
                "                MONTH([Date]) IN {7, 8, 9}, 1,      --|",
                "                MONTH([Date]) IN {10, 11, 12}, 2,   --|",
                "                MONTH([Date]) IN {1, 2, 3}, 3,      --|",
                "                4                                   --|",
                "            ),                                      --|",
                "                                                    --|",
                "        \"Fiscal Year Quarter (ie FY25 Q1)\",         --|",
                "            \"FY\" &                                  --|",
                "            RIGHT(                                  --|",
                "                IF (                                --|",
                "                    MONTH([Date]) >= _FiscalYearStartMonth,",
                "                    YEAR([Date]) + 1,               --|",
                "                    YEAR([Date])                    --|",
                "                ),                                  --|",
                "                2                                   --|",
                "            ) &                                     --|",
                "            \" Q\" &                                  --|",
                "            SWITCH (                                --|",
                "                TRUE(),                             --|",
                "                MONTH([Date]) IN {7, 8, 9}, 1,      --|",
                "                MONTH([Date]) IN {10, 11, 12}, 2,   --|",
                "                MONTH([Date]) IN {1, 2, 3}, 3,      --|",
                "                4                                   --|",
                "            ),                                      --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Fiscal Month Number (ie 1)\",               --|",
                "            IF (                                    --|-- Fiscal Month",
                "                MONTH([Date]) >= _FiscalYearStartMonth,",
                "                MONTH([Date]) - _FiscalYearStartMonth + 1,",
                "                MONTH([Date]) + 12 - _FiscalYearStartMonth + 1",
                "            ),                                      --|",
                "                                                    --|",
                "        \"Fiscal Month (ie FM01)\",                   --|",
                "            \"FM\" &                                  --|",
                "            FORMAT (                                --|",
                "                IF (                                --|",
                "                    MONTH([Date]) >= _FiscalYearStartMonth,",
                "                    MONTH([Date]) - _FiscalYearStartMonth + 1,",
                "                    MONTH([Date]) + 12 - _FiscalYearStartMonth + 1",
                "                ),                                  --|",
                "                \"00\"                                --|",
                "            ),                                      --|",
                "            ------------------------------------------",
                "",
                "",
                "            ------------------------------------------",
                "        \"IsDateInScope\",                            --|",
                "            [Date] <= _Refdate                      --|-- Boolean",
                "            &&                                      --|",
                "            YEAR([Date]) > YEAR(_EarliestDate),     --|",
                "                                                    --|",
                "        \"IsBeforeThisMonth\",                        --|",
                "            [Date] <= EOMONTH ( _Refdate, -1 ),     --|",
                "                                                    --|",
                "        \"IsLastMonth\",                              --|",
                "            [Date] <= EOMONTH ( _Refdate, 0 )       --|",
                "            &&                                      --|",
                "            [Date] > EOMONTH ( _Refdate, -1 ),      --|",
                "                                                    --|",
                "        \"IsYTD\",                                    --|",
                "            MONTH([Date])                           --|",
                "            <=                                      --|",
                "            MONTH(EOMONTH ( _Refdate, 0 )),         --|",
                "                                                    --|",
                "        \"IsActualToday\",                            --|",
                "            [Date] = _Today,                        --|",
                "                                                    --|",
                "        \"IsRefDate\",                                --|",
                "            [Date] = _Refdate,                      --|",
                "                                                    --|",
                "        \"IsHoliday\",                                --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date])                             --|",
                "                IN {0101, 0501, 1111, 1225},        --|",
                "                                                    --|",
                "        \"IsWeekday\",                                --|",
                "            WEEKDAY([Date], 2)                      --|",
                "                IN {1, 2, 3, 4, 5})                 --|",
                "            ------------------------------------------",
                "",
                "VAR _Result = ",
                "    ",
                "            --------------------------------------------",
                "    ADDCOLUMNS (                                      --|",
                "        _IntermediateResult,                          --|-- Boolean #2",
                "        \"IsThisYear\",                                 --|",
                "            [Calendar Year Number (ie 2021)]          --|",
                "                = _RefYear,                           --|",
                "                                                      --|",
                "        \"IsThisMonth\",                                --|",
                "            [Calendar Year Month (ie 202101)]         --|",
                "                = _RefMonth,                          --|",
                "                                                      --|",
                "        \"IsThisQuarter\",                              --|",
                "            [Calendar Year Quarter (ie 202101)]       --|",
                "                = _RefQuarter,                        --|",
                "                                                      --|",
                "        \"IsThisWeek\",                                 --|",
                "            [Calendar Year Week Number EU (ie 202125)]--|",
                "                = _RefWeek_EU                         --|",
                "    )                                                 --|",
                "            --------------------------------------------",
                "            ",
                "RETURN ",
                "    _Result"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Workdays MTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays MTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "60bdc822-da58-425d-b3a8-d0ec14e2f312"
          },
          {
            "name": "# Workdays QTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays QTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "f28169d7-9111-43ee-9723-519011228003"
          },
          {
            "name": "# Workdays YTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays YTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "6c4cfb23-68e4-49ce-a554-864e087bdd1a"
          },
          {
            "name": "# Workdays in Selected Month",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays MTD]),",
              "        VALUES ('Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "1da7bbf4-b761-44c5-b411-0ea1de9c7fad"
          },
          {
            "name": "# Workdays in Selected Quarter",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays QTD]),",
              "        VALUES ('Date'[Calendar Quarter Year (ie Q1 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "1edc05f2-c0e6-4cf2-8511-c44f57eaa3cc"
          },
          {
            "name": "# Workdays in Selected Year",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays YTD]),",
              "        VALUES ('Date'[Calendar Year (ie 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "71319ef0-6894-4427-b347-0c8b876dcad3"
          },
          {
            "name": "% Workdays MTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays MTD], [# Workdays in Selected Month]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "678d4d16-3b7f-40df-8635-db7db5208782"
          },
          {
            "name": "% Workdays QTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays QTD], [# Workdays in Selected Quarter]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "25a17f8f-7107-4ed9-bc5c-69dd1256713e"
          },
          {
            "name": "% Workdays YTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays YTD], [# Workdays in Selected Year]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "25a18387-c551-485b-b15c-e7f965b2013e"
          },
          {
            "name": "RefDate",
            "expression": "CALCULATE ( MAX ( 'Invoices'[Billing Date] ), REMOVEFILTERS ( ) )",
            "isHidden": true,
            "displayFolder": "Measures",
            "lineageTag": "b36b7dea-8c27-4cb4-be04-79464effbbaf"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "4216428d-7af3-4006-9590-023b7edf4fb4",
            "levels": [
              {
                "name": "Calendar Year (ie 2021)",
                "ordinal": 0,
                "column": "Calendar Year (ie 2021)",
                "lineageTag": "ad11366c-4406-4cf0-85fb-a604e8b8434d"
              },
              {
                "name": "Calendar Quarter (ie Q1)",
                "ordinal": 1,
                "column": "Calendar Quarter (ie Q1)",
                "lineageTag": "3b449542-4bbb-4382-9447-c4f9febf4228"
              },
              {
                "name": "Calendar Month (ie Jan)",
                "ordinal": 2,
                "column": "Calendar Month (ie Jan)",
                "lineageTag": "0e1fd81d-29bc-465b-b3f5-a32861704881"
              },
              {
                "name": "Calendar Week EU (ie WK25)",
                "ordinal": 3,
                "column": "Calendar Week EU (ie WK25)",
                "lineageTag": "7a51c7a0-e8a5-4f66-bd74-75f765929f43"
              },
              {
                "name": "Weekday Short (i.e. Mon)",
                "ordinal": 4,
                "column": "Weekday Short (i.e. Mon)",
                "lineageTag": "ce178dee-63c1-4be5-b51b-972c7cfc1989"
              },
              {
                "name": "Date",
                "ordinal": 5,
                "column": "Date",
                "lineageTag": "e765a7b5-800b-49f6-9301-57db5d6f217f"
              }
            ]
          }
        ]
      },
      {
        "name": "On-Time Delivery",
        "lineageTag": "a6c750ce-9b49-4944-bdff-c5cd95f9da62",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Invoices[OTD Indicator]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sortByColumn": "OTD Sort Order",
            "lineageTag": "a3a6b5dd-1f39-42a4-a8cb-874213eddd67",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Status",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Status]",
            "sortByColumn": "OTD Sort Order",
            "lineageTag": "2b7de0c4-6fc1-49b6-bbea-1114483be060",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Sort Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Sort Order]",
            "lineageTag": "78270986-031d-463d-a222-ae89bcc1dadd",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "On-Time Delivery",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    FILTER (",
                "        DISTINCT ('Invoices'[OTD Indicator]),",
                "        NOT ISBLANK ('Invoices'[OTD Indicator])",
                "    ),",
                "    \"OTD Status\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, \"On Time\",",
                "            \"Late\"",
                "        ),",
                "    \"OTD Sort Order\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, 1,",
                "            2",
                "        )",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "OTD % (Lines)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Lines)]",
              "VAR _Total = CALCULATE (",
              "    [Invoice Lines],",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "3. Lines",
            "lineageTag": "3f44f863-80b8-49b7-b6ed-6e7665fecbc9"
          },
          {
            "name": "OTD % (Quantity)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Quantity)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Quantity],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "2. Quantity",
            "lineageTag": "1c1710ac-e928-490e-a541-9c409d09a27e"
          },
          {
            "name": "OTD % (Value)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Value)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value",
            "lineageTag": "94c07e4d-d5aa-4814-bf6f-5df4b53d6a8f"
          },
          {
            "name": "OTD (Lines)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Invoice Lines],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "6b16df47-8395-402c-b5c9-c0ba5c9345ab"
          },
          {
            "name": "OTD (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Quantity],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "4c9f3344-4cfd-4864-9f7b-50094b8f6ef6"
          },
          {
            "name": "OTD (Value)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Value],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value",
            "lineageTag": "1f16789e-1262-47dc-ba2d-a9a7f0183b4f"
          }
        ]
      },
      {
        "name": "1) Selected Metric",
        "description": "It lets you select a Metric.",
        "lineageTag": "6dd28e74-0803-4db8-ab39-76eccf2f8aa0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Select a Measure",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Measure]",
            "sortByColumn": "Order",
            "lineageTag": "92cf31b3-542e-4f59-918d-166b1573f299",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "53797334-7847-4608-9d6a-71214825cfb8",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "1) Selected Metric",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z01CG2 - Value (Budget Rate)',",
                "        \"Select a Measure\", 'Z01CG2 - Value (Budget Rate)'[Measure],",
                "        \"Order\", 'Z01CG2 - Value (Budget Rate)'[Ordinal]",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "2) Selected Unit",
        "description": "System.Object[]",
        "lineageTag": "706a8c9c-f978-4777-b185-487822549e5e",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Select a Unit",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Unit]",
            "sortByColumn": "Order",
            "lineageTag": "a75422da-f194-48c3-9a5e-d4b46cee231d",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "46fe0dd6-a4e2-4755-99e9-be887538d49a",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "2) Selected Unit",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z02CG1 - Unit',",
                "        \"Select a Unit\", 'Z02CG1 - Unit'[Unit],",
                "        \"Order\", 'Z02CG1 - Unit'[Ordinal]",
                ") "
              ]
            }
          }
        ]
      },
      {
        "name": "3) Selected Target",
        "description": "System.Object[]",
        "lineageTag": "74cb38fd-9ffd-4028-86ff-a5f073859246",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Select a Target",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Target]",
            "sortByColumn": "Order",
            "lineageTag": "459ca6b6-8992-4f78-8e79-1db1ccf88fb1",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "d7faa363-5937-4d54-aa79-123ab85eb320",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "MTD Slicer",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD Slicer]",
            "sortByColumn": "Order",
            "lineageTag": "57c9f16b-1915-4ec7-ac35-94c31a3f5913",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "3) Selected Target",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    'Z03CG1 - Sales Target',",
                "    \"Select a Target\", 'Z03CG1 - Sales Target'[Target],",
                "    \"Order\", 'Z03CG1 - Sales Target'[Ordinal],",
                "    \"MTD Slicer\",",
                "        VAR _TARGET = 'Z03CG1 - Sales Target'[Target]",
                "        RETURN",
                "            SWITCH (",
                "                TRUE (),",
                "                _TARGET = \"Budget\",         \"Gross Sales MTD vs. Budget\",",
                "                _TARGET = \"Forecast\",       \"Gross Sales MTD vs. FCST\",",
                "                _TARGET = \"1 Year Prior\",   \"Gross Sales MTD vs. 1YP\",",
                "                _TARGET = \"2 Years Prior\",  \"Gross Sales MTD vs. 2YP\"",
                "            )",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "4) Selected Period",
        "description": "System.Object[]",
        "lineageTag": "e4ec70b3-30b5-4d98-8247-ff180cf24995",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD]",
            "lineageTag": "93da36a6-b34c-44b4-b697-b1f4ec2cbff1",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "QTD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[QTD]",
            "lineageTag": "5b8ff8f9-2883-41f4-bf2a-dac084747750",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "YTD",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YTD]",
            "lineageTag": "8e26448b-df9d-48a3-86a4-95ae9045a270",
            "summarizeBy": "none"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "d2b96867-fbdd-4eb7-8932-e562d174d099",
            "summarizeBy": "sum"
          },
          {
            "type": "calculatedTableColumn",
            "name": "Period",
            "dataType": "string",
            "isNameInferred": false,
            "isDataTypeInferred": true,
            "sourceColumn": "[Period]",
            "lineageTag": "d7c4530b-793b-46d4-9def-b379659ec0d9",
            "summarizeBy": "none"
          }
        ],
        "partitions": [
          {
            "name": "4) Selected Period",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "UNION (",
                "    ROW (",
                "        \"Period\", {\"Full Period\"},",
                "        \"Order\", {0},",
                "        \"MTD\", {\"Full Month\"},",
                "        \"QTD\", {\"Full Quarter\"},",
                "        \"YTD\", {\"Full Year\"}",
                "    ),",
                "    ROW (",
                "        \"Period\", {\"Period-to-Date\"},",
                "        \"Order\", {1},",
                "        \"MTD\", {\"MTD\"},",
                "        \"QTD\", {\"QTD\"},",
                "        \"YTD\", {\"YTD\"}",
                "    )",
                ")"
              ]
            }
          }
        ]
      },
      {
        "name": "__Measures",
        "description": "System.Object[]",
        "isHidden": true,
        "lineageTag": "632bc845-f8fa-4017-a8e9-a7fe2b6e3429",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "lineageTag": "a89ced23-8b26-4cc7-abb9-bf836542dd8f",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "__Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actuals",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('2) Selected Unit'[Select a Unit]),",
              "        'Z02CG1 - Unit'[Unit]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "3f14ddaa-bef4-4110-8360-1f505cd79506"
          },
          {
            "name": "Actuals MTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Actuals",
            "lineageTag": "3f77f30a-f78b-4f82-be95-29bb387f1e93"
          },
          {
            "name": "Actuals QTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Actuals",
            "lineageTag": "53160c0d-4ace-45e6-aa23-353717092799"
          },
          {
            "name": "Actuals YTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "19a20892-3d4a-4a30-b7e5-5e7a7b65cb75"
          },
          {
            "name": "Lines",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG4 - Lines'[Measure]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "b4c0c893-0231-478c-94bd-6b4735ea0e49"
          },
          {
            "name": "Quantity",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG1 - Quantity'[Measure])",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "1bba8bc5-c7df-45dc-8b16-76cef4f64b05"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target YTD]",
              "VAR _DELTA  = [Actuals YTD] -  _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "4. YTD",
            "lineageTag": "307e98ff-6f93-40fa-bbf8-bca80f62ccc7"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (Δ)",
            "expression": [
              "",
              "[Actuals YTD] - [Sales Target YTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "41cd1e7c-909e-4ae8-90e3-28d801e74345"
          },
          {
            "name": "Value",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG2 - Value (Budget Rate)'[Measure]",
              "    )",
              ") "
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "aa495471-d1fc-48f9-a0ae-057a4a48bc45"
          },
          {
            "name": "Sales Target YTD",
            "expression": [
              "",
              "VAR YRTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESYTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsBeforeThisMonth] = TRUE",
              "    ) // Calculates the target for the current month/year selection",
              "VAR _CurrentMonth_value =",
              "    CALCULATE( [Sales Target], 'Date'[IsThisMonth] = TRUE ) // Calculates the % workdays MTD together with the dynamic parameter to set the exponential rate of increase MTD",
              "VAR _currentMonthWorkDay =",
              "    POWER(",
              "        CALCULATE(",
              "            MAX( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE,",
              "            'Date'[IsThisMonth] = TRUE",
              "        ),",
              "        0.93",
              "    ) // If viewing units, hide the FCST (as there is no units FCST as of July 09, 2020)",
              "VAR MOTD =",
              "    IF(",
              "        _CurrentMonth_value > 0,",
              "        _currentMonthWorkDay * _CurrentMonth_value,",
              "        BLANK( )",
              "    )",
              "        + YRTD",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _YEAR = MAX( 'Date'[Calendar Year Number (ie 2021)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Number (ie 2021)] = _YEAR,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        // If date is in the visual context and YTD is blank, show MTD, otherwise add YTD + MTD together",
              "        MOTD",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "bc9faa0b-f186-4310-bc30-ceabc385ef29"
          },
          {
            "name": "Sales Target QTD",
            "expression": [
              "",
              "VAR _QTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESQTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _MTD =",
              "    CALCULATE( [Sales Target MTD], 'Date'[IsThisMonth] = TRUE )",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _QUARTER = MAX( 'Date'[Calendar Year Quarter (ie 202101)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Quarter (ie 202101)] = _QUARTER,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        IF(",
              "            ISBLANK( _QTD ),",
              "            _MTD,",
              "            // If date is in the visual context and QTD is blank, show MTD, otherwise add QTD + MTD together",
              "            IF( MAX ( 'Date'[Date] ) >= MAX ('Last Refresh'[Last Refresh]), _QTD + _MTD, _QTD )",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Sales Target",
            "lineageTag": "fafa9006-7ebe-4f29-a164-5077cd559ede"
          },
          {
            "name": "Sales Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Sales Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "VAR CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "9b8a2c53-abf0-47ce-be91-625ff3620137"
          },
          {
            "name": "Sales Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT (",
              "            '3) Selected Target'[Select a Target]",
              "        ),",
              "        'Z03CG1 - Sales Target'[Target]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "ce363427-0240-42ff-baad-867139e7bf99"
          },
          {
            "name": "Sales Target vs. Actuals (Δ)",
            "expression": [
              "",
              "[Actuals] - [Sales Target]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "6e2179bb-92a6-4bfd-993f-5e5927c62a49"
          },
          {
            "name": "Sales Target vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target]",
              "VAR _ACTUAL = [Actuals]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "19ea6160-d480-4215-a9c8-355f4502142f"
          },
          {
            "name": "Sales Target MTD vs. Actuals (Δ)",
            "expression": [
              "",
              "[Actuals MTD] - [Sales Target MTD]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "b38c07f0-fcc6-446d-9ea7-9f7ba4dc4ff8"
          },
          {
            "name": "Sales Target MTD vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target MTD]",
              "VAR _ACTUAL = [Actuals MTD]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "db579ace-257a-466c-879c-9e2e339cb7ee"
          },
          {
            "name": "Actuals MTD, Latest Data Point",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        [Actuals MTD]",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "e6540427-b7cd-485b-8b38-612a710310cf"
          },
          {
            "name": "Actuals MTD, Data Label",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        \"#6e8c95\",",
              "        \"#FFFFFF00\"",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "fd65490b-3920-4114-9865-53f058727b0a"
          },
          {
            "name": "Blank",
            "expression": [
              "",
              "BLANK ()"
            ],
            "isHidden": true,
            "displayFolder": "9. Technical Measures",
            "lineageTag": "31c4e84c-19d1-4df2-a0ea-889c8ab650da"
          },
          {
            "name": "Orders Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ( '3) Selected Target'[Select a Target] ), 'Z03CG2 - Orders Target'[Target] )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "2c38dcfc-6641-40c0-ba52-d29587796082"
          },
          {
            "name": "Orders Target vs. Net Orders (%)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "VAR _TARGET = [Orders Target]",
              "VAR _DELTA  = [Net Orders] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ↑;#,##0.0% ↓;#,##0.0%",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "906d5bf9-765a-46fb-9e11-ed2553d114aa"
          },
          {
            "name": "Orders Target vs. Net Orders (Δ)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "[Net Orders] - [Orders Target]"
            ],
            "formatString": "#,##0 ↑;#,##0 ↓;#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "cf227c6a-c422-4c9a-b2f1-771a84082ae3"
          },
          {
            "name": "Orders Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "    ",
              "VAR __HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        __HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            __HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Orders Target",
            "lineageTag": "370e2137-e13b-41e3-b3c3-22e9d6725d44"
          },
          {
            "name": "Orders Target QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Orders Target MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Orders Target], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Orders Target",
            "lineageTag": "6a493c4f-ae56-4cb6-8b3c-46d38e1c6f1f"
          },
          {
            "name": "Orders Target YTD",
            "expression": [
              "",
              "VAR _CURRENT_MONTH_TARGET = [Orders Target MTD]",
              "VAR _YTD_TARGET_BEFORE_THIS_MONTH =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        CALCULATETABLE (",
              "            DATESYTD ('Date'[Date]),",
              "            'Date'[IsThisMonth] = FALSE,",
              "            'Date'[IsDateInScope] = TRUE",
              "        )",
              "    )",
              "VAR _RESULT = _CURRENT_MONTH_TARGET + _YTD_TARGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "ef4978a4-935c-4014-ac05-7f39d85e26c5"
          },
          {
            "name": "Gross Sales 2YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "d9b67bc4-7d7f-4e4f-97c5-bcef6c42c99f"
          },
          {
            "name": "Gross Sales 1YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "c4d7af89-9b87-4ecb-897f-ada36a3808d4"
          }
        ]
      },
      {
        "name": "__Demo Measures",
        "description": "5 measures usable without any selection; quick-start",
        "lineageTag": "8e2fd85a-346c-4cfb-bfc7-c565aeff6e9a",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": false,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "lineageTag": "289af42c-6cb8-4035-9815-dbd5c9da4144",
            "summarizeBy": "sum"
          }
        ],
        "partitions": [
          {
            "name": "__Demo Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "5025b598-5f85-4e4e-a785-b09c15febc35"
          },
          {
            "name": "Sales Budget",
            "expression": [
              "",
              "CALCULATE (",
              "    [Budget],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "eb5f7f56-9d8d-4b56-96bf-7902cc18966f"
          },
          {
            "name": "Sales Forecast",
            "expression": [
              "",
              "CALCULATE (",
              "    [Forecast],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "98c66c9a-05e5-4daa-aea3-ddfee28a6258"
          },
          {
            "name": "Billing Document Lines",
            "expression": "[Invoice Lines]",
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "786a2e0a-eedb-429c-abc8-e7d1b5a9c9f6"
          },
          {
            "name": "# Accounts",
            "expression": "1",
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "a119c86f-b1b7-4316-9afc-eb8c60e4a85d"
          },
          {
            "name": "ActualVsTargetColor",
            "expression": [
              "",
              "IF (",
              "    [Gross Sales (Quantity)]",
              "        > [Sales Target],",
              "    \"good\", -- Good color (blue)",
              "    \"bad\"  -- Bad color (yellow)",
              ")"
            ],
            "lineageTag": "52fd365d-7069-48c0-88da-4eaf72b8ad9c"
          },
          {
            "name": "No. Products",
            "expression": "COUNTROWS ( 'Products' )",
            "formatString": "#,##0 Products",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "54c3463a-97a6-4729-af24-64a15be0d225"
          },
          {
            "name": "CustomData",
            "expression": "CUSTOMDATA()",
            "lineageTag": "bce9a80c-c09f-4e9a-bad1-be2e20e66a8c"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "0ab05116-f3bb-443b-836c-1d3069ea7692",
        "fromTable": "Customers",
        "fromColumn": "Station",
        "toTable": "Regions",
        "toColumn": "Station"
      },
      {
        "name": "7fd9b229-fb0c-4067-8e09-876f36d2e56b",
        "fromTable": "Products",
        "fromColumn": "Sub Brand Name",
        "toTable": "Brands",
        "toColumn": "Sub Brand"
      },
      {
        "name": "70d81d9e-d13d-4e04-8ea3-557efe979868",
        "fromTable": "Budget",
        "fromColumn": "Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "b58b794d-3b93-4d3f-9028-367c81920dd4",
        "fromTable": "Budget",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "a15c183c-ad08-4783-97d9-6adc448abe6a",
        "fromTable": "Budget",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "82029d11-e9d6-42f8-b30d-5893a689abd2",
        "fromTable": "Exchange Rate",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "e3144ecd-ad05-431b-98ee-dcc01f42cc11",
        "fromTable": "Orders",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "6149a8fc-3e28-40d7-b1a6-2921f90274e3",
        "fromTable": "Orders",
        "fromColumn": "Request Goods Receipt Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "385a9e79-1bfc-4d8b-8ccc-ec622969b484",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Line Item Status",
        "toTable": "Order Status",
        "toColumn": "Order Status Code"
      },
      {
        "name": "b9a7a478-d423-4ab4-bd8e-4d7d0baca4db",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Type Code",
        "toTable": "Order Document Type",
        "toColumn": "Sales Order Document Type Code"
      },
      {
        "name": "f2c890d2-aa3d-4e8e-8656-ee47cbe0786d",
        "fromTable": "Orders",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "c66244a6-1861-4abb-95b9-bd80fc0ab050",
        "fromTable": "Orders",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "8971e92e-ba96-4583-8c69-5636b85e0684",
        "fromTable": "Forecast",
        "fromColumn": "Forecast Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "fb54ddb0-44de-4c9f-9c78-2cb6172b2fc0",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Product Type",
        "toTable": "Products",
        "toColumn": "Type"
      },
      {
        "name": "38942b90-6a32-4a79-a03e-98ecc6670e0c",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Region Territory",
        "toTable": "Regions",
        "toColumn": "Territory"
      },
      {
        "name": "ac13c076-0942-42b5-b427-b6660e1ce8ee",
        "fromTable": "Orders",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "93ac1a19-5871-4e5b-93a6-27b02ac884bc",
        "fromTable": "Invoices",
        "fromColumn": "Billing Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "003dd442-0175-4b7d-87d3-fdd56769b6b1",
        "fromTable": "Invoices",
        "fromColumn": "Billing Document Type Code",
        "toTable": "Invoice Document Type",
        "toColumn": "Billing Document Type Code"
      },
      {
        "name": "2d60aaa4-4807-45c3-9184-9ed4e1bf1193",
        "fromTable": "Invoices",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "edf2f760-c2c7-4000-9e2a-d82d27b9d8d4",
        "fromTable": "Invoices",
        "fromColumn": "OTD Indicator",
        "toTable": "On-Time Delivery",
        "toColumn": "OTD Indicator"
      },
      {
        "name": "45eca776-d64d-458a-a5e2-eb9e2373de1a",
        "fromTable": "Invoices",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "d1a883c7-0e65-44bb-bfc9-4c6c68f15c74",
        "fromTable": "Invoices",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      }
    ],
    "annotations": [
      {
        "name": "__TEdtr",
        "value": "1"
      },
      {
        "name": "TabularProcessingBatch_Budget",
        "value": "full"
      },
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":false,\"LocalPerspectives\":false,\"SortArrays\":false,\"LocalRelationships\":false,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/Calculation Items\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      }
    ]
  }
}