{
  "name": "SpacePartsBim",
  "id": "90c78d27-49f6-4236-9b8c-f87b72915ae6",
  "compatibilityLevel": 1702,
  "model": {
    "name": "SpacePartsBim",
    "culture": "en-US",
    "collation": "Latin1_General_100_BIN2_UTF8",
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "discourageImplicitMeasures": true,
    "sourceQueryCulture": "en-US",
    "tables": [
      {
        "name": "Brands",
        "lineageTag": "5e2b506f-5416-43b6-b5f6-160cbd60ab96",
        "columns": [
          {
            "name": "Flagship",
            "dataType": "string",
            "sourceColumn": "flagship",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "16be3840-ea52-4cb5-bbc1-f866be4193aa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Class",
            "dataType": "string",
            "sourceColumn": "class",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "e3b11f72-6c3d-4151-a219-5df0d87c75ab",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "type",
            "displayFolder": "2. Brand Attributes",
            "lineageTag": "f1c1b582-1730-4828-a57c-9e4148579d68",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Brand",
            "dataType": "string",
            "sourceColumn": "brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "026cc844-0d0a-444c-b3e6-4755b618ee1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sub Brand",
            "dataType": "string",
            "sourceColumn": "sub_brand",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "64d691d4-8f81-40ad-9626-f50a0fb25bfa",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Brand VP",
            "dataType": "string",
            "sourceColumn": "product_brand_vp",
            "displayFolder": "3. Managers",
            "lineageTag": "cd36ed0c-b7f0-404f-b8a0-ced180569814",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Brands",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"brands\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Brand Hierarchy",
            "displayFolder": "1. Brand Hierarchy",
            "lineageTag": "084d70b4-6315-42f4-9fa3-84fac3f33e6b",
            "levels": [
              {
                "name": "Class",
                "ordinal": 0,
                "column": "Class",
                "lineageTag": "5457edb0-3439-4d56-baf9-e14078ae42d6"
              },
              {
                "name": "Flagship",
                "ordinal": 1,
                "column": "Flagship",
                "lineageTag": "63f540d1-6f1a-4224-b13d-e5e8cf74727c"
              },
              {
                "name": "Brand",
                "ordinal": 2,
                "column": "Brand",
                "lineageTag": "47d9b70c-0dbe-4719-9c28-498808e9fe1b"
              },
              {
                "name": "Sub Brand",
                "ordinal": 3,
                "column": "Sub Brand",
                "lineageTag": "4cf48791-4d41-4f0d-988b-385822b676aa"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Budget Rate",
        "isHidden": true,
        "lineageTag": "68dde8df-0ca5-4974-9afa-a3d1fc7dcf1f",
        "columns": [
          {
            "name": "Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "rate",
            "displayFolder": "1. Facts",
            "lineageTag": "46c64843-a8c8-49af-9770-8144db4c3640",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "from_currency",
            "displayFolder": "2. Keys",
            "lineageTag": "df013c22-0791-4223-9fe0-f45c70d95063",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "to_currency",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "d7d777a5-9b43-429b-a5eb-fb1ab1549af7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "currency_system",
            "displayFolder": "3. Other Currency Fields",
            "lineageTag": "f92a040a-f088-449b-8486-33aeeef0c9b2",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Budget Rate",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"budget_rate\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Customers",
        "lineageTag": "c247ff24-c33b-4a9e-96f6-95d1e36e4be4",
        "columns": [
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "customer_key",
            "displayFolder": "4. Keys",
            "lineageTag": "8138d992-9c95-4468-ad79-4607af12e82e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Sold-To Name",
            "dataType": "string",
            "sourceColumn": "customer_soldto_name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "57a55013-2487-4f85-9924-ba95d30adf0c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Name",
            "dataType": "string",
            "sourceColumn": "account_name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "a0b900e7-c1c7-4a87-aa1a-a52a61ece17d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Key Account Name",
            "dataType": "string",
            "sourceColumn": "key_account_name",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "449b79b3-9236-4e65-9f9e-2ac349ace7be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Transaction Type",
            "dataType": "string",
            "sourceColumn": "transaction_type",
            "displayFolder": "2. Other Customer Attributes",
            "lineageTag": "d288644d-e68b-417a-b6ad-c229a86c5de4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Type",
            "dataType": "string",
            "sourceColumn": "account_type",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "a0a0a72d-6c54-4e38-89c2-acf0084d375a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "station",
            "displayFolder": "4. Keys",
            "lineageTag": "22b532a7-95c9-4055-98bd-f6c8624e21ea",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Account Manager",
            "dataType": "string",
            "sourceColumn": "account_manager",
            "displayFolder": "3. Managers",
            "lineageTag": "67fe957e-20ff-43ea-ae81-6e377ee37f71",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Key Account Manager",
            "dataType": "string",
            "sourceColumn": "key_account_manager",
            "displayFolder": "3. Managers",
            "lineageTag": "72fc9786-6102-4514-a9f0-35cfc60809b4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Customers",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "",
                "  // Data Source",
                "  Source = Sql.Database(",
                "    #\"SqlEndpoint\", ",
                "    #\"Database\"",
                "  ), ",
                "",
                "  // Step",
                "  Data = Source",
                "    {",
                "      [",
                "        Schema = \"dbo\", ",
                "        Item   = \"customers\"",
                "      ]",
                "    }",
                "    [Data]",
                "",
                "// Result",
                "in",
                "  Data"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Customers",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "b99fd2f5-eff7-4fe3-8fee-b4f9e758f2bf"
          },
          {
            "name": "# Key Accounts",
            "expression": [
              "",
              "COUNTROWS (",
              "    VALUES ( 'Customers'[Key Account Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "19c6259b-8906-4d55-9f07-f38335a43d03"
          }
        ],
        "hierarchies": [
          {
            "name": "Customer Hierarchy",
            "displayFolder": "1. Customer Hierarchy",
            "lineageTag": "21ce8263-4484-4671-9324-29eb1d5fb394",
            "levels": [
              {
                "name": "Account Type",
                "ordinal": 0,
                "column": "Account Type",
                "lineageTag": "63750788-6ce3-468b-acfb-48561f995e59"
              },
              {
                "name": "Key Account Name",
                "ordinal": 1,
                "column": "Key Account Name",
                "lineageTag": "695025d0-549e-4b7c-b020-926a32b43d89"
              },
              {
                "name": "Account Name",
                "ordinal": 2,
                "column": "Account Name",
                "lineageTag": "4701a595-a719-4c4c-a262-0961ea84c24b"
              },
              {
                "name": "Customer Sold-To Name",
                "ordinal": 3,
                "column": "Customer Sold-To Name",
                "lineageTag": "24730ed3-e089-46de-bd4c-26f648c4a791"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"03e537eb-3ddb-4c20-b5ad-9090c0aadd0d\",",
              "    \"fromTable\": \"Customers\",",
              "    \"fromColumn\": \"Station\",",
              "    \"toTable\": \"Regions\",",
              "    \"toColumn\": \"Station\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Employees",
        "isHidden": true,
        "lineageTag": "524ed7be-f2f0-440f-9280-3b067d6f766e",
        "columns": [
          {
            "name": "Role",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "role",
            "displayFolder": "Columns",
            "lineageTag": "3d1387dd-01f0-4f13-ab38-811f06cd1359",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "employee_name",
            "displayFolder": "Columns",
            "lineageTag": "fc711d7b-da3f-4e5e-9c68-0073c2489c1a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Employee Email",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "employee_email",
            "displayFolder": "Columns",
            "lineageTag": "e4e18027-3292-4531-9c47-c0d2bd3d8efb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Data Security Rule",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "data_security_rule",
            "displayFolder": "Columns",
            "lineageTag": "b08c9506-5704-406c-a5f5-5ea65d6623b8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Employees",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"employees\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Exchange Rate",
        "lineageTag": "01ee8527-a2dc-471d-9a3d-9ccfe51284ef",
        "columns": [
          {
            "name": "Rate Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "rate_type",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "452c5cfd-c704-4b98-be56-71082368b44b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "From Currency",
            "dataType": "string",
            "sourceColumn": "from_currency",
            "displayFolder": "1. Select a Currency",
            "lineageTag": "ee8bbaa9-0b3e-42bf-9d01-d907458159bc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "To Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "to_currency",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "7640e9c9-9b46-48e7-bdaa-c96bb487b625",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Currency System",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "currency_system",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "ee01193c-1f42-4aec-a1fc-45db6cabfb80",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "rate",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "c7c98d7b-101b-4fb0-b4b6-a1990adb1ecb",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "date",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "024862a6-5e54-4cc6-a1d7-2b7b1f393ad6",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "month",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "fe0e261d-d4be-49a5-b2d0-a644f272b0eb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Exchange Rate Composite Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "exchange_rate_composite_key",
            "displayFolder": "2. Other Currency Fields",
            "lineageTag": "5b3738b3-2625-4510-909a-71dd86316090",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Exchange Rate",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"exchange_rate\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"4a26dc2c-f944-4c6e-9670-5e66e566c970\",",
              "    \"fromTable\": \"Exchange Rate\",",
              "    \"fromColumn\": \"Date\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Invoice Document Type",
        "lineageTag": "dbcc3ac6-9a34-4dc6-8477-078cb12b3dd4",
        "columns": [
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "sourceColumn": "billing_document_type_code",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "e9a08be0-7588-41c4-bc84-7d10ed0d5d0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "text",
            "sortByColumn": "Doc. Type Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "b90274be-9a59-4782-b817-fe6c65a5c0b3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "doc_type_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "3439cdad-fc7d-4cfb-9b69-26b03bd3ef65",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "group",
            "sortByColumn": "Group Ordinal",
            "displayFolder": "1. Billing Doc. Type",
            "lineageTag": "494309fe-449d-447a-9522-5aaac15890e8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "group_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "5c8de158-176b-43a0-aa9d-5314d4b4ded6",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Invoice Document Type",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"invoice_doc_type\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Products",
        "lineageTag": "4963b255-25ef-4ad6-8fc0-3991443146a0",
        "columns": [
          {
            "name": "Sub Brand Name",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sub_brand_name",
            "displayFolder": "5. Keys",
            "lineageTag": "46b52e9b-f065-4a4b-a860-cbd239180893",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ship Class for Part",
            "dataType": "string",
            "sourceColumn": "ship_class_for_part",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "8b05870e-ec7e-4bee-b9cc-3998508fd4c9",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Name",
            "dataType": "string",
            "sourceColumn": "product_name",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "31fc2387-5a7f-4655-a5ea-0bc51c07852a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Part Fit Grading",
            "dataType": "string",
            "sourceColumn": "part_fit_grading",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "5832f019-fb01-4e09-ab32-ca411cb31e53",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_key",
            "displayFolder": "5. Keys",
            "lineageTag": "0af3eedf-9023-45c6-9b52-df7c4c69ee12",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Subtype",
            "dataType": "string",
            "sourceColumn": "subtype",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "15258ae0-314c-4258-b6a9-c5f4b1f7c0df",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Type",
            "dataType": "string",
            "sourceColumn": "type",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "85080b98-1526-4199-8045-b27395dcead7",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "MK",
            "dataType": "string",
            "sourceColumn": "mk",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "434ef8cd-463c-423c-98d0-133def571872",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Color",
            "dataType": "string",
            "sourceColumn": "color",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "d09831f4-99c0-40cd-b760-3fde292b3c21",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Production Series",
            "dataType": "string",
            "sourceColumn": "production_series",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "2c8917a4-56c0-41b2-aea6-2b4db37b3711",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Nameplate",
            "dataType": "string",
            "sourceColumn": "nameplate",
            "displayFolder": "2. Product Attributes",
            "lineageTag": "4e1f18fb-66c0-457f-a7df-65694bfe81de",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Material",
            "dataType": "string",
            "sourceColumn": "material",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "a78bca4e-9fc2-42b7-8e38-44a2800b9ad1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Maximum Temperature (K)",
            "dataType": "int64",
            "sourceColumn": "maximum_temperature_k",
            "displayFolder": "4. Product Facts",
            "lineageTag": "2005d462-c934-4b0d-9746-b46329fb408d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Business Line Leader",
            "dataType": "string",
            "sourceColumn": "product_business_line_leader",
            "displayFolder": "3. Product Managers",
            "lineageTag": "f7d90ab0-1767-4d3d-884b-33ce7aab8421",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Tolerance (g)",
            "dataType": "int64",
            "sourceColumn": "tolerance_g",
            "displayFolder": "4. Product Facts",
            "lineageTag": "5b9d9f23-63fd-4aca-99c3-8c2952190f4c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Velocity Tolerance (Meters / Second)",
            "dataType": "int64",
            "sourceColumn": "velocity_tolerance_meters__second",
            "displayFolder": "4. Product Facts",
            "lineageTag": "762198d6-0454-4be8-bd34-93a179964871",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Weight (Tonnes)",
            "dataType": "decimal",
            "sourceColumn": "weight_tonnes",
            "displayFolder": "4. Product Facts",
            "lineageTag": "cc3bfcfb-ca3a-48ef-a567-b767efcdf6bd",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Products",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"products\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Products",
            "expression": [
              "",
              "COUNTROWS ( ",
              "    VALUES ( 'Products'[Product Name] )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures",
            "lineageTag": "1fb6f2e9-ed3c-4c97-8fdc-95d1d037a0de"
          }
        ],
        "hierarchies": [
          {
            "name": "Product Hierarchy",
            "displayFolder": "1. Product Hierarchy",
            "lineageTag": "be3e77c0-e9ee-4ef7-947d-d4d075eeee9a",
            "levels": [
              {
                "name": "Type",
                "ordinal": 0,
                "column": "Type",
                "lineageTag": "5dc23be4-9e7d-4d9c-9125-29fff24963af"
              },
              {
                "name": "Subtype",
                "ordinal": 1,
                "column": "Subtype",
                "lineageTag": "aad230ae-d02b-40ca-909f-912eb59dbd84"
              },
              {
                "name": "Product Name",
                "ordinal": 2,
                "column": "Product Name",
                "lineageTag": "2faa8a87-f034-4a37-ae57-78226ae641ee"
              },
              {
                "name": "Material",
                "ordinal": 3,
                "column": "Material",
                "lineageTag": "3f546d11-2759-4b51-bd76-87db29036a7b"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"aee91ed3-e637-4150-a8d4-22619ecc0034\",",
              "    \"fromTable\": \"Products\",",
              "    \"fromColumn\": \"Sub Brand Name\",",
              "    \"toTable\": \"Brands\",",
              "    \"toColumn\": \"Sub Brand\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Regions",
        "lineageTag": "bca583de-764e-4d89-9f57-4f9b7afa671f",
        "columns": [
          {
            "name": "System",
            "dataType": "string",
            "sourceColumn": "system",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "33bdc3d4-f515-4abe-9c2b-b07cbf859c2a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Interplanetary Region",
            "dataType": "string",
            "sourceColumn": "interplanetary_region",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "e5e4b390-0dcc-4018-b87c-b484a852f032",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Territory",
            "dataType": "string",
            "sourceColumn": "territory",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "85ec7ff6-21a1-4ccc-bdb0-391f173c7cbb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station",
            "dataType": "string",
            "sourceColumn": "station",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "448ce04b-4b37-4836-a906-9cbeed4310be",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station Type",
            "dataType": "string",
            "sourceColumn": "station_type",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "143c4d29-e3be-4b74-9cc2-f2f5b2e31c5c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Territory Directors",
            "dataType": "string",
            "sourceColumn": "territory_directors",
            "displayFolder": "3. Managers",
            "lineageTag": "a55a008d-d15b-4c72-ac32-796786fb4cce",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "All",
            "dataType": "string",
            "sourceColumn": "all",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "01dabba0-927a-447c-933e-dd4282827050",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Station Sales Managers",
            "dataType": "string",
            "sourceColumn": "station_sales_managers",
            "displayFolder": "3. Managers",
            "lineageTag": "d38439ea-70ae-4a7f-82b1-6cdd6536ba53",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "System Regional Managers",
            "dataType": "string",
            "sourceColumn": "system_regional_managers",
            "displayFolder": "3. Managers",
            "lineageTag": "b59ca628-8da1-4052-aa67-ab015c55aaa1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "System Sales Directors",
            "dataType": "string",
            "sourceColumn": "system_sales_directors",
            "displayFolder": "3. Managers",
            "lineageTag": "af710796-8d11-4cc9-964f-6571ccfc7f0a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Tax Rate",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "tax_rate",
            "formatString": "#,##0.000",
            "displayFolder": "2. Region Attributes",
            "lineageTag": "39630edd-0932-46c0-9e86-5db2c308b51a",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Regions",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"regions\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Regional Hierarchy",
            "displayFolder": "1. Region Hierarchy",
            "lineageTag": "8ce16331-fb01-4dfb-bd38-da99652a4893",
            "levels": [
              {
                "name": "All",
                "ordinal": 0,
                "column": "All",
                "lineageTag": "d0892c44-a314-4400-a33c-1c9e05de3679"
              },
              {
                "name": "System",
                "ordinal": 1,
                "column": "System",
                "lineageTag": "eb24e180-a00e-4f4f-9b9f-03f0c2c33521"
              },
              {
                "name": "Interplanetary Region",
                "ordinal": 2,
                "column": "Interplanetary Region",
                "lineageTag": "df0d47d9-4330-4447-8fc4-7a3dead1f50d"
              },
              {
                "name": "Territory",
                "ordinal": 3,
                "column": "Territory",
                "lineageTag": "006fd1c2-f102-4ed6-b80b-677e2e392747"
              },
              {
                "name": "Station",
                "ordinal": 4,
                "column": "Station",
                "lineageTag": "d6c1f01c-580a-45be-ba9f-a0ce66a12255"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Budget",
        "lineageTag": "a6b0eb60-264f-474d-a8fe-ac16f65fbc35",
        "columns": [
          {
            "name": "Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "month",
            "formatString": "Long Date",
            "displayFolder": "1. Keys",
            "lineageTag": "23bef58e-18a2-4193-856d-2498101b880c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Budget (EUR)",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "total_budget",
            "displayFolder": "2. Facts",
            "lineageTag": "3f44e27b-e38e-489b-ab39-80615cb15782",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "customer_key",
            "displayFolder": "1. Keys",
            "lineageTag": "f748b942-7ab6-4a6a-800e-7e1acfe97bca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_key",
            "displayFolder": "1. Keys",
            "lineageTag": "f70c2f53-c04d-46a5-a162-d54d50bfffa0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Budget",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"budget\"]}[Data],",
                "    #\"Select Columns\" = Table.SelectColumns ( Data, {\"customer_key\", \"month\", \"product_key\", \"total_budget\"} )",
                "in",
                "    #\"Select Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "2022 Budget Achievement %",
            "expression": [
              "",
              "VAR _Sales =",
              "    CALCULATE (",
              "        [Gross Sales],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Budget =",
              "    CALCULATE (",
              "        [Total Budget],",
              "        'Date'[Calendar Year Number (ie 2021)]",
              "            = 2022,",
              "        'Date'[IsDateInScope] = TRUE ( ),",
              "        DATESYTD ( 'Date'[Date] )",
              "    )",
              "VAR _Delta = _Sales - _Budget",
              "VAR _Perc = DIVIDE ( _Delta, _Budget )",
              "RETURN",
              "    _Perc"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "f1e22bd1-bd4f-487d-84e0-7a4b863f1088"
          },
          {
            "name": "Budget MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Budget],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "e7c3e0f7-bc73-4250-93f4-17d3b3e06d2e"
          },
          {
            "name": "Budget MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "8eb42713-706d-436a-a1c4-dda1c25494e1"
          },
          {
            "name": "Budget MTD vs. Gross Sales ()",
            "expression": [
              "",
              "[MTD Gross Sales] - [Budget MTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "dae40a70-a31d-41e3-bf4d-f77b08aefe31"
          },
          {
            "name": "Budget QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_BUDGET_BEFORE_THIS_MONTH = CALCULATE ([Budget], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Budget + QTD_BUDGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "377282fa-8f79-4de5-b02c-9ed97ed804ff"
          },
          {
            "name": "Budget QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget QTD]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "4b634367-f3b3-4b7e-a4c5-11ae1f0005a3"
          },
          {
            "name": "Budget QTD vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Budget QTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "2a13f546-675f-46dc-80b9-e457b2aa9d01"
          },
          {
            "name": "Budget YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ( 'Date'[Date] ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Budget = [Budget MTD]",
              "VAR QTD_Budget_BEFORE_THIS_MONTH =",
              "    CALCULATE ( [Budget], _DATES_YTD )",
              "VAR _RESULT =",
              "    _CURRENT_MONTH_Budget",
              "        + QTD_Budget_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "4cfd4bbc-3ee3-4224-8224-89ba77bfd212"
          },
          {
            "name": "Budget YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget YTD]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "99f3b31f-c3eb-4f23-8403-959bdcf5cae0"
          },
          {
            "name": "Budget YTD vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Budget YTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "ee4a5a38-3679-4596-afa7-5f613a87ed87"
          },
          {
            "name": "Total Budget",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Budget'[Budget (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "1cfbbd0e-ec57-4948-8e7c-e8a520d634c7"
          },
          {
            "name": "Budget",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[From Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[From Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Budget'[Budget (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Budget'[Budget (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "60d839fc-8ab6-4b78-af3f-80bc6305c529"
          },
          {
            "name": "Budget vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Budget]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "e5eb5098-0e4f-4d23-b7c5-bb287ff8bb59"
          },
          {
            "name": "Budget vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Budget]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "824b1d58-869a-408c-a12e-ccdf950300ef"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"583c271a-a6ae-4f4b-bdb0-dfc91a31493e\",",
              "    \"fromTable\": \"Budget\",",
              "    \"fromColumn\": \"Customer Key\",",
              "    \"toTable\": \"Customers\",",
              "    \"toColumn\": \"Customer Key\"",
              "  },",
              "  {",
              "    \"name\": \"bbcee627-b8b2-4604-9ad8-9d2036321cfb\",",
              "    \"fromTable\": \"Budget\",",
              "    \"fromColumn\": \"Month\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\"",
              "  },",
              "  {",
              "    \"name\": \"b9c4b659-0116-4f12-af8c-704fe07f3112\",",
              "    \"fromTable\": \"Budget\",",
              "    \"fromColumn\": \"Product Key\",",
              "    \"toTable\": \"Products\",",
              "    \"toColumn\": \"Product Key\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Date",
        "lineageTag": "0bb45e29-3908-422d-ade4-4100434bdfa4",
        "dataCategory": "Time",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isKey": true,
            "sourceColumn": "[Date]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "09572bf6-eb54-4fb5-8ad1-1dee0c198ec0",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Number (ie 2021)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Number (ie 2021)]",
            "displayFolder": "1. Year",
            "lineageTag": "cf2e5156-c81b-4636-b66b-f9b439f92d2d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year (ie 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year (ie 2021)]",
            "sortByColumn": "Calendar Year Number (ie 2021)",
            "displayFolder": "1. Year",
            "lineageTag": "3fb515aa-1cf5-4e35-9368-26ba9fe9609b",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter Year (ie Q1 2021)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter Year (ie Q1 2021)]",
            "sortByColumn": "Calendar Year Quarter (ie 202101)",
            "displayFolder": "2. Quarter",
            "lineageTag": "d8f8780d-8364-4be5-ad87-fb1d7e8bb57c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Quarter (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Quarter (ie 202101)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "6303b430-6995-46b7-82b1-4cd3102b9d6d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Year (ie Jan 21)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Year (ie Jan 21)]",
            "sortByColumn": "Calendar Year Month (ie 202101)",
            "displayFolder": "3. Month",
            "lineageTag": "edb084ec-790c-4fee-a229-e24044d12bd4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Month (ie 202101)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Year Month (ie 202101)]",
            "displayFolder": "3. Month",
            "lineageTag": "2063cb48-7333-440e-acc1-5d12b4ef4641",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month (ie Jan)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month (ie Jan)]",
            "sortByColumn": "Calendar Month # (ie 1)",
            "displayFolder": "3. Month",
            "lineageTag": "40d9d72e-8593-4b4b-a7bc-78a324b1decb",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month # (ie 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month # (ie 1)]",
            "displayFolder": "3. Month",
            "lineageTag": "e19f6bb4-ef58-4a9b-9938-a9f53054cfca",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week EU (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week EU (ie WK25)]",
            "sortByColumn": "Calendar Week Number EU (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "da853b79-633f-4869-b291-880aa11452ad",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number EU (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number EU (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "3eb012c2-1bb5-4cc3-bf3e-4d98a1fbfd27",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number EU (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number EU (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "9239173d-70a1-4fb7-8ef8-b6b580e4c576",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week US (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week US (ie WK25)]",
            "sortByColumn": "Calendar Week Number US (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "54b2a8dd-1d3d-4350-8e50-ea3c2aa70603",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number US (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number US (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "ee4f45a3-e866-4cd7-9a08-6b8b3e96cef4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number US (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number US (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "6369e90a-ee7b-4da8-9884-0457e4366927",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week ISO (ie WK25)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week ISO (ie WK25)]",
            "sortByColumn": "Calendar Week Number ISO (ie 25)",
            "displayFolder": "4. Week",
            "lineageTag": "ef48982f-eb1c-4196-8059-9a69d4a1c7fe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Week Number ISO (ie 25)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Week Number ISO (ie 25)]",
            "displayFolder": "4. Week",
            "lineageTag": "ae46b8f1-44d5-450d-b322-33f5ecb3a0dc",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Year Week Number ISO (ie 202125)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Calendar Year Week Number ISO (ie 202125)]",
            "displayFolder": "4. Week",
            "lineageTag": "b7562b0b-32a5-49ab-8c2b-c0f933e8e272",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Short (i.e. Mon)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Short (i.e. Mon)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "41ab7d65-b8a5-4011-9814-92b110086158",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Name (i.e. Monday)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Name (i.e. Monday)]",
            "sortByColumn": "Weekday Number EU (i.e. 1)",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "ef85b198-9069-484e-b7d7-25425c242d1a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Weekday Number EU (i.e. 1)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Weekday Number EU (i.e. 1)]",
            "displayFolder": "5. Weekday / Workday\\Weekday",
            "lineageTag": "6d6d80e2-e8a9-4d10-acff-4d7531522034",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. Jan 05)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. Jan 05)]",
            "sortByColumn": "Calendar Month Day (i.e. 0105)",
            "displayFolder": "3. Month",
            "lineageTag": "1b09698b-a90f-40ce-9596-6c6047ebe042",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Month Day (i.e. 0105)",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Month Day (i.e. 0105)]",
            "displayFolder": "3. Month",
            "lineageTag": "6e7c0f3a-b2bb-411a-a0a7-e267d7807ab4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YYYYMMDD",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YYYYMMDD]",
            "displayFolder": "6. Calendar Date",
            "lineageTag": "b8f541e5-acb5-4fdf-83b9-c031aee1e282",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsDateInScope",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsDateInScope]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "4bca850c-4687-484d-a941-8b82c8ac9435",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsBeforeThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsBeforeThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3a3ebb62-fa77-42c9-94e7-7dd38cbcc9ca",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsLastMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsLastMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3cf4eb07-f6c1-4297-a58d-37d7bc7c0c5d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsYTD",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsYTD]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "1be5363a-e1d5-42c9-b335-83e6b593273c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsActualToday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsActualToday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "c158c062-5f41-4066-9b71-07040d22ea1c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsRefDate",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsRefDate]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "a0711613-1ed5-4931-be77-c97fe1f71a3d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsHoliday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsHoliday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "ee3e6d01-2621-4a08-b25a-591318b53703",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsWeekday",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsWeekday]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "bf956c16-2355-499b-b503-b88553b552df",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisYear",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisYear]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "016d6200-8ae0-43de-85c0-fcf96e65fab3",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisMonth",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisMonth]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "51bcf435-6619-4d65-8dcf-b861329e2a51",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisQuarter",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisQuarter]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "3701707f-517d-4b04-a559-747ad90fa4ec",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "IsThisWeek",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[IsThisWeek]",
            "displayFolder": "7. Boolean Fields",
            "lineageTag": "19c5b6d5-141d-4298-b0db-d60212c2707e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays MTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "f66ce538-103c-476a-b5b7-fdf95a7d756e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays QTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Quarter Year (ie Q1 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "9d01d75f-4942-4b6a-9217-a702574aaf64",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays YTD",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "expression": [
              "VAR _Holidays =",
              "    CALCULATETABLE (",
              "        DISTINCT ('Date'[Date]),",
              "        'Date'[IsHoliday] <> TRUE",
              "    )",
              "VAR _WeekdayName = CALCULATE ( SELECTEDVALUE ( 'Date'[Weekday Short (i.e. Mon)] ) )",
              "VAR _WeekendDays = SWITCH (",
              "        _WeekdayName,",
              "        \"Sat\", 2,",
              "        \"Sun\", 3,",
              "        0",
              "    )",
              "VAR _WorkdaysMTD =",
              "    CALCULATE (",
              "        NETWORKDAYS (",
              "            CALCULATE (",
              "                MIN ('Date'[Date]),",
              "                ALLEXCEPT ('Date', 'Date'[Calendar Year (ie 2021)])",
              "            ),",
              "            CALCULATE (MAX ('Date'[Date]) - _WeekendDays),",
              "            1,",
              "            _Holidays",
              "        )",
              "    )",
              "        + 1",
              "RETURN",
              "    IF (_WorkdaysMTD < 1, 1, _WorkdaysMTD)"
            ],
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "439c9bb8-b5df-4014-92dd-384c1bcdaf5c",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Workdays MTD %",
            "dataType": "double",
            "isDataTypeInferred": true,
            "expression": [
              "DIVIDE (",
              "    'Date'[Workdays MTD],",
              "    /* Number of weekdays MTD for selected month */",
              "    CALCULATE (",
              "        [# Workdays in Selected Month],",
              "        ALLEXCEPT ( 'Date', 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ),",
              "    /* Total number of weekdays for selected month */",
              "    0",
              ")"
            ],
            "formatString": "0.00%",
            "displayFolder": "5. Weekday / Workday\\Workdays",
            "lineageTag": "cd816ac9-657f-4f27-ae68-ba35c84475f5",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Calendar Quarter (ie Q1)",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Calendar Quarter (ie Q1)]",
            "displayFolder": "2. Quarter",
            "lineageTag": "0808e9ee-085c-4934-9b9d-c647eba54590",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Date",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "-- Reference date for the latest date in the report",
                "-- Until when the business wants to see data in reports",
                "VAR _Refdate_Measure = [RefDate]",
                "VAR _Today = TODAY ( )",
                "",
                "-- Replace with \"Today\" if [RefDate] evaluates blank",
                "VAR _Refdate = IF ( ISBLANK ( _Refdate_Measure ), _Today, _Refdate_Measure )",
                "    VAR _RefYear        = YEAR ( _Refdate )",
                "    VAR _RefQuarter     = _RefYear * 100 + QUARTER(_Refdate)",
                "    VAR _RefMonth       = _RefYear * 100 + MONTH(_Refdate)",
                "    VAR _RefWeek_EU     = _RefYear * 100 + WEEKNUM(_Refdate, 2)",
                " ",
                "-- Earliest date in the model scope",
                "VAR _EarliestDate       = DATE ( YEAR ( MIN ( 'Orders'[Order Date] ) ) - 2, 1, 1 )",
                "VAR _EarliestDate_Safe  = MIN ( _EarliestDate, DATE ( YEAR ( _Today ) + 1, 1, 1 ) )",
                "",
                "-- Latest date in the model scope",
                "VAR _LatestDate_Safe    = DATE ( YEAR ( _Refdate ) + 2, 12, 1 )",
                "",
                "------------------------------------------",
                "-- Base calendar table",
                "VAR _Base_Calendar      = CALENDAR ( _EarliestDate_Safe, _LatestDate_Safe )",
                "------------------------------------------",
                "",
                "",
                "",
                "------------------------------------------",
                "VAR _IntermediateResult = ",
                "    ADDCOLUMNS ( _Base_Calendar,",
                "",
                "            ------------------------------------------",
                "        \"Calendar Year Number (ie 2021)\",           --|",
                "            YEAR ([Date]),                          --|-- Year",
                "                                                    --|",
                "        \"Calendar Year (ie 2021)\",                  --|",
                "            FORMAT ([Date], \"YYYY\"),                --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Quarter Year (ie Q1 2021)\",       --|",
                "            \"Q\" &                                   --|-- Quarter",
                "            CONVERT(QUARTER([Date]), STRING) &      --|",
                "            \" \" &                                   --|",
                "            CONVERT(YEAR([Date]), STRING),          --|",
                "                                                    --|",
                "        \"Calendar Year Quarter (ie 202101)\",        --|",
                "            YEAR([Date]) * 100 + QUARTER([Date]),   --|",
                "                                                    --| ",
                "        \"Calendar Quarter (ie Q1)\",                 --|",
                "            \"Q\" &                                   --|",
                "            CONVERT(QUARTER([Date]), STRING),       --|  ",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Calendar Month Year (ie Jan 21)\",          --|",
                "            FORMAT ( [Date], \"MMM YY\" ),            --|-- Month",
                "                                                    --|",
                "        \"Calendar Year Month (ie 202101)\",          --|",
                "            YEAR([Date]) * 100 + MONTH([Date]),     --|",
                "                                                    --|",
                "        \"Calendar Month (ie Jan)\",                  --|",
                "            FORMAT ( [Date], \"MMM\" ),               --|",
                "                                                    --|",
                "        \"Calendar Month # (ie 1)\",                  --|",
                "            MONTH ( [Date] ),                       --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Week EU (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 2 ),            --|-- Week",
                "                                                    --|",
                "        \"Calendar Week Number EU (ie 25)\",          --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number EU (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 2 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week US (ie WK25)\",               --|",
                "            \"WK\" & WEEKNUM( [Date], 1 ),            --|",
                "                                                    --|",
                "        \"Calendar Week Number US (ie 25)\",          --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Year Week Number US (ie 202125)\", --|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 1 ),                   --|",
                "                                                    --|",
                "        \"Calendar Week ISO (ie WK25)\",              --|",
                "            \"WK\" & WEEKNUM( [Date], 21 ),           --|",
                "                                                    --|",
                "        \"Calendar Week Number ISO (ie 25)\",         --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "                                                    --|",
                "        \"Calendar Year Week Number ISO (ie 202125)\",--|",
                "            YEAR ( [Date] ) * 100                   --|",
                "            +                                       --|",
                "            WEEKNUM( [Date], 21 ),                  --|",
                "            ------------------------------------------",
                "",
                "            ------------------------------------------",
                "        \"Weekday Short (i.e. Mon)\",                 --|",
                "            FORMAT ( [Date], \"DDD\" ),               --|-- Weekday",
                "                                                    --|",
                "        \"Weekday Name (i.e. Monday)\",               --|",
                "            FORMAT ( [Date], \"DDDD\" ),              --|",
                "                                                    --|",
                "        \"Weekday Number EU (i.e. 1)\",               --|",
                "            WEEKDAY ( [Date], 2 ),                  --|",
                "            ------------------------------------------",
                "            ",
                "            ------------------------------------------",
                "        \"Calendar Month Day (i.e. Jan 05)\",         --|",
                "            FORMAT ( [Date], \"MMM DD\" ),            --|-- Day",
                "                                                    --|",
                "        \"Calendar Month Day (i.e. 0105)\",           --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date]),                            --|",
                "                                                    --|",
                "        \"YYYYMMDD\",                                 --|",
                "            YEAR ( [Date] ) * 10000                 --|",
                "            +                                       --|",
                "            MONTH ( [Date] ) * 100                  --|",
                "            +                                       --|",
                "            DAY ( [Date] ),                         --|",
                "            ------------------------------------------",
                "",
                "",
                "            ------------------------------------------",
                "        \"IsDateInScope\",                            --|",
                "            [Date] <= _Refdate                      --|-- Boolean",
                "            &&                                      --|",
                "            YEAR([Date]) > YEAR(_EarliestDate),     --|",
                "                                                    --|",
                "        \"IsBeforeThisMonth\",                        --|",
                "            [Date] <= EOMONTH ( _Refdate, -1 ),     --|",
                "                                                    --|",
                "        \"IsLastMonth\",                              --|",
                "            [Date] <= EOMONTH ( _Refdate, 0 )       --|",
                "            &&                                      --|",
                "            [Date] > EOMONTH ( _Refdate, -1 ),      --|",
                "                                                    --|",
                "        \"IsYTD\",                                    --|",
                "            MONTH([Date])                           --|",
                "            <=                                      --|",
                "            MONTH(EOMONTH ( _Refdate, 0 )),         --|",
                "                                                    --|",
                "        \"IsActualToday\",                            --|",
                "            [Date] = _Today,                        --|",
                "                                                    --|",
                "        \"IsRefDate\",                                --|",
                "            [Date] = _Refdate,                      --|",
                "                                                    --|",
                "        \"IsHoliday\",                                --|",
                "            MONTH([Date]) * 100                     --|",
                "            +                                       --|",
                "            DAY([Date])                             --|",
                "                IN {0101, 0501, 1111, 1225},        --|",
                "                                                    --|",
                "        \"IsWeekday\",                                --|",
                "            WEEKDAY([Date], 2)                      --|",
                "                IN {1, 2, 3, 4, 5})                 --|",
                "            ------------------------------------------",
                "",
                "VAR _Result = ",
                "    ",
                "            --------------------------------------------",
                "    ADDCOLUMNS (                                      --|",
                "        _IntermediateResult,                          --|-- Boolean #2",
                "        \"IsThisYear\",                                 --|",
                "            [Calendar Year Number (ie 2021)]          --|",
                "                = _RefYear,                           --|",
                "                                                      --|",
                "        \"IsThisMonth\",                                --|",
                "            [Calendar Year Month (ie 202101)]         --|",
                "                = _RefMonth,                          --|",
                "                                                      --|",
                "        \"IsThisQuarter\",                              --|",
                "            [Calendar Year Quarter (ie 202101)]       --|",
                "                = _RefQuarter,                        --|",
                "                                                      --|",
                "        \"IsThisWeek\",                                 --|",
                "            [Calendar Year Week Number EU (ie 202125)]--|",
                "                = _RefWeek_EU                         --|",
                "    )                                                 --|",
                "            --------------------------------------------",
                "            ",
                "RETURN ",
                "    _Result"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "# Workdays MTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays MTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "4b0555ab-6912-4d3c-b613-0d2d542a6965"
          },
          {
            "name": "# Workdays QTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays QTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "a07fb670-6765-4b8b-91da-3170765e8e94"
          },
          {
            "name": "# Workdays YTD",
            "expression": [
              "CALCULATE(",
              "    MAX( 'Date'[Workdays YTD] ),",
              "    'Date'[IsDateInScope] = TRUE",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "0a27905d-9841-4cda-9976-ec65d16821d4"
          },
          {
            "name": "# Workdays in Selected Month",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays MTD]),",
              "        VALUES ('Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "55924c9b-cb78-47d3-824e-92cb1a525706"
          },
          {
            "name": "# Workdays in Selected Quarter",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays QTD]),",
              "        VALUES ('Date'[Calendar Quarter Year (ie Q1 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "84ccfbbd-bf7b-43b6-8e35-df7a54d0d9e7"
          },
          {
            "name": "# Workdays in Selected Year",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    CALCULATE (",
              "        MAX ('Date'[Workdays YTD]),",
              "        VALUES ('Date'[Calendar Year (ie 2021)])",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "a5eb1c3f-f13e-4d86-9fb2-d7bbb3fc3cf6"
          },
          {
            "name": "% Workdays MTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Month Year (ie Jan 21)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays MTD], [# Workdays in Selected Month]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "68e3c8f6-6e44-4191-9e86-90afb7ddf261"
          },
          {
            "name": "% Workdays QTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Quarter Year (ie Q1 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays QTD], [# Workdays in Selected Quarter]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "7acd41b3-fc3c-4e8b-809c-a5edc09bc853"
          },
          {
            "name": "% Workdays YTD",
            "expression": [
              "IF (",
              "    HASONEVALUE ('Date'[Calendar Year (ie 2021)]),",
              "    MROUND (",
              "        DIVIDE ([# Workdays YTD], [# Workdays in Selected Year]),",
              "        0.01",
              "    )",
              ")"
            ],
            "formatString": "#,##0%",
            "displayFolder": "5. Weekday / Workday\\Measures\\# Workdays",
            "lineageTag": "74c83d7c-2d91-4dc3-87f3-d129a2b220ae"
          },
          {
            "name": "RefDate",
            "expression": "CALCULATE ( MAX ( 'Invoices'[Billing Date] ), REMOVEFILTERS ( ) )",
            "isHidden": true,
            "displayFolder": "Measures",
            "lineageTag": "75027a89-68f7-4e3f-9d0b-abbb14b92094"
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "1748d90b-b004-4b0d-afa9-77214627ce0f",
            "levels": [
              {
                "name": "Calendar Year (ie 2021)",
                "ordinal": 0,
                "column": "Calendar Year (ie 2021)",
                "lineageTag": "ec183b08-c5d1-42ca-a087-e4dbfbcc9349"
              },
              {
                "name": "Calendar Quarter (ie Q1)",
                "ordinal": 1,
                "column": "Calendar Quarter (ie Q1)",
                "lineageTag": "54cf79cd-0493-4918-9750-c334dcfe4eb5"
              },
              {
                "name": "Calendar Month (ie Jan)",
                "ordinal": 2,
                "column": "Calendar Month (ie Jan)",
                "lineageTag": "7ab92588-0b9b-4b03-a4ee-a556e9b8cc1e"
              },
              {
                "name": "Calendar Week EU (ie WK25)",
                "ordinal": 3,
                "column": "Calendar Week EU (ie WK25)",
                "lineageTag": "51e5883b-9124-4ff7-9600-954ef91e6f80"
              },
              {
                "name": "Weekday Short (i.e. Mon)",
                "ordinal": 4,
                "column": "Weekday Short (i.e. Mon)",
                "lineageTag": "5aef54bd-34f0-47c9-b70c-21e5cf59e625"
              },
              {
                "name": "Date",
                "ordinal": 5,
                "column": "Date",
                "lineageTag": "cb95b6f4-85ff-4121-bb82-3e18125ac0db"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "On-Time Delivery",
        "lineageTag": "fa6fb917-28ce-4d34-97ad-9fff4d086e1c",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "Invoices[OTD Indicator]",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\2. Keys",
            "lineageTag": "705b4fb2-c9bb-4915-8cb4-b7dac943d875",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Status",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Status]",
            "sortByColumn": "OTD Sort Order",
            "displayFolder": "Columns\\1. OTD",
            "lineageTag": "7f04b315-56ac-43ca-ad33-ff6229fe4e8c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "OTD Sort Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[OTD Sort Order]",
            "displayFolder": "Columns\\3. Ordinal",
            "lineageTag": "7a38eab2-031b-4605-9352-d562e2c842c7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "On-Time Delivery",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "ADDCOLUMNS (",
                "    FILTER (",
                "        DISTINCT ('Invoices'[OTD Indicator]),",
                "        NOT ISBLANK ('Invoices'[OTD Indicator])",
                "    ),",
                "    \"OTD Status\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, \"On Time\",",
                "            \"Late\"",
                "        ),",
                "    \"OTD Sort Order\",",
                "        SWITCH (",
                "            TRUE (),",
                "            'Invoices'[OTD Indicator] = TRUE, 1,",
                "            2",
                "        )",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "OTD % (Lines)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Lines)]",
              "VAR _Total = CALCULATE (",
              "    [Invoice Lines],",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "3. Lines",
            "lineageTag": "ac99485b-fc61-474e-a30e-d0889efce03f",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "OTD % (Quantity)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Quantity)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Quantity],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "2. Quantity",
            "lineageTag": "29fcb593-54b0-4061-ae46-2683f72fe75a",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "OTD % (Value)",
            "expression": [
              "",
              "VAR _OnTime = [OTD (Value)]",
              "VAR _Total = ",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Group] = \"Invoice\"",
              "    )",
              "RETURN",
              "",
              "DIVIDE ( _OnTime, _Total )"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value",
            "lineageTag": "8e11165d-306e-4e59-b549-fc1cdf4b080f",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "OTD (Lines)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Invoice Lines],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "e117a7f4-cf4b-4ec6-80bb-a1cc7970da51",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "OTD (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Quantity],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "7018a9c2-01fc-4f2b-8312-80c684c99e25",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "OTD (Value)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Invoice Value],",
              "    'On-Time Delivery'[OTD Indicator] = TRUE,",
              "    'Invoice Document Type'[Group] = \"Invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value",
            "lineageTag": "c6c32721-002f-444e-8c7a-dadc8ea6c9c6",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_InPerspective",
            "value": "[\"No Measure Selection\"]"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Orders",
        "lineageTag": "85791d56-7571-4870-ac91-2e53ef43e591",
        "columns": [
          {
            "name": "Sales Order Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales_order_document_number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "163858ac-fb24-4133-adf0-b14dab3c3f36",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Date",
            "dataType": "dateTime",
            "description": "There is a bug with the \"Order Date\" field where it is blank. This will take me a bit of time to resolve. - Kurt",
            "isHidden": true,
            "sourceColumn": "order_date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "cca4d6f0-d0b7-47ed-a7c9-8f5aa2a98962",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "customer_key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "9496ba22-b180-436d-bcdc-9a1a74722321",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Order Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "sales_order_document_line_item_number",
            "displayFolder": "Columns\\2. Document Fields",
            "lineageTag": "3160dd83-6600-4ee8-9352-1f63bf72df1e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_key",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "35a4cdf8-ef86-4d1f-b389-9f9cf1567188",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "billing_date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "0dfc4547-ab35-4e31-b8c9-e1ac1f97746e",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "0b2be8fb-09ab-4abc-a26a-c2b736c312b4",
                "defaultHierarchy": {
                  "table": "LocalDateTable_fca581ec-8430-42e1-9f91-795770007388",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ship_date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "9792bfa7-8c8a-434d-8cad-919bc7f9ecb8",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "1c1cd679-d959-4344-a9d3-e592ae111e42",
                "defaultHierarchy": {
                  "table": "LocalDateTable_4ad7e833-9e3a-4bd3-9873-535c2d4d4285",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Request Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "request_goods_receipt_date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "1d86455e-0786-4044-a863-46c0f76d2528",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Confirm Goods Receipt Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "confirm_goods_receipt_date",
            "formatString": "Long Date",
            "displayFolder": "Columns\\3. Keys\\Dates",
            "lineageTag": "76a947d9-cf88-49b9-945e-9034a3c2ce17",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "0cb7c41d-deae-4c82-b01a-5dbeb9ed834b",
                "defaultHierarchy": {
                  "table": "LocalDateTable_579bd8be-fc8b-4a18-a637-ab748ff358e0",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sales_order_document_type_code",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "9f790c89-4a50-4f00-9729-4e8219f5ebb4",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Sales Order Document Line Item Status",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sales_order_document_line_item_status",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "cd22a20a-de0e-411c-8c1a-bf9806d7dcfe",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "local_currency",
            "displayFolder": "Columns\\3. Keys",
            "lineageTag": "2022bec1-9cd4-4ac9-993e-9cc85a29646c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Order Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "net_order_value",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "ce7d5f32-b1d9-4c34-b778-963c65d7931d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Net Order Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "net_order_quantity",
            "displayFolder": "Columns\\1. Facts",
            "lineageTag": "38503552-7ce2-412c-bb5e-b56bda227eb0",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Orders",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"orders\"]}[Data],",
                "    #\"Select Columns\" = Table.RemoveColumns ( Data, \"dwcreateddate\" ),",
                "    #\"Added Custom\" = Table.AddColumn(#\"Select Columns\", \"RandomDays\", each Number.RandomBetween(7, 90), Int64.Type),",
                "    #\"Changed Type\" = Table.TransformColumnTypes(#\"Added Custom\",{{\"RandomDays\", Int64.Type}}),",
                "    #\"Added Custom1\" = Table.AddColumn(#\"Changed Type\", \"Fixed Order Date\", each if [order_date] = null then Date.AddDays([request_goods_receipt_date], -[RandomDays]) else [order_date]),",
                "    #\"Changed Type1\" = Table.TransformColumnTypes(#\"Added Custom1\",{{\"Fixed Order Date\", type date}}),",
                "    #\"Removed Columns\" = Table.RemoveColumns(#\"Changed Type1\",{\"order_date\", \"RandomDays\"}),",
                "    #\"Renamed Columns\" = Table.RenameColumns(#\"Removed Columns\",{{\"Fixed Order Date\", \"order_date\"}})",
                "in",
                "    #\"Renamed Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Net Orders",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Value],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "4b34a3e0-ef13-4b57-8312-568cc0f1083c",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Net Orders (Quantity)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE (",
              "    [Total Net Order Quantity],",
              "    'Order Document Type'[Group]",
              "        <> \"Cancellation\"",
              ") "
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity",
            "lineageTag": "735e22bf-4e02-4887-a597-e1dfcdd34aad",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Net Orders 1YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\ii. 1YP",
            "lineageTag": "ff93215e-8b82-41cd-bfd8-a31541d6dc84",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Net Orders 2YP",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "CALCULATE ( [Net Orders], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\iii. 2YP",
            "lineageTag": "4ace6187-dbc5-4132-a957-a2c2d78d7c0e",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Total Net Order Value",
            "description": "The net order value is the sum of all order intake including cancellations (also known as Gross Orders)",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "",
              "    -- Convert to common currency (WAT)",
              "    SUMX (",
              "        'Orders',",
              "        'Orders'[Net Order Value]",
              "            / RELATED ('Budget Rate'[Rate])",
              "    )",
              "",
              "        -- Convert to selected currency",
              "        * _RATE "
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\i. Total",
            "lineageTag": "7bb01c04-5462-4841-93f9-e0d850e8c1cf",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Order Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Orders' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "5324832f-97a5-437f-9604-d6dca47246de",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Total Net Order Quantity",
            "expression": [
              "",
              "SUM ( 'Orders'[Net Order Quantity] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "2. Quantity",
            "lineageTag": "880c9c1a-af07-4b22-b4e8-28a116f6a170",
            "annotations": [
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_InPerspective",
            "value": "[\"No Measure Selection\"]"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"0b2be8fb-09ab-4abc-a26a-c2b736c312b4\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Billing Date\",",
              "    \"toTable\": \"LocalDateTable_fca581ec-8430-42e1-9f91-795770007388\",",
              "    \"toColumn\": \"Date\",",
              "    \"joinOnDateBehavior\": \"datePartOnly\"",
              "  },",
              "  {",
              "    \"name\": \"0cb7c41d-deae-4c82-b01a-5dbeb9ed834b\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Confirm Goods Receipt Date\",",
              "    \"toTable\": \"LocalDateTable_579bd8be-fc8b-4a18-a637-ab748ff358e0\",",
              "    \"toColumn\": \"Date\",",
              "    \"joinOnDateBehavior\": \"datePartOnly\"",
              "  },",
              "  {",
              "    \"name\": \"c97e9cf2-9441-4f5a-8609-f53e6a3a7571\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Customer Key\",",
              "    \"toTable\": \"Customers\",",
              "    \"toColumn\": \"Customer Key\"",
              "  },",
              "  {",
              "    \"name\": \"d3b21caa-eed5-4a2b-85a1-92a599807a8a\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Local Currency\",",
              "    \"toTable\": \"Budget Rate\",",
              "    \"toColumn\": \"From Currency\"",
              "  },",
              "  {",
              "    \"name\": \"1ae64f29-da13-4294-bde5-4320a84af2c1\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Order Date\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\"",
              "  },",
              "  {",
              "    \"name\": \"7664202a-acbb-4942-a83e-60eb3b8537f9\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Product Key\",",
              "    \"toTable\": \"Products\",",
              "    \"toColumn\": \"Product Key\"",
              "  },",
              "  {",
              "    \"name\": \"34c786fb-4d8e-41d3-a86c-fd83e71d8cc1\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Request Goods Receipt Date\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\",",
              "    \"isActive\": false",
              "  },",
              "  {",
              "    \"name\": \"6ef67eab-1e07-436d-a358-6197853f0064\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Sales Order Document Line Item Status\",",
              "    \"toTable\": \"Order Status\",",
              "    \"toColumn\": \"Order Status Code\"",
              "  },",
              "  {",
              "    \"name\": \"5c8f76eb-7c06-4ed5-bdc2-6368b1f0ef0a\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Sales Order Document Type Code\",",
              "    \"toTable\": \"Order Document Type\",",
              "    \"toColumn\": \"Sales Order Document Type Code\"",
              "  },",
              "  {",
              "    \"name\": \"1c1cd679-d959-4344-a9d3-e592ae111e42\",",
              "    \"fromTable\": \"Orders\",",
              "    \"fromColumn\": \"Ship Date\",",
              "    \"toTable\": \"LocalDateTable_4ad7e833-9e3a-4bd3-9873-535c2d4d4285\",",
              "    \"toColumn\": \"Date\",",
              "    \"joinOnDateBehavior\": \"datePartOnly\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Forecast",
        "lineageTag": "f44175ec-6e73-4cc5-93db-4febba622528",
        "columns": [
          {
            "name": "Forecast Month",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "forecast_month",
            "formatString": "Long Date",
            "displayFolder": "2. Keys",
            "lineageTag": "1c521f45-cb4d-444a-94da-8684fd62cf37",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Region Territory",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "region_territory",
            "displayFolder": "2. Keys",
            "lineageTag": "864f2700-e020-4b14-98ce-7e5b4154275d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Type",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "product_type",
            "displayFolder": "2. Keys",
            "lineageTag": "a3e38e2f-113c-4b33-97bd-ba68256feaff",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Forecast (EUR)",
            "dataType": "decimal",
            "isHidden": true,
            "sourceColumn": "forecast_eur",
            "displayFolder": "1. Facts",
            "lineageTag": "68c093b8-8ce0-44cc-ab2c-213dcc900077",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Forecast",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"forecast\"]}[Data],",
                "    #\"Select Columns\" = Table.SelectColumns ( Data, {\"forecast_month\", \"forecast_eur\", \"region_territory\", \"product_type\"})",
                "in",
                "    #\"Select Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Forecast MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CURRENT_MONTH_VALUE =",
              "    CALCULATE (",
              "        [Forecast],",
              "        ALL ( 'Date' ),",
              "        VALUES ( 'Date'[Calendar Month Year (ie Jan 21)] )",
              "    ) ",
              "",
              "-- Computes rate at which Forecast increases through the month",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS_MTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _CURRENT_MONTH_PERC_WORKDAYS =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "",
              "VAR _PERIOD =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HASONEMONTH =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HASONEMONTH",
              "            && _PERIOD = \"Full Period\",",
              "        _CURRENT_MONTH_PERC_WORKDAYS",
              "            * _CURRENT_MONTH_VALUE,",
              "",
              "        IF (",
              "            _HASONEMONTH,",
              "            _CURRENT_MONTH_PERC_WORKDAYS_MTD",
              "                * _CURRENT_MONTH_VALUE",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "59b4471b-3cce-43f5-ab24-5555faf2bd37"
          },
          {
            "name": "Forecast QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "b016de82-c11c-4231-a206-c2d02568aa7f"
          },
          {
            "name": "Forecast QTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast QTD]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "5fc59186-997c-4890-a18b-97e7662b0667"
          },
          {
            "name": "Forecast QTD vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Forecast QTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\iii. QTD",
            "lineageTag": "86a370f9-61ff-46d1-a054-614a604cf185"
          },
          {
            "name": "Forecast YTD",
            "expression": [
              "",
              "VAR _DATES_YTD =",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Forecast MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Forecast], _DATES_YTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "8db40d35-8818-45fb-b008-f39e79ba3084"
          },
          {
            "name": "Forecast YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast YTD]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "8d1f9942-e438-4edf-99fb-a244511fb73f"
          },
          {
            "name": "Forecast YTD vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Forecast YTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\iv. YTD",
            "lineageTag": "1a4e0d88-e751-4350-bf75-3cb5aab8e7c1"
          },
          {
            "name": "Total Forecast",
            "expression": [
              "",
              "    VAR _SelectedRate = MAX ( 'Exchange Rate'[Rate] )",
              "RETURN",
              "    SUM ( 'Forecast'[Forecast (EUR)] ) * _SelectedRate"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "66dd4eca-8cd0-492a-b93a-0bb91c4f6b04"
          },
          {
            "name": "Forecast",
            "expression": [
              "",
              "IF.EAGER(",
              "    HASONEVALUE( '2) Selected Unit'[Select a Unit] )",
              "        && ",
              "    HASONEVALUE( 'Exchange Rate'[From Currency] ),",
              "",
              "    VAR _SELECTED_CURRENCY = ",
              "        SELECTEDVALUE( 'Exchange Rate'[From Currency] )",
              "",
              "    VAR _SELECTED_RATE_TYPE = ",
              "        SELECTEDVALUE( '2) Selected Unit'[Select a Unit] )",
              "    ",
              "    VAR _SELECTED_BUDGET_RATE =",
              "        MAX( 'Exchange Rate'[Rate] )",
              "        ",
              "    VAR _SELECTED_MONTHLY_RATE =",
              "        ADDCOLUMNS(",
              "            SUMMARIZE(",
              "                'Exchange Rate',",
              "                'Date'[Calendar Month Year (ie Jan 21)]",
              "            ),",
              "            \"Curr\", ",
              "            CALCULATE ( ",
              "                MAX( 'Exchange Rate'[Rate] ) ",
              "            )",
              "        )",
              "        ",
              "    RETURN",
              "",
              "    IF(",
              "        _SELECTED_RATE_TYPE = \"Value (Budget Rate)\",",
              "        SUM ( 'Forecast'[Forecast (EUR)]) ",
              "        * ",
              "        _SELECTED_BUDGET_RATE,",
              "        ",
              "        IF(",
              "            _SELECTED_RATE_TYPE = \"Value (Monthly Rate)\",",
              "            SUMX(",
              "                _SELECTED_MONTHLY_RATE,",
              "                CALCULATE( ",
              "                    SUM ( 'Forecast'[Forecast (EUR)])",
              "                )",
              "                * [Curr]",
              "            )",
              "        )",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "a6383680-00ad-44a2-a972-afd4378179ad"
          },
          {
            "name": "Forecast MTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast MTD]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "852154a6-c9a0-46bc-bc2f-f27301426027"
          },
          {
            "name": "Forecast MTD vs. Gross Sales ()",
            "expression": [
              "",
              "[MTD Gross Sales] - [Forecast MTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\ii. MTD",
            "lineageTag": "32e7cb6e-42b1-4549-ac5a-4dcd6d678b1c"
          },
          {
            "name": "Forecast vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Forecast]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "0f955ab8-28e0-4ac4-b335-23c88440db41"
          },
          {
            "name": "Forecast vs. Gross Sales ()",
            "expression": [
              "",
              "[Gross Sales] - [Forecast]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "Measures\\i. Total",
            "lineageTag": "68c5bb1f-fa70-42a1-8f9c-34f95ed0950b"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"3795aac2-e6ba-48a7-9722-b7dd7af7b762\",",
              "    \"fromTable\": \"Forecast\",",
              "    \"fromColumn\": \"Forecast Month\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\"",
              "  },",
              "  {",
              "    \"name\": \"599b10ac-8bcb-4550-b452-56d8954b2a35\",",
              "    \"toCardinality\": \"many\",",
              "    \"fromTable\": \"Forecast\",",
              "    \"fromColumn\": \"Product Type\",",
              "    \"toTable\": \"Products\",",
              "    \"toColumn\": \"Type\"",
              "  },",
              "  {",
              "    \"name\": \"703b86a0-df9c-47d6-82e4-7c457de95971\",",
              "    \"toCardinality\": \"many\",",
              "    \"fromTable\": \"Forecast\",",
              "    \"fromColumn\": \"Region Territory\",",
              "    \"toTable\": \"Regions\",",
              "    \"toColumn\": \"Territory\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "Order Document Type",
        "lineageTag": "8f2bc030-d173-42c1-9fc4-26bdc4efcbca",
        "columns": [
          {
            "name": "Sales Order Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "sales_order_document_type_code",
            "displayFolder": "2. Keys",
            "lineageTag": "3370b74d-45ca-4aee-9dfa-3578ad1b476f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Text",
            "dataType": "string",
            "sourceColumn": "text",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "dd298654-70aa-4357-a16e-7cf6eebe5e0f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Doc. Type Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "doc_type_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "f010755d-dc7c-4add-8bfd-a679f33ef0e5",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Group",
            "dataType": "string",
            "sourceColumn": "group",
            "displayFolder": "1. Order Doc. Type",
            "lineageTag": "f6aaeee2-b14c-47b1-9658-cdf317f44195",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Group Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "group_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "1ce7a8e9-fe9f-4c9e-b106-4464b5c9419d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Order Document Type",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"order_doc_type\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_InPerspective",
            "value": "[\"No Measure Selection\"]"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Order Status",
        "lineageTag": "12d7ff4e-91a1-4a12-bdaa-8138019fc2d0",
        "columns": [
          {
            "name": "Order Status Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "order_status_code",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "2. Keys",
            "lineageTag": "a100afe0-dcbd-4d7c-99d8-a75db4331ab8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Text",
            "dataType": "string",
            "sourceColumn": "order_status_text",
            "sortByColumn": "Order Status Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "cac50369-1d71-44df-9a3a-852a8da9d08f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Order Status Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "order_status_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "d641dd45-15cd-45fa-9d89-069004a9392c",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Order Status Group",
            "dataType": "string",
            "sourceColumn": "order_status_group",
            "sortByColumn": "Order Status Grouping Ordinal",
            "displayFolder": "1. Order Status",
            "lineageTag": "f34f646d-9d85-473b-be9a-0fd08df3cb97",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "TabularEditor_InPerspective",
                "value": "[\"No Measure Selection\"]"
              }
            ]
          },
          {
            "name": "Order Status Grouping Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "order_status_grouping_ordinal",
            "displayFolder": "3. Ordinal",
            "lineageTag": "b6d344fc-1b71-4459-90fc-67a8d9d92e9f",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Order Status",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"order_status\"]}[Data]",
                "in",
                "    Data"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_InPerspective",
            "value": "[\"No Measure Selection\"]"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "1) Selected Metric",
        "description": "It lets you select a Metric.",
        "lineageTag": "31535870-007d-4636-8348-2f06b750951d",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "734455ee-3587-4f7b-bdd9-34f849747e7d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Measure",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Measure]",
            "sortByColumn": "Order",
            "lineageTag": "16dc4342-12d1-4da6-89d8-63ba7be01ddf",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "1) Selected Metric",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z01CG2 - Value (Budget Rate)',",
                "        \"Select a Measure\", 'Z01CG2 - Value (Budget Rate)'[Measure],",
                "        \"Order\", 'Z01CG2 - Value (Budget Rate)'[Ordinal]",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Selection"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "2) Selected Unit",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Unit."
        ],
        "lineageTag": "8db601bc-67fe-4a66-8b3e-5751e675a807",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "6b618add-eff1-447d-b625-90bab65824d7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Unit",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Unit]",
            "sortByColumn": "Order",
            "lineageTag": "01083816-a18e-4ea5-9fba-28c9b19b5f74",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "2) Selected Unit",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS(",
                "    'Z02CG1 - Unit',",
                "        \"Select a Unit\", 'Z02CG1 - Unit'[Unit],",
                "        \"Order\", 'Z02CG1 - Unit'[Ordinal]",
                ") "
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Selection"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "3) Selected Target",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Target."
        ],
        "lineageTag": "faedb0d7-81a5-4a5b-aa77-569ccb6f80d4",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD Slicer",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD Slicer]",
            "sortByColumn": "Order",
            "lineageTag": "02184b60-9463-42cc-9353-3076dcfd57d1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "lineageTag": "6549343f-cc13-417c-a7ec-4052e86c701d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Select a Target",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Select a Target]",
            "sortByColumn": "Order",
            "lineageTag": "d66a7492-deb6-4fc5-8bf4-9ea15c424cfc",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "3) Selected Target",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    'Z03CG1 - Sales Target',",
                "    \"Select a Target\", 'Z03CG1 - Sales Target'[Target],",
                "    \"Order\", 'Z03CG1 - Sales Target'[Ordinal],",
                "    \"MTD Slicer\",",
                "        VAR _TARGET = 'Z03CG1 - Sales Target'[Target]",
                "        RETURN",
                "            SWITCH (",
                "                TRUE (),",
                "                _TARGET = \"Budget\",         \"Gross Sales MTD vs. Budget\",",
                "                _TARGET = \"Forecast\",       \"Gross Sales MTD vs. FCST\",",
                "                _TARGET = \"1 Year Prior\",   \"Gross Sales MTD vs. 1YP\",",
                "                _TARGET = \"2 Years Prior\",  \"Gross Sales MTD vs. 2YP\"",
                "            )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Selection"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "4) Selected Period",
        "description": [
          "This is a disconnected table for Measure Selection.",
          "It lets you select a Period"
        ],
        "lineageTag": "d0747f9f-bab0-419e-87fb-7ae01f97a523",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "MTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[MTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "c9ee146b-ada4-4f64-b3ec-5367e8e35c2e",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Order",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Order]",
            "displayFolder": "Columns\\1. Order",
            "lineageTag": "28ecb9f2-1504-4a33-9da4-5bcfcc9c3317",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "Period",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "sourceColumn": "[Period]",
            "sortByColumn": "Order",
            "lineageTag": "1f98320e-9b80-4c14-abbd-50b713f55446",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "QTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[QTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "32c56d15-bb0d-4567-b661-75ae39b13044",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "type": "calculatedTableColumn",
            "name": "YTD",
            "dataType": "string",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[YTD]",
            "sortByColumn": "Order",
            "displayFolder": "Columns\\0. Select a Period",
            "lineageTag": "25f552c2-f3ce-428e-a61c-dd66630c4bef",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "4) Selected Period",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "UNION (",
                "    ROW (",
                "        \"Period\", {\"Full Period\"},",
                "        \"Order\", {0},",
                "        \"MTD\", {\"Full Month\"},",
                "        \"QTD\", {\"Full Quarter\"},",
                "        \"YTD\", {\"Full Year\"}",
                "    ),",
                "    ROW (",
                "        \"Period\", {\"Period-to-Date\"},",
                "        \"Order\", {1},",
                "        \"MTD\", {\"MTD\"},",
                "        \"QTD\", {\"QTD\"},",
                "        \"YTD\", {\"YTD\"}",
                "    )",
                ")"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_TableGroup",
            "value": "Measure Selection"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z01CG1 - Quantity",
        "isHidden": true,
        "lineageTag": "b6f842c2-82d7-4bb1-9831-491a409aec9b",
        "calculationGroup": {
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 0
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders (Quantity)]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Quantity]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "5ac136e4-db61-4d9b-a51a-6f8c4d835f03",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "9156d93a-97c0-4799-a6a8-8c77088cf932",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z01CG2 - Value (Budget Rate)",
        "isHidden": true,
        "lineageTag": "af94bf00-20d7-4871-a2d6-dbcc1e73ad88",
        "calculationGroup": {
          "precedence": 1,
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Gross Sales]"
              ],
              "ordinal": 0
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 1
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Total Net Invoice Value]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "[Total Net Invoice COGS]"
              ],
              "ordinal": 3
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "[Total Delivery Cost]"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "[Total Freight Surcharge]"
              ],
              "ordinal": 5
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "[Total Taxes & Commercial Fees]"
              ],
              "ordinal": 6
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "[Total Overdue Payment Penalties]"
              ],
              "ordinal": 7
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "[Total Late Delivery Penalties]"
              ],
              "ordinal": 8
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "70c83fac-2574-42ac-ab25-2c2e3e703ea8",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "8e6c5fc1-c509-40cd-887d-e7840bbc41a4",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z01CG4 - Lines",
        "isHidden": true,
        "lineageTag": "d0e1c818-c035-4cd9-a3ac-7efb39b1e1a7",
        "calculationGroup": {
          "precedence": 3,
          "calculationItems": [
            {
              "name": "Gross Sales",
              "expression": [
                "",
                "[Invoice Lines]"
              ],
              "ordinal": 0
            },
            {
              "name": "Net Sales",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 1
            },
            {
              "name": "Orders",
              "expression": [
                "",
                "[Net Orders]"
              ],
              "ordinal": 2
            },
            {
              "name": "Invoices",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 3
            },
            {
              "name": "Invoice Cost",
              "description": "The Net Invoice Cost is",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 4
            },
            {
              "name": "Delivery Cost",
              "description": "The cost of the delivery only",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 5
            },
            {
              "name": "Delivery Surcharge",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 6
            },
            {
              "name": "Taxes",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 7
            },
            {
              "name": "Overdue Payment Penalties",
              "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 8
            },
            {
              "name": "Late Delivery Penalties",
              "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 9
            }
          ]
        },
        "columns": [
          {
            "name": "Measure",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "bec81eaa-021e-4d70-a8f3-9b1bf2851d93",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "f246d2a1-6ef4-457c-9953-66884a9f7f4b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z02CG1 - Unit",
        "isHidden": true,
        "lineageTag": "516121f5-e575-4aef-9915-f766b1aa72e0",
        "calculationGroup": {
          "precedence": 2,
          "calculationItems": [
            {
              "name": "Value (Budget Rate)",
              "expression": [
                "",
                "[Value]"
              ],
              "ordinal": 0
            },
            {
              "name": "Quantity",
              "expression": [
                "",
                "[Quantity]"
              ],
              "ordinal": 1
            },
            {
              "name": "Lines",
              "expression": [
                "",
                "[Lines]"
              ],
              "ordinal": 2
            }
          ]
        },
        "columns": [
          {
            "name": "Unit",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "2d7160af-d5c1-4676-b064-a01f4f8cd651",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "c3a035d1-b935-4d28-9654-7b1f0468e8e2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z03CG1 - Sales Target",
        "isHidden": true,
        "lineageTag": "04c41956-f84c-47b8-a9d6-c2264d42e1e9",
        "calculationGroup": {
          "precedence": 6,
          "calculationItems": [
            {
              "name": "Budget",
              "expression": [
                "",
                "[Total Budget]"
              ],
              "ordinal": 0
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "[Forecast]"
              ],
              "ordinal": 1
            },
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Gross Sales 1YP (Selected Unit)]"
              ],
              "ordinal": 2
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Gross Sales 2YP (Selected Unit)]"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "3f903a26-3226-403d-a33a-4ec211020c27",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "e9744b72-7acd-442c-97f8-64454ba19c7f",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z03CG2 - Orders Target",
        "isHidden": true,
        "lineageTag": "03aebfe4-55ef-4d5c-9ffb-173716934b26",
        "calculationGroup": {
          "precedence": 7,
          "calculationItems": [
            {
              "name": "1 Year Prior",
              "expression": [
                "",
                "[Net Orders 1YP]"
              ],
              "ordinal": 0
            },
            {
              "name": "2 Years Prior",
              "expression": [
                "",
                "[Net Orders 2YP]"
              ],
              "ordinal": 1
            },
            {
              "name": "Budget",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 2
            },
            {
              "name": "Forecast",
              "expression": [
                "",
                "BLANK()"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Target",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "d301dc31-afbe-4e15-8ffb-96932ff69684",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "6f45bbff-0b86-4c81-bef2-d404cc2f982d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Z04CG1 - Time Intelligence",
        "isHidden": true,
        "lineageTag": "06d80604-395e-436b-8758-bf365cf9f944",
        "calculationGroup": {
          "precedence": 4,
          "calculationItems": [
            {
              "name": "Daily",
              "expression": [
                "",
                "SELECTEDMEASURE()"
              ],
              "ordinal": 0
            },
            {
              "name": "MTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESMTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 1
            },
            {
              "name": "QTD",
              "expression": [
                "",
                "CALCULATE (",
                "    SELECTEDMEASURE (), ",
                "    CALCULATETABLE (",
                "        DATESQTD ('Date'[Date]),",
                "        'Date'[IsDateInScope]",
                "    )",
                ")"
              ],
              "ordinal": 2
            },
            {
              "name": "YTD",
              "expression": [
                "",
                "VAR _YTD =",
                "    CALCULATE (",
                "        SELECTEDMEASURE (),",
                "        CALCULATETABLE (",
                "            DATESYTD ('Date'[Date]),",
                "            'Date'[IsDateInScope]",
                "        )",
                "    )",
                "VAR _FULL_YTD =",
                "    CALCULATE (SELECTEDMEASURE (), DATESYTD ('Date'[Date]))",
                "RETURN",
                "    IF (",
                "        SEARCH (\"Actuals\", SELECTEDMEASURENAME (), , 999) <> 999,",
                "        _YTD,",
                "        _FULL_YTD",
                "    )"
              ],
              "ordinal": 3
            }
          ]
        },
        "columns": [
          {
            "name": "Aggregation",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "Name",
            "sortByColumn": "Ordinal",
            "lineageTag": "b26f8f5f-3bdc-41ef-8b64-edef27cccd5d",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ordinal",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "Ordinal",
            "lineageTag": "a9337a43-d38a-4585-a86a-94689ee5a05e",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Partition",
            "mode": "import",
            "source": {
              "type": "calculationGroup"
            }
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "__Measures",
        "description": [
          "Everything in this Table Requires Measure Selection",
          "1. Select a Metric",
          "2. Select a Unit",
          "3. Select a Target",
          "4. Select a Period",
          "5. Select a Currency (from 'Exchange Rate')",
          "6. Select a Year and/or Month from 'Date'",
          ""
        ],
        "isHidden": true,
        "lineageTag": "c1f26e78-ea20-4757-b4d4-89e2237d2584",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "lineageTag": "721b2ff3-ac1f-41ae-b13b-e28a49828598",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "__Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Actuals",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('2) Selected Unit'[Select a Unit]),",
              "        'Z02CG1 - Unit'[Unit]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "0a6cef3d-e27e-4055-a718-50e2e16947d2"
          },
          {
            "name": "Actuals MTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Actuals",
            "lineageTag": "ea39866d-9863-418f-884b-661ffb7be937"
          },
          {
            "name": "Actuals QTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Actuals",
            "lineageTag": "75670b7b-105c-4bdd-83a1-1ead1595f242"
          },
          {
            "name": "Actuals YTD",
            "expression": [
              "",
              "CALCULATE (",
              "    [Actuals],",
              "    CALCULATETABLE (",
              "        DATESYTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "cceb1633-c625-4f81-92e9-220b5bcdf28f"
          },
          {
            "name": "Lines",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG4 - Lines'[Measure]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "70efca37-c432-410e-a447-3025e4237852"
          },
          {
            "name": "Quantity",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG1 - Quantity'[Measure])",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "c68488fd-5631-4b9f-a9c3-7f17d7f6a2ef"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target YTD]",
              "VAR _DELTA  = [Actuals YTD] -  _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "4. YTD",
            "lineageTag": "0886ae94-a618-4cb5-a879-159717597f72"
          },
          {
            "name": "Sales Target YTD vs. Gross Sales ()",
            "expression": [
              "",
              "[Actuals YTD] - [Sales Target YTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "60e7cc65-3801-4cf5-b186-7216e43c7086"
          },
          {
            "name": "Value",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ('1) Selected Metric'[Select a Measure]),",
              "        'Z01CG2 - Value (Budget Rate)'[Measure]",
              "    )",
              ") "
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Actuals",
            "lineageTag": "c5c7fd2d-5b7d-467c-953c-71338d4296f7"
          },
          {
            "name": "Sales Target YTD",
            "expression": [
              "",
              "VAR YRTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESYTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsBeforeThisMonth] = TRUE",
              "    ) // Calculates the target for the current month/year selection",
              "VAR _CurrentMonth_value =",
              "    CALCULATE( [Sales Target], 'Date'[IsThisMonth] = TRUE ) // Calculates the % workdays MTD together with the dynamic parameter to set the exponential rate of increase MTD",
              "VAR _currentMonthWorkDay =",
              "    POWER(",
              "        CALCULATE(",
              "            MAX( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE,",
              "            'Date'[IsThisMonth] = TRUE",
              "        ),",
              "        0.93",
              "    ) // If viewing units, hide the FCST (as there is no units FCST as of July 09, 2020)",
              "VAR MOTD =",
              "    IF(",
              "        _CurrentMonth_value > 0,",
              "        _currentMonthWorkDay * _CurrentMonth_value,",
              "        BLANK( )",
              "    )",
              "        + YRTD",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _YEAR = MAX( 'Date'[Calendar Year Number (ie 2021)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Number (ie 2021)] = _YEAR,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        // If date is in the visual context and YTD is blank, show MTD, otherwise add YTD + MTD together",
              "        MOTD",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "8baefb39-9d1b-40ad-9ad5-4f9c9c310095"
          },
          {
            "name": "Sales Target QTD",
            "expression": [
              "",
              "VAR _QTD =",
              "    CALCULATE(",
              "        [Sales Target],",
              "        CALCULATETABLE(",
              "            DATESQTD( 'Date'[Date] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _MTD =",
              "    CALCULATE( [Sales Target MTD], 'Date'[IsThisMonth] = TRUE )",
              "VAR _PERIOD = SELECTEDVALUE( '4) Selected Period'[Period] )",
              "VAR _QUARTER = MAX( 'Date'[Calendar Year Quarter (ie 202101)] )",
              "VAR _MONTH = MAX( 'Date'[Calendar Year Month (ie 202101)] )",
              "RETURN",
              "    IF(",
              "        _PERIOD = \"Full Period\",",
              "        CALCULATE(",
              "            [Sales Target],",
              "            ALL( 'Date' ),",
              "            'Date'[Calendar Year Quarter (ie 202101)] = _QUARTER,",
              "            'Date'[Calendar Year Month (ie 202101)] <= _MONTH",
              "        ),",
              "        IF(",
              "            ISBLANK( _QTD ),",
              "            _MTD,",
              "            // If date is in the visual context and QTD is blank, show MTD, otherwise add QTD + MTD together",
              "            IF( MAX ( 'Date'[Date] ) >= MAX ('Last Refresh'[Last Refresh]), _QTD + _MTD, _QTD )",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Sales Target",
            "lineageTag": "5e01dd13-583d-429c-9ba4-79b2fc89b918"
          },
          {
            "name": "Sales Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Sales Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        1.035",
              "    )",
              "VAR CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        1.035",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "528d4072-5ea6-4427-97e0-7e812a0f511a"
          },
          {
            "name": "Sales Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT (",
              "            '3) Selected Target'[Select a Target]",
              "        ),",
              "        'Z03CG1 - Sales Target'[Target]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "14bbba44-f1d9-49ad-ab20-4c7910d9d7da"
          },
          {
            "name": "Sales Target vs. Actuals ()",
            "expression": [
              "",
              "[Actuals] - [Sales Target]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "79869441-9511-4efb-b95a-147eb3d14926"
          },
          {
            "name": "Sales Target vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target]",
              "VAR _ACTUAL = [Actuals]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "876d123c-de76-4a10-84e7-470eed31b8c8"
          },
          {
            "name": "Sales Target MTD vs. Actuals ()",
            "expression": [
              "",
              "[Actuals MTD] - [Sales Target MTD]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "30488de0-5eac-468b-a3db-81eea38a2165"
          },
          {
            "name": "Sales Target MTD vs. Actuals (%)",
            "expression": [
              "",
              "VAR _TARGET = [Sales Target MTD]",
              "VAR _ACTUAL = [Actuals MTD]",
              "VAR _DELTA  = _ACTUAL - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "",
              "RETURN",
              "",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "2. MTD\\Sales Target",
            "lineageTag": "2d7fff67-3495-4143-b0e4-2322aca32642"
          },
          {
            "name": "Actuals MTD, Latest Data Point",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        [Actuals MTD]",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "f526af90-be40-4e71-a8af-700e44503379"
          },
          {
            "name": "Actuals MTD, Data Label",
            "expression": [
              "",
              "-- Max workday in scope",
              "VAR _MAXWD =",
              "    CALCULATE (",
              "        MAX ( 'Date'[Workdays MTD] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)])",
              "    )",
              "",
              "-- Max date in scope",
              "VAR _MAXDT =",
              "    CALCULATE ( MAX ('Date'[Date] ),",
              "        'Date'[IsDateInScope],",
              "        ALLEXCEPT ('Date', 'Date'[Calendar Month Year (ie Jan 21)]) )",
              "RETURN",
              "",
              "    -- If the selected workday = the max workday in scope, return the value",
              "    -- Otherwise return blank (don't show the marker / value)",
              "    IF (",
              "        MAX ('Date'[Workdays MTD]) = _MAXWD",
              "            || MAX ('Date'[Date]) = _MAXDT,",
              "        \"#6e8c95\",",
              "        \"#FFFFFF00\"",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "9. Technical Measures",
            "lineageTag": "a38853fe-b2da-469e-b410-756d6c44e88d"
          },
          {
            "name": "Blank",
            "expression": [
              "",
              "BLANK ()"
            ],
            "isHidden": true,
            "displayFolder": "9. Technical Measures",
            "lineageTag": "7bc7070b-80ae-431e-8600-63befaa1d5bf"
          },
          {
            "name": "Orders Target",
            "expression": [
              "",
              "CALCULATE (",
              "    [Blank],",
              "    TREATAS (",
              "        DISTINCT ( '3) Selected Target'[Select a Target] ), 'Z03CG2 - Orders Target'[Target] )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "4eed64a0-d832-4f27-ae28-91d1dc31cb89"
          },
          {
            "name": "Orders Target vs. Net Orders (%)",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "VAR _TARGET = [Orders Target]",
              "VAR _DELTA  = [Net Orders] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "e6cda3c8-6f0c-4d5a-8685-d41623fb81d9"
          },
          {
            "name": "Orders Target vs. Net Orders ()",
            "description": "Net orders exclude cancellation document types",
            "expression": [
              "",
              "[Net Orders] - [Orders Target]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Total\\Orders Target",
            "lineageTag": "baee51d7-d773-4a52-9486-6aed36e264c0"
          },
          {
            "name": "Orders Target MTD",
            "expression": [
              "",
              "-- Calculates the target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Budget increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "    ",
              "VAR __HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        __HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            __HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. MTD\\Orders Target",
            "lineageTag": "1d671a50-fac4-4d2b-a41d-3328c522dafa"
          },
          {
            "name": "Orders Target QTD",
            "expression": [
              "",
              "VAR _DATES_QTD =",
              "    CALCULATETABLE (",
              "        DATESQTD ('Date'[Date]),",
              "        'Date'[IsThisMonth] = FALSE",
              "    )",
              "VAR _CURRENT_MONTH_Forecast = [Orders Target MTD]",
              "VAR _QTD_Forecast_BEFORE_THIS_MONTH = CALCULATE ([Orders Target], _DATES_QTD)",
              "VAR _RESULT = _CURRENT_MONTH_Forecast + _QTD_Forecast_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. QTD\\Orders Target",
            "lineageTag": "8592bd67-7145-4ca4-ba42-fa3e0defba2e"
          },
          {
            "name": "Orders Target YTD",
            "expression": [
              "",
              "VAR _CURRENT_MONTH_TARGET = [Orders Target MTD]",
              "VAR _YTD_TARGET_BEFORE_THIS_MONTH =",
              "    CALCULATE (",
              "        [Orders Target],",
              "        CALCULATETABLE (",
              "            DATESYTD ('Date'[Date]),",
              "            'Date'[IsThisMonth] = FALSE,",
              "            'Date'[IsDateInScope] = TRUE",
              "        )",
              "    )",
              "VAR _RESULT = _CURRENT_MONTH_TARGET + _YTD_TARGET_BEFORE_THIS_MONTH",
              "RETURN",
              "    _RESULT"
            ],
            "formatString": "#,##0",
            "displayFolder": "4. YTD",
            "lineageTag": "056c010c-5b3c-4faa-a65e-daeb3231600d"
          },
          {
            "name": "Gross Sales 2YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -2, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "7a676e6e-7385-4ce0-acb9-84a987fededa"
          },
          {
            "name": "Gross Sales 1YP (Selected Unit)",
            "expression": [
              "",
              "CALCULATE ( [Gross Sales (Selected Unit)], DATEADD('Date'[Date], -1, YEAR ))"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Total\\Sales Target",
            "lineageTag": "77b9b822-0dde-4ece-8dd7-3dd7a1a9bb14"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "__Demo Measures",
        "description": "5 measures usable without any selection; quick-start",
        "lineageTag": "5bfcf671-969d-4907-942e-4ed897cbc246",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "__Measures",
            "dataType": "int64",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[__Measures]",
            "lineageTag": "7b86f793-f2d4-4efc-be96-092bd800e254",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "__Demo Measures",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": [
                "",
                "SELECTCOLUMNS (",
                "    { 1 },",
                "    \"__Measures\", ''[Value]",
                ")"
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "19ea0898-8a9e-43a6-8190-48879e67068e"
          },
          {
            "name": "Sales Budget",
            "expression": [
              "",
              "CALCULATE (",
              "    [Budget],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "e3555966-4f07-443b-a732-838da8defcc2"
          },
          {
            "name": "Sales Forecast",
            "expression": [
              "",
              "CALCULATE (",
              "    [Forecast],",
              "    'Exchange Rate'[From Currency] = \"EUR\"",
              ")"
            ],
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "d4110b87-0cfc-49d6-8b96-053d05450b96"
          },
          {
            "name": "Billing Document Lines",
            "expression": "[Invoice Lines]",
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "d69dc0a4-9763-403e-8e38-edb03bb5ec7e"
          },
          {
            "name": "# Accounts",
            "expression": "1",
            "formatString": "#,##0.00",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "be41049e-f8e5-48dd-8d7f-9c14dd274b1a"
          },
          {
            "name": "ActualVsTargetColor",
            "expression": [
              "",
              "IF (",
              "    [Gross Sales (Quantity)]",
              "        > [Sales Target],",
              "    \"good\", -- Good color (blue)",
              "    \"bad\"  -- Bad color (yellow)",
              ")"
            ],
            "lineageTag": "c7dae960-d6ad-4ebc-881d-32b70eebfecf",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "No. Products",
            "expression": "COUNTROWS ( 'Products' )",
            "formatString": "#,##0 Products",
            "displayFolder": "Measures\\Numbers",
            "lineageTag": "d80a646a-487d-43cf-8469-f960058c7705"
          }
        ],
        "annotations": [
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "DateTableTemplate_ff17ea92-fce8-4bb9-9469-a432491a20d5",
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "c945bdef-389b-46cd-a7f0-a83789c9c5c9",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "5991e013-8217-44f9-a0ef-7ac0cf0f4c8d",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "34a5d6c4-7790-4b6e-8974-0d36362c26b7",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "cdef966c-81c9-4598-81de-3cba223f2127",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "b1fe8d4c-a9fa-4378-937f-b6940282fa3f",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "604c6c62-a35e-4d11-85b6-184d218138b4",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "f4346808-0678-449e-aa3e-82fc54e06271",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "0be43bf0-3a7d-40bf-88b1-fe60c4f9f9e8",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "DateTableTemplate_ff17ea92-fce8-4bb9-9469-a432491a20d5-ac1b4bd2-083b-493b-8602-35d4913a0014",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "d8db4f5d-2051-4d1f-8db4-9414626d7957",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "45d8ca75-a9f7-431b-83a8-0df43dcd8ca6"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "6ea11dac-2f42-4ce4-931f-acc160a283ad"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "a6d5bdfd-d0bf-4640-9a9b-2a116dc97df3"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "dad48f91-da21-477f-8584-725394142670"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "LocalDateTable_fca581ec-8430-42e1-9f91-795770007388",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "0fe4862c-12cd-41cf-991b-a4e05268dc66",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "4615dcec-f3be-455d-8a53-0211a799e92d",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "1683a7dc-d3dd-4391-9e63-959057ef927a",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "323c174a-d2fd-4974-9ba2-aae97439d157",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "a06ba4ad-7661-4be2-8a4f-6fd419a3ff89",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "d7fe11e9-3273-4990-84c9-f4b3f25cae39",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "81b16b4e-4537-42b4-abe5-b71507989bb9",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "690c6e9a-a6fa-42fb-9b0a-66fc163fa77c",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_fca581ec-8430-42e1-9f91-795770007388-b2f19df5-fa1b-4748-8959-5034576ef8c0",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Orders'[Billing Date])), 1, 1), Date(Year(MAX('Orders'[Billing Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "134cd47b-83dd-4120-8a4a-0365e4909fa0",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "bcbc7796-b7ad-4b4a-a64f-c3b08d3bc656"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "9b943717-723c-4c2a-9ea2-8bec3f8da7ae"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "c951a449-fa6e-4f85-8de3-62077eeecb75"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "e1e93ac9-fe3d-418c-bccf-2679077681bb"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "LocalDateTable_4ad7e833-9e3a-4bd3-9873-535c2d4d4285",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "9796b169-31c8-4ace-a143-73322ab16487",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "8aad7794-d320-4e11-883d-c65a05924061",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "f8a451af-9064-411d-a173-eb43ce89620c",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "800d3d67-2a2c-473f-8f12-d8db2763047d",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "27652454-4d21-442f-951f-b382900c2e13",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "d86e11a8-416f-47d9-95a5-8b318bc78002",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "65abc8a0-3276-4401-90d7-3019767fc8df",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "c2167a2b-5df2-4b64-aa42-36f136397fec",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_4ad7e833-9e3a-4bd3-9873-535c2d4d4285-404d773c-c025-4089-a461-fd536a2e3081",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Orders'[Ship Date])), 1, 1), Date(Year(MAX('Orders'[Ship Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "7223fac7-9404-438a-a490-219e54db736a",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "11e5dab9-14db-4e7d-bf17-d5654c14f31a"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "8e0e8fc3-c864-4065-a0b4-6a870fbc07b0"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "61d614ec-764c-4e2f-8eb7-bd007dfda7a4"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "20a524cf-9c4c-40c2-9313-ee6a69f79875"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "LocalDateTable_579bd8be-fc8b-4a18-a637-ab748ff358e0",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "f16358e0-4f04-4e39-9c60-7fd7a933a921",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "c33641a9-0710-44b0-a03f-2b7dab25167a",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "7b8c8595-7d03-4dca-918c-295b36dd6e11",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "d4b7fc67-1d3c-4ae3-8ca6-839e98d4b9ac",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "3dfa262a-012c-4623-ba2d-84a24805ab60",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "9ecd9b0a-c4aa-45c0-90f0-9906071118b8",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "6bb32ea0-7dab-4eca-af30-28dcac78dfa0",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "7c8a8ccc-6d5c-4124-9815-674b6cb879af",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_579bd8be-fc8b-4a18-a637-ab748ff358e0-968c5d92-4854-4a57-882e-d207a94cce03",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Orders'[Confirm Goods Receipt Date])), 1, 1), Date(Year(MAX('Orders'[Confirm Goods Receipt Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "46a3ceab-41a6-4e9e-88ca-4a0ccf317dde",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "6ed2928b-a006-4b6c-93ed-fdcbf99d7540"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "ac447853-c588-4e05-8e44-6ecf937284e3"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "37cfdd53-4a2d-481b-9e5d-1f8837e3f7e8"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "434c1155-f3e5-4b65-9f76-8c848ad2abcb"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Last Refresh",
        "lineageTag": "8df9a87e-0917-4ec3-8a2f-297dbfaa148e",
        "columns": [
          {
            "name": "Last Refresh",
            "dataType": "dateTime",
            "sourceColumn": "Last Refresh",
            "formatString": "General Date",
            "lineageTag": "427dcc41-8ebd-4730-9cb4-9295708e7591",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "cf55bb82-b832-4bdf-bc81-c415a3504ae9",
                "defaultHierarchy": {
                  "table": "LocalDateTable_595bdce4-ba17-4e98-90af-2d00b0a66670",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Last Refresh-01ea78bc-dff4-4eac-b58e-527fab59801b",
            "mode": "import",
            "queryGroup": "Scalar Values",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = DateTimeZone.FixedLocalNow()",
                "in",
                "    Source"
              ]
            }
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTimeZone"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"cf55bb82-b832-4bdf-bc81-c415a3504ae9\",",
              "    \"fromTable\": \"Last Refresh\",",
              "    \"fromColumn\": \"Last Refresh\",",
              "    \"toTable\": \"LocalDateTable_595bdce4-ba17-4e98-90af-2d00b0a66670\",",
              "    \"toColumn\": \"Date\",",
              "    \"joinOnDateBehavior\": \"datePartOnly\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "LocalDateTable_595bdce4-ba17-4e98-90af-2d00b0a66670",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "a70dcdb4-da29-4e72-af37-15f7fcdb9add",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isDataTypeInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "ded4ff8c-5de2-4659-b9c6-f56cb8fa2580",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "c0332679-2f41-465c-930a-f8c75a120e36",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "76c25a6f-703c-4900-9e07-6673ee0ff1c1",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "955e8344-ef65-4433-b2dc-498ee21a5287",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "4fbb2657-03b1-48ed-8d7b-c443acc7a08a",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "62ec656e-47fc-47e6-9fd2-4251017f68ad",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isDataTypeInferred": true,
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "d58bb67c-efd5-4e0e-a5a9-ea5494fb8dba",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_595bdce4-ba17-4e98-90af-2d00b0a66670-6d1d6bee-26e2-4f90-9936-5174b0acf7b5",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Last Refresh'[Last Refresh])), 1, 1), Date(Year(MAX('Last Refresh'[Last Refresh])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "edc2d574-36fd-4b0e-92e8-a699c8e1d7f2",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "5475efa6-2190-4ebe-9b95-b32668a278ac"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "eac457da-c127-477b-b35a-5f0795b2c6b2"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "9c3ee6aa-a6b1-4449-a80d-727aa9d2be56"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "f8901b6d-c049-4912-8451-acc9a2df4b31"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      },
      {
        "name": "Invoices",
        "lineageTag": "fba0b030-ca72-44ec-a0e3-98ad3bba0508",
        "columns": [
          {
            "name": "Billing Document Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "billing_document_number",
            "formatString": "0",
            "sourceProviderType": "int",
            "displayFolder": "Columns",
            "lineageTag": "5af8c1b0-9c62-41b6-9c46-ddb0ce3585a9",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "billing_date",
            "formatString": "Long Date",
            "sourceProviderType": "date",
            "displayFolder": "Columns",
            "lineageTag": "620c8eea-a6f2-4eea-9dd2-401eacc94636",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "Customer Key",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "customer_key",
            "sourceProviderType": "nvarchar(max)",
            "displayFolder": "Columns",
            "lineageTag": "c4c2e629-13f0-49bd-a155-6b4ab02847e1",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Document Line Item Number",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "billing_document_line_item_number",
            "formatString": "0",
            "sourceProviderType": "int",
            "displayFolder": "Columns",
            "lineageTag": "de732182-dbdd-4d23-a417-553be7c45e2b",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Product Key",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "product_key",
            "formatString": "0",
            "sourceProviderType": "bigint",
            "displayFolder": "Columns",
            "lineageTag": "d9b2b581-c637-4916-9558-494ef1fa2450",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Ship Date",
            "dataType": "dateTime",
            "isHidden": true,
            "sourceColumn": "ship_date",
            "formatString": "Long Date",
            "sourceProviderType": "date",
            "displayFolder": "Columns",
            "lineageTag": "2c49ff4f-96bc-48c9-a242-c1204247ce23",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "relationship": "7572bf1a-bc25-432d-8287-8a015e4ddeab",
                "defaultHierarchy": {
                  "table": "LocalDateTable_6b2c9e31-0c64-4034-8869-3404e703fc01",
                  "hierarchy": "Date Hierarchy"
                },
                "isDefault": true
              }
            ],
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ]
          },
          {
            "name": "OTD Indicator",
            "dataType": "boolean",
            "isHidden": true,
            "sourceColumn": "otd_indicator",
            "formatString": "\"TRUE\";\"TRUE\";\"FALSE\"",
            "sourceProviderType": "bit",
            "displayFolder": "Columns",
            "lineageTag": "8e50d053-0fc7-4fa2-b869-24364a0ae99a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Billing Document Type Code",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "billing_document_type_code",
            "sourceProviderType": "nvarchar(max)",
            "displayFolder": "Columns",
            "lineageTag": "705c6e4f-d7d8-4230-b26e-499b1e09188a",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Local Currency",
            "dataType": "string",
            "isHidden": true,
            "sourceColumn": "local_currency",
            "sourceProviderType": "nvarchar(max)",
            "displayFolder": "Columns",
            "lineageTag": "cb9f4c47-d859-423b-b802-c8a178d57440",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          },
          {
            "name": "Delivery Cost",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "delivery_cost",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "9ecb1ae0-6e98-45f6-a75d-f14fa567fb57",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Net Invoice COGS",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "net_invoice_cogs",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "ef6eafe9-cb4f-4a7f-a28f-1a00be6f86a2",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Late Delivery Penalties",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "late_delivery_penalties",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "71d608e7-9b6e-4ec6-bf86-ab3a82b5fda8",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Overdue Payment Penalties",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "overdue_payment_penalties",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "1d349cb7-8e68-44a1-89f6-8b9dc9c318b7",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Taxes & Commercial Fees",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "taxes__commercial_fees",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "a2efa68e-4950-49e5-8c33-68120ad1616d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Freight",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "freight",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "e9872e0c-ba0f-4ba7-9de5-4ed3f4dc3429",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Net Invoice Value",
            "dataType": "double",
            "isHidden": true,
            "sourceColumn": "net_invoice_value",
            "sourceProviderType": "float",
            "displayFolder": "Columns",
            "lineageTag": "ac304df8-7ccc-450b-8d1c-a57f93db365d",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"isGeneralNumber\":true}"
              }
            ]
          },
          {
            "name": "Net Invoice Quantity",
            "dataType": "int64",
            "isHidden": true,
            "sourceColumn": "net_invoice_quantity",
            "formatString": "0",
            "sourceProviderType": "int",
            "displayFolder": "Columns",
            "lineageTag": "6f2da7dd-b470-4d32-98ea-5ebd10095643",
            "summarizeBy": "sum",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "Invoices",
            "mode": "import",
            "queryGroup": "Tables",
            "source": {
              "type": "m",
              "expression": [
                "let",
                "    Source = Sql.Database(#\"SqlEndpoint\",#\"Database\"),",
                "    Data = Source{[Schema=\"dbo\",Item=\"invoices\"]}[Data],",
                "    #\"Select Columns\" = Table.RemoveColumns ( Data, {\"dwcreateddate\", \"net_invoice_cost\"} )",
                "in",
                "    #\"Select Columns\""
              ]
            }
          }
        ],
        "measures": [
          {
            "name": "Delivery Margin (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "",
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Freight Surcharge],",
              "        'Invoice Document Type'[Billing Document Type Code] IN {\"invoice\", \"express\"}",
              "    )",
              "VAR _MARGIN = [Delivery Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "4d723c79-cfbc-4e96-b733-149429093b95"
          },
          {
            "name": "Delivery Margin 1YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "d15f4a1b-40e8-4af0-9fa8-4c8691b5702f"
          },
          {
            "name": "Delivery Margin 2YP (%)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\%",
            "lineageTag": "f3fe51e5-3af4-4573-a104-6f13b3475648"
          },
          {
            "name": "Delivery Margin (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Freight] - 'Invoices'[Delivery Cost]",
              "    ),",
              "    'Invoice Document Type'[Billing Document Type Code] IN { \"invoice\", \"express\" }",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "adf032e2-a94e-4c64-b116-3bae16b40c1c"
          },
          {
            "name": "Delivery Margin 1YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "92415e4c-e6e2-45ff-ab1a-8a11ff4fd364"
          },
          {
            "name": "Delivery Margin 2YP (Value)",
            "description": "The delivery margin only considers the revenue and costs associated with freights, delivery and shipments.",
            "expression": [
              "CALCULATE (",
              "    [Delivery Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\III. Delivery Margin\\$",
            "lineageTag": "04c7666b-55bd-42ea-a0fd-7982d9697d9b"
          },
          {
            "name": "Selling Margin (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "VAR _TOTAL =",
              "    CALCULATE (",
              "        [Total Net Invoice Value],",
              "        'Invoice Document Type'[Billing Document Type Code] = \"invoice\"",
              "    )",
              "VAR _MARGIN = [Selling Margin (Value)]",
              "RETURN",
              "    DIVIDE (_MARGIN, _TOTAL)"
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "3663b091-8e64-487b-95c5-a3a356cd6b5b"
          },
          {
            "name": "Selling Margin 1YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "2463193f-b427-4961-b506-cabae06dc450"
          },
          {
            "name": "Selling Margin 2YP (%)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\%",
            "lineageTag": "3b62bc90-c3ad-4940-b1db-cec84413ba1c"
          },
          {
            "name": "Selling Margin (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "",
              "CALCULATE (",
              "    SUMX (",
              "        'Invoices',",
              "        'Invoices'[Net Invoice Value] - 'Invoices'[Net Invoice COGS]",
              "    ),",
              "    'Invoice Document Type'[Billing Document Type Code] = \"invoice\"",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "be448632-beb1-4250-b5dd-9a0faaab6f52"
          },
          {
            "name": "Selling Margin 1YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "f22d9d95-877a-4e38-83be-7f7b12b13576"
          },
          {
            "name": "Selling Margin 2YP (Value)",
            "description": "The selling margin is the margin earned when considering only the revenue and costs associated with the product, before delivery",
            "expression": [
              "CALCULATE (",
              "    [Selling Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\II. Selling Margin\\$",
            "lineageTag": "20d39d89-73f2-47b3-aa46-1098a58a9077"
          },
          {
            "name": "Standard Margin (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "",
              "DIVIDE ( [Standard Margin (Value)], [Net Sales] ) "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "b83ec207-e4f4-4f0d-919d-c3b1a17e900e"
          },
          {
            "name": "Standard Margin 1YP (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "d62ee724-dceb-407c-9129-aa7dbe586ab4"
          },
          {
            "name": "Standard Margin 2YP (%)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (%)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ") "
            ],
            "formatString": "#,##0.0%",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\%",
            "lineageTag": "297a502c-34d3-4eb5-856c-33e65253a609"
          },
          {
            "name": "Standard Margin (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net Sales",
              "            VAR _NET = ",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "            -- COGS",
              "            VAR _COST =",
              "            ('Invoices'[Net Invoice COGS] ",
              "                + 'Invoices'[Delivery Cost] )",
              "",
              "            RETURN",
              "",
              "            ( _NET - _COST ) / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected rate",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "ff8b2241-4dee-401a-af2c-a246e02f2a40"
          },
          {
            "name": "Standard Margin 1YP (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "ecefc65d-3c1e-4680-8aee-7b9f7623d8c6"
          },
          {
            "name": "Standard Margin 2YP (Value)",
            "description": [
              "The standard margin is the selling margin + the delivery margin",
              "It takes into account all revenues and costs."
            ],
            "expression": [
              "CALCULATE (",
              "    [Standard Margin (Value)],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\d. Margins\\I. Std. Margin\\$",
            "lineageTag": "89b286d1-1b3a-45de-9753-fc201a384161"
          },
          {
            "name": "Gross Sales",
            "expression": [
              "",
              "[Total Net Invoice Value]",
              "    + [Total Freight Surcharge]",
              "    + [Total Late Delivery Penalties]",
              "    + [Total Overdue Payment Penalties]",
              "    - [Total Taxes & Commercial Fees]"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "683196db-ff3e-4763-8161-a11c1626c646"
          },
          {
            "name": "Gross Sales (Selected Unit)",
            "expression": [
              "",
              "-- Sideways recursion",
              "CALCULATE (",
              "    [Actuals],",
              "    ALL ( '1) Selected Metric'[Select a Measure] ),",
              "    '1) Selected Metric'[Select a Measure] = \"Gross Sales\"",
              ")"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "c6803610-3c05-4cb0-bf47-500545195637"
          },
          {
            "name": "MTD Gross Sales",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    CALCULATETABLE (",
              "        DATESMTD ('Date'[Date]),",
              "        'Date'[IsDateInScope]",
              "    )",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "ea816f78-4faf-4f3f-8d4e-02121230e7db"
          },
          {
            "name": "Total Net Invoice Value",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Value]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice Value]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\I. Total",
            "lineageTag": "4743b7bf-79cb-4660-846e-243bcf724584"
          },
          {
            "name": "Gross Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "16f7ed63-9149-4aa0-a7b0-fb57300ee516"
          },
          {
            "name": "Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 1YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "c71f604e-ded0-4bee-b453-f1ba4844b672"
          },
          {
            "name": "Gross Sales vs 1YP ()",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\Daily",
            "lineageTag": "8f2720aa-6d1b-43d8-a43c-58e1293ab7bf"
          },
          {
            "name": "MTD Gross Sales 1YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 1YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "c286b77d-b313-4767-8645-1fd3a5d0c0c8"
          },
          {
            "name": "MTD Gross Sales vs 1YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "df2c1596-d3b7-4359-ad0a-708a2c840d42"
          },
          {
            "name": "MTD Gross Sales vs 1YP ()",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\II. 1YP\\MTD",
            "lineageTag": "e0550d22-4405-4c3b-bf05-d150b153fc27"
          },
          {
            "name": "Gross Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "8788b945-6470-4988-b936-b739a0f842ea"
          },
          {
            "name": "Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [Gross Sales 2YP]",
              "VAR _DELTA  = [Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "9362a185-8dd0-41c5-b77a-0b65c6183416"
          },
          {
            "name": "Gross Sales vs 2YP ()",
            "expression": [
              "",
              "[Gross Sales] - [Gross Sales 2YP]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\Daily",
            "lineageTag": "ee265e11-1ead-44d2-8851-f666a26db72e"
          },
          {
            "name": "MTD Gross Sales 2YP",
            "expression": [
              "",
              "-- Calculates Target for the current month/year selection",
              "VAR _CurrentMonth =",
              "    CALCULATE (",
              "        [Gross Sales 2YP],",
              "        ALL ( 'Date' ),",
              "        VALUES (",
              "            'Date'[Calendar Month Year (ie Jan 21)]",
              "        )",
              "    )",
              "",
              "-- Computes rate at which Target increases through the month",
              "VAR _CurrentMonthWDMTD =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] ),",
              "            'Date'[IsDateInScope] = TRUE",
              "        ),",
              "        0.93",
              "    )",
              "VAR _CurrentMonthWDTotal =",
              "    POWER (",
              "        CALCULATE (",
              "            MAX ( 'Date'[Workdays MTD %] )",
              "        ),",
              "        0.93",
              "    )",
              "VAR _Period =",
              "    SELECTEDVALUE (",
              "        '4) Selected Period'[Period]",
              "    )",
              "VAR _HasOneMonth =",
              "    HASONEVALUE (",
              "        'Date'[Calendar Month Year (ie Jan 21)]",
              "    )",
              "RETURN",
              "    -- return MTD value if a month is selected",
              "    IF.EAGER (",
              "        _HasOneMonth && _Period = \"Full Period\",",
              "        _CurrentMonthWDTotal",
              "            * _CurrentMonth,",
              "        IF (",
              "            _HasOneMonth,",
              "            _CurrentMonthWDMTD",
              "                * _CurrentMonth",
              "        )",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "1e93df27-b0ee-452d-b209-8e10a91109b8"
          },
          {
            "name": "MTD Gross Sales vs 2YP (%)",
            "expression": [
              "",
              "VAR _TARGET = [MTD Gross Sales 1YP]",
              "VAR _DELTA  = [MTD Gross Sales] - _TARGET",
              "VAR _PERC   = DIVIDE ( _DELTA, _TARGET )",
              "RETURN",
              "_PERC"
            ],
            "formatString": "#,##0.0% ;#,##0.0% ;#,##0.0%",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "c694eb93-5caf-484f-b50d-c2601f9cd9bd"
          },
          {
            "name": "MTD Gross Sales vs. 2YP ()",
            "expression": [
              "",
              "[MTD Gross Sales] - [MTD Gross Sales 1YP]"
            ],
            "formatString": "#,##0 ;#,##0 ;#,##0",
            "displayFolder": "1. Value\\a. Gross Sales Actuals\\III. 2YP\\MTD",
            "lineageTag": "556ddb49-2de6-4d05-bda4-197a7ed5d320"
          },
          {
            "name": "Net Sales",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Net sales",
              "            ('Invoices'[Net Invoice Value]",
              "                + 'Invoices'[Freight]",
              "                - 'Invoices'[Taxes & Commercial Fees]",
              "                + 'Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties] )",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "2afed537-1de8-4905-967c-83cf6ae8c661"
          },
          {
            "name": "Net Sales 1YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "ad3c564a-708d-4c42-9e18-bb723225c142"
          },
          {
            "name": "Net Sales 2YP",
            "expression": [
              "",
              "CALCULATE (",
              "    [Net Sales],",
              "    DATEADD ('Date'[Date], -2, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "1. Value\\c. Net Sales",
            "lineageTag": "7cefb57c-9696-40a1-897c-b314c3a66abd"
          },
          {
            "name": "Total Cost",
            "description": "The cost of the product sold and the shipment / delivery",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- COGS",
              "            ('Invoices'[Net Invoice COGS] + 'Invoices'[Delivery Cost])",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "cf432eee-c4e8-4a90-b256-81261849e567"
          },
          {
            "name": "Total Delivery Cost",
            "description": "The cost of the delivery only",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Delivery Cost]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "3e145aa8-d957-4b79-b7af-55cda240d83d"
          },
          {
            "name": "Total Net Invoice COGS",
            "description": "All costs associated with the sold product",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Net Invoice COGS]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\I. Cost",
            "lineageTag": "4ee93bec-8319-45b6-92b9-d4c906841912"
          },
          {
            "name": "Total Fees & Penalties",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "",
              "            -- Total fees & penalties",
              "            ('Invoices'[Late Delivery Penalties]",
              "                + 'Invoices'[Overdue Payment Penalties]",
              "                - 'Invoices'[Taxes & Commercial Fees])",
              "",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "a2c8e893-19e4-4e9f-bd27-b30a74db5210"
          },
          {
            "name": "Total Late Delivery Penalties",
            "description": "Late Delivery penalties occur when we fail to meet the SLA for deliveries. If the products take longer than a certain number of days to deliver after the requested delivery date, a Late Delivery Penalty is levied.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Late Delivery Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "3ee42063-2a45-4ef0-8135-189b387479ee"
          },
          {
            "name": "Total Overdue Payment Penalties",
            "description": "Overdue Payments result when the customer hasn't paid their invoice within a certain number of days since the product was shipped.",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Overdue Payment Penalties]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "279adfbb-4f1f-49e7-8f13-57c380ad1d5d"
          },
          {
            "name": "Total Taxes & Commercial Fees",
            "description": "This measure is theSumof column 'Invoices'[Taxes & Commercial Fees]",
            "expression": [
              "SUMX (",
              "    'Invoices',",
              "    'Invoices'[Taxes & Commercial Fees]",
              "        / RELATED ( 'Budget Rate'[Rate] )",
              ")",
              "    * MAX ( 'Exchange Rate'[Rate] )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\II. Penalties and Adjustments",
            "lineageTag": "187488af-0dcd-44e3-b20e-7fd7b0f489dd"
          },
          {
            "name": "Total Freight Surcharge",
            "description": "The freight surcharge is what we charge for delivery. It is one of our lines of revenue.",
            "expression": [
              "",
              "VAR _RATE = MAX ('Exchange Rate'[Rate])",
              "RETURN",
              "    CALCULATE (",
              "",
              "        -- Convert to common currency (WAT)",
              "        SUMX (",
              "            'Invoices',",
              "            'Invoices'[Freight]",
              "                / RELATED ('Budget Rate'[Rate])",
              "        )",
              "",
              "            -- Convert to selected currency",
              "            * _RATE,",
              "",
              "        -- Limit to dates in scope",
              "        'Date'[IsDateInScope] = TRUE",
              "    )"
            ],
            "formatString": "#,##0",
            "isHidden": true,
            "displayFolder": "1. Value\\b. Cost & Penalties\\III. Freight",
            "lineageTag": "29974f41-9300-4296-92e6-a5f0f7f5b4a6"
          },
          {
            "name": "Invoice Lines",
            "expression": [
              "",
              "COUNTROWS ( 'Invoices' )"
            ],
            "formatString": "#,##0",
            "displayFolder": "3. Lines",
            "lineageTag": "a56d5b74-2cd8-4ce0-a673-f229a09a9726"
          },
          {
            "name": "Gross Sales (Quantity)",
            "expression": [
              "",
              "[Total Net Invoice Quantity]"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "3adb6c1c-0186-4a30-90b0-a60040b44316"
          },
          {
            "name": "Gross Sales 1YP (Quantity)",
            "expression": [
              "",
              "CALCULATE (",
              "    [Gross Sales (Quantity)],",
              "    DATEADD ('Date'[Date], -1, YEAR)",
              ")"
            ],
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "7b231dac-05c2-415f-99de-7a7fbbdf3524"
          },
          {
            "name": "Total Net Invoice Quantity",
            "description": "This measure is theSumof column 'Invoices'[Net Invoice Quantity]",
            "expression": "SUM ( 'Invoices'[Net Invoice Quantity] )",
            "formatString": "#,##0",
            "displayFolder": "2. Quantity\\b. Gross Sales Actuals",
            "lineageTag": "0a56a159-aefd-4473-826e-b7bb61e1ddba"
          }
        ],
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": [
              "[",
              "  {",
              "    \"name\": \"0e6e4252-95c4-4e0e-a4c8-874e5463ec4c\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Billing Date\",",
              "    \"toTable\": \"Date\",",
              "    \"toColumn\": \"Date\"",
              "  },",
              "  {",
              "    \"name\": \"7dacb5b5-3b77-45fe-85f9-cdebc76b1d56\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Billing Document Type Code\",",
              "    \"toTable\": \"Invoice Document Type\",",
              "    \"toColumn\": \"Billing Document Type Code\"",
              "  },",
              "  {",
              "    \"name\": \"9a0268c1-ab7d-d96d-ab2f-c4ba28aaae5c\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Customer Key\",",
              "    \"toTable\": \"Customers\",",
              "    \"toColumn\": \"Customer Key\"",
              "  },",
              "  {",
              "    \"name\": \"7a4bdc99-ebb9-4dc1-92bd-c20e0460b638\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Local Currency\",",
              "    \"toTable\": \"Budget Rate\",",
              "    \"toColumn\": \"From Currency\"",
              "  },",
              "  {",
              "    \"name\": \"4eade231-e4d9-4b9f-8568-0f8dd9162e6f\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"OTD Indicator\",",
              "    \"toTable\": \"On-Time Delivery\",",
              "    \"toColumn\": \"OTD Indicator\"",
              "  },",
              "  {",
              "    \"name\": \"a9b264e6-c155-4643-adc9-e01ad2b308ea\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Product Key\",",
              "    \"toTable\": \"Products\",",
              "    \"toColumn\": \"Product Key\"",
              "  },",
              "  {",
              "    \"name\": \"7572bf1a-bc25-432d-8287-8a015e4ddeab\",",
              "    \"fromTable\": \"Invoices\",",
              "    \"fromColumn\": \"Ship Date\",",
              "    \"toTable\": \"LocalDateTable_6b2c9e31-0c64-4034-8869-3404e703fc01\",",
              "    \"toColumn\": \"Date\",",
              "    \"joinOnDateBehavior\": \"datePartOnly\"",
              "  }",
              "]"
            ]
          }
        ]
      },
      {
        "name": "LocalDateTable_6b2c9e31-0c64-4034-8869-3404e703fc01",
        "isHidden": true,
        "showAsVariationsOnly": true,
        "lineageTag": "75350c61-7dd9-4596-a44b-70861fc28da0",
        "columns": [
          {
            "type": "calculatedTableColumn",
            "name": "Date",
            "dataType": "dateTime",
            "isNameInferred": true,
            "isHidden": true,
            "sourceColumn": "[Date]",
            "lineageTag": "3a2cd88d-5abf-43fd-85b0-17e9f0291387",
            "dataCategory": "PaddedDateTableDates",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Year",
            "dataType": "int64",
            "isHidden": true,
            "expression": "YEAR([Date])",
            "lineageTag": "1d90b7ef-0b1a-43e4-9d43-d35939a89cf5",
            "dataCategory": "Years",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "MonthNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "MONTH([Date])",
            "lineageTag": "d39a4060-5f04-48ca-ae1d-bc6b8addebe4",
            "dataCategory": "MonthOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Month",
            "dataType": "string",
            "isHidden": true,
            "expression": "FORMAT([Date], \"MMMM\")",
            "sortByColumn": "MonthNo",
            "lineageTag": "a086437e-06e2-4243-8ada-9d95f526f535",
            "dataCategory": "Months",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "QuarterNo",
            "dataType": "int64",
            "isHidden": true,
            "expression": "INT(([MonthNo] + 2) / 3)",
            "lineageTag": "80f4881d-db9c-46cb-92af-81af5acc2406",
            "dataCategory": "QuarterOfYear",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Quarter",
            "dataType": "string",
            "isHidden": true,
            "expression": "\"Qtr \" & [QuarterNo]",
            "sortByColumn": "QuarterNo",
            "lineageTag": "d64c2841-2228-48f6-a476-5915b3c2842d",
            "dataCategory": "Quarters",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ]
          },
          {
            "type": "calculated",
            "name": "Day",
            "dataType": "int64",
            "isHidden": true,
            "expression": "DAY([Date])",
            "lineageTag": "f29b5611-19ea-467e-a2a8-8b27e6003bf9",
            "dataCategory": "DayOfMonth",
            "summarizeBy": "none",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ]
          }
        ],
        "partitions": [
          {
            "name": "LocalDateTable_6b2c9e31-0c64-4034-8869-3404e703fc01",
            "mode": "import",
            "source": {
              "type": "calculated",
              "expression": "Calendar(Date(Year(MIN('Invoices'[Ship Date])), 1, 1), Date(Year(MAX('Invoices'[Ship Date])), 12, 31))"
            }
          }
        ],
        "hierarchies": [
          {
            "name": "Date Hierarchy",
            "lineageTag": "b5e32d91-76a5-440f-aebc-4c2532ad7c37",
            "levels": [
              {
                "name": "Year",
                "ordinal": 0,
                "column": "Year",
                "lineageTag": "f513ddaf-5b87-40aa-8b1a-1f3c51660d7d"
              },
              {
                "name": "Quarter",
                "ordinal": 1,
                "column": "Quarter",
                "lineageTag": "d84eaba5-4e47-4ceb-bbc8-9e1b16fa4158"
              },
              {
                "name": "Month",
                "ordinal": 2,
                "column": "Month",
                "lineageTag": "e5386227-1790-4c11-bb23-fc38a1efee21"
              },
              {
                "name": "Day",
                "ordinal": 3,
                "column": "Day",
                "lineageTag": "fbf3e2d1-8198-4044-8b1c-fe727cd8e9b6"
              }
            ],
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ]
          }
        ],
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          },
          {
            "name": "TabularEditor_Relationships",
            "value": "[]"
          }
        ]
      }
    ],
    "relationships": [
      {
        "name": "03e537eb-3ddb-4c20-b5ad-9090c0aadd0d",
        "fromTable": "Customers",
        "fromColumn": "Station",
        "toTable": "Regions",
        "toColumn": "Station"
      },
      {
        "name": "aee91ed3-e637-4150-a8d4-22619ecc0034",
        "fromTable": "Products",
        "fromColumn": "Sub Brand Name",
        "toTable": "Brands",
        "toColumn": "Sub Brand"
      },
      {
        "name": "bbcee627-b8b2-4604-9ad8-9d2036321cfb",
        "fromTable": "Budget",
        "fromColumn": "Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "583c271a-a6ae-4f4b-bdb0-dfc91a31493e",
        "fromTable": "Budget",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "b9c4b659-0116-4f12-af8c-704fe07f3112",
        "fromTable": "Budget",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "4a26dc2c-f944-4c6e-9670-5e66e566c970",
        "fromTable": "Exchange Rate",
        "fromColumn": "Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "1ae64f29-da13-4294-bde5-4320a84af2c1",
        "fromTable": "Orders",
        "fromColumn": "Order Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "34c786fb-4d8e-41d3-a86c-fd83e71d8cc1",
        "fromTable": "Orders",
        "fromColumn": "Request Goods Receipt Date",
        "toTable": "Date",
        "toColumn": "Date",
        "isActive": false
      },
      {
        "name": "6ef67eab-1e07-436d-a358-6197853f0064",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Line Item Status",
        "toTable": "Order Status",
        "toColumn": "Order Status Code"
      },
      {
        "name": "5c8f76eb-7c06-4ed5-bdc2-6368b1f0ef0a",
        "fromTable": "Orders",
        "fromColumn": "Sales Order Document Type Code",
        "toTable": "Order Document Type",
        "toColumn": "Sales Order Document Type Code"
      },
      {
        "name": "7664202a-acbb-4942-a83e-60eb3b8537f9",
        "fromTable": "Orders",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "c97e9cf2-9441-4f5a-8609-f53e6a3a7571",
        "fromTable": "Orders",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      },
      {
        "name": "3795aac2-e6ba-48a7-9722-b7dd7af7b762",
        "fromTable": "Forecast",
        "fromColumn": "Forecast Month",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "599b10ac-8bcb-4550-b452-56d8954b2a35",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Product Type",
        "toTable": "Products",
        "toColumn": "Type"
      },
      {
        "name": "703b86a0-df9c-47d6-82e4-7c457de95971",
        "toCardinality": "many",
        "fromTable": "Forecast",
        "fromColumn": "Region Territory",
        "toTable": "Regions",
        "toColumn": "Territory"
      },
      {
        "name": "d3b21caa-eed5-4a2b-85a1-92a599807a8a",
        "fromTable": "Orders",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "0b2be8fb-09ab-4abc-a26a-c2b736c312b4",
        "fromTable": "Orders",
        "fromColumn": "Billing Date",
        "toTable": "LocalDateTable_fca581ec-8430-42e1-9f91-795770007388",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "1c1cd679-d959-4344-a9d3-e592ae111e42",
        "fromTable": "Orders",
        "fromColumn": "Ship Date",
        "toTable": "LocalDateTable_4ad7e833-9e3a-4bd3-9873-535c2d4d4285",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "0cb7c41d-deae-4c82-b01a-5dbeb9ed834b",
        "fromTable": "Orders",
        "fromColumn": "Confirm Goods Receipt Date",
        "toTable": "LocalDateTable_579bd8be-fc8b-4a18-a637-ab748ff358e0",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "cf55bb82-b832-4bdf-bc81-c415a3504ae9",
        "fromTable": "Last Refresh",
        "fromColumn": "Last Refresh",
        "toTable": "LocalDateTable_595bdce4-ba17-4e98-90af-2d00b0a66670",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "0e6e4252-95c4-4e0e-a4c8-874e5463ec4c",
        "fromTable": "Invoices",
        "fromColumn": "Billing Date",
        "toTable": "Date",
        "toColumn": "Date"
      },
      {
        "name": "7dacb5b5-3b77-45fe-85f9-cdebc76b1d56",
        "fromTable": "Invoices",
        "fromColumn": "Billing Document Type Code",
        "toTable": "Invoice Document Type",
        "toColumn": "Billing Document Type Code"
      },
      {
        "name": "7a4bdc99-ebb9-4dc1-92bd-c20e0460b638",
        "fromTable": "Invoices",
        "fromColumn": "Local Currency",
        "toTable": "Budget Rate",
        "toColumn": "From Currency"
      },
      {
        "name": "4eade231-e4d9-4b9f-8568-0f8dd9162e6f",
        "fromTable": "Invoices",
        "fromColumn": "OTD Indicator",
        "toTable": "On-Time Delivery",
        "toColumn": "OTD Indicator"
      },
      {
        "name": "a9b264e6-c155-4643-adc9-e01ad2b308ea",
        "fromTable": "Invoices",
        "fromColumn": "Product Key",
        "toTable": "Products",
        "toColumn": "Product Key"
      },
      {
        "name": "7572bf1a-bc25-432d-8287-8a015e4ddeab",
        "fromTable": "Invoices",
        "fromColumn": "Ship Date",
        "toTable": "LocalDateTable_6b2c9e31-0c64-4034-8869-3404e703fc01",
        "toColumn": "Date",
        "joinOnDateBehavior": "datePartOnly"
      },
      {
        "name": "9a0268c1-ab7d-d96d-ab2f-c4ba28aaae5c",
        "fromTable": "Invoices",
        "fromColumn": "Customer Key",
        "toTable": "Customers",
        "toColumn": "Customer Key"
      }
    ],
    "cultures": [
      {
        "name": "en-US",
        "linguisticMetadata": {}
      }
    ],
    "perspectives": [
      {
        "name": "No Measure Selection",
        "tables": [
          {
            "name": "Orders",
            "measures": [
              {
                "name": "Total Net Order Quantity"
              },
              {
                "name": "Order Lines"
              },
              {
                "name": "Net Orders (Quantity)"
              },
              {
                "name": "Total Net Order Value"
              },
              {
                "name": "Net Orders"
              },
              {
                "name": "Net Orders 1YP"
              },
              {
                "name": "Net Orders 2YP"
              }
            ]
          },
          {
            "name": "Order Status",
            "columns": [
              {
                "name": "Order Status Group"
              },
              {
                "name": "Order Status Text"
              }
            ]
          },
          {
            "name": "Order Document Type",
            "columns": [
              {
                "name": "Text"
              },
              {
                "name": "Group"
              }
            ]
          },
          {
            "name": "On-Time Delivery",
            "measures": [
              {
                "name": "OTD % (Lines)"
              },
              {
                "name": "OTD (Lines)"
              },
              {
                "name": "OTD (Quantity)"
              },
              {
                "name": "OTD % (Quantity)"
              },
              {
                "name": "OTD (Value)"
              },
              {
                "name": "OTD % (Value)"
              }
            ]
          }
        ]
      },
      {
        "name": "Measure Selection"
      }
    ],
    "expressions": [
      {
        "name": "SqlEndpoint",
        "kind": "m",
        "expression": "\"4vft62jnceaujcmrpa4ib27kuq-ubv5teutsnsufbwwj6ezco7vj4.datawarehouse.fabric.microsoft.com\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "lineageTag": "c5701a1a-761b-4a4f-abb2-8bb5e7de8d4d",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "Database",
        "kind": "m",
        "expression": "\"Curated\" meta [IsParameterQuery=true, Type=\"Text\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "lineageTag": "423d49f9-2077-4e20-b035-c615e286df5e",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "Text"
          }
        ]
      },
      {
        "name": "RangeStart",
        "kind": "m",
        "expression": "#datetime(2020, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "lineageTag": "f5c9c445-899a-4c4a-be86-ec32fc7dfe18",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ]
      },
      {
        "name": "RangeEnd",
        "kind": "m",
        "expression": "#datetime(2026, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type=\"DateTime\", IsParameterQueryRequired=true]",
        "queryGroup": "Parameters",
        "lineageTag": "eafae8e4-e0dd-4b47-8125-3149da661455",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navigation"
          },
          {
            "name": "PBI_ResultType",
            "value": "DateTime"
          }
        ]
      }
    ],
    "queryGroups": [
      {
        "folder": "Parameters",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ]
      },
      {
        "folder": "Scalar Values",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "1"
          }
        ]
      },
      {
        "folder": "Tables",
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "2"
          }
        ]
      }
    ],
    "functions": [
      {
        "name": "Comparison.RelativeToTarget",
        "expression": [
          "//Compare to a target and return the relative percent",
          "//Example usage: Comparing Sales to budget or forecast to get relative performance",
          "//Examples:",
          "// - 9/10 is -10%",
          "// - 11/10 is +10%",
          "(",
          "    // The actual value",
          "    actual: SCALAR NUMERIC VAL,",
          " ",
          "    // The target that you are comparing to",
          "    target: SCALAR NUMERIC VAL",
          ") =>",
          "VAR _target = target",
          "VAR _actual = actual",
          "VAR _delta  = _actual - _target",
          "VAR _percent  = DIVIDE ( _delta, _target )",
          "",
          "RETURN",
          "    _percent",
          ""
        ],
        "lineageTag": "4b641776-6b1e-42c4-8839-1d1fd0fd5fe4"
      }
    ],
    "annotations": [
      {
        "name": "TabularEditor_SerializeOptions",
        "value": "{\"IgnoreInferredObjects\":true,\"IgnoreInferredProperties\":true,\"IgnoreTimestamps\":true,\"SplitMultilineStrings\":true,\"PrefixFilenames\":false,\"LocalTranslations\":true,\"LocalPerspectives\":true,\"LocalRelationships\":true,\"Levels\":[\"Data Sources\",\"Perspectives\",\"Relationships\",\"Roles\",\"Shared Expressions\",\"Tables\",\"Tables/CalculationItems\",\"Tables/Columns\",\"Tables/Hierarchies\",\"Tables/Measures\",\"Tables/Partitions\",\"Translations\"]}"
      },
      {
        "name": "DataGoblins_SnekHighScore",
        "value": "3"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Brands\",\"Budget Rate\",\"Customers\",\"Employees\",\"Exchange Rate\",\"Invoice Document Type\",\"Products\",\"Regions\",\"Budget\",\"Orders\",\"Forecast\",\"Order Document Type\",\"Order Status\",\"SqlEndpoint\",\"Database\",\"RangeStart\",\"RangeEnd\",\"Last Refresh\",\"Invoices\"]"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DaxQueryView_Desktop\",\"TMDLView_Desktop\"]"
      },
      {
        "name": "__PBI_ServiceStoredInTmdl",
        "value": "reserved"
      },
      {
        "name": "TabularEditor_Perspectives",
        "value": "[{\"Name\":\"Measure Selection\",\"Description\":\"\",\"Annotations\":{}},{\"Name\":\"No Measure Selection\",\"Description\":\"\",\"Annotations\":{}}]"
      },
      {
        "name": "__TEdtr",
        "value": "1"
      }
    ]
  }
}